//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

@class UILabel;

@interface AboutUsViewController : BaseNavViewController
{
    UILabel *_appNameLabel;
    UILabel *_appVersionLabel;
}

@property(nonatomic) __weak UILabel *appVersionLabel; // @synthesize appVersionLabel=_appVersionLabel;
@property(nonatomic) __weak UILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
- (void).cxx_destruct;
- (void)downloadClientBtnClick:(id)arg1;
- (void)viewDidLoad;

@end

