//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIFont, UIImage, UIImageView, UILabel;

@interface AJCheckbox : UIButton
{
    _Bool _check;
    _Bool _canChecked;
    id <AJCheckboxDelegate> _privateDelegate;
    long long _checkboxImageAlignment;
    UIImage *_checkedImage;
    UIImage *_uncheckedImage;
    NSString *_title;
    UIFont *_titleFont;
    UILabel *_customTitleLabel;
    UIImageView *_checkboxImageView;
}

@property(retain, nonatomic) UIImageView *checkboxImageView; // @synthesize checkboxImageView=_checkboxImageView;
@property(retain, nonatomic) UILabel *customTitleLabel; // @synthesize customTitleLabel=_customTitleLabel;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool canChecked; // @synthesize canChecked=_canChecked;
@property(nonatomic, getter=isCheck) _Bool check; // @synthesize check=_check;
@property(retain, nonatomic) UIImage *uncheckedImage; // @synthesize uncheckedImage=_uncheckedImage;
@property(retain, nonatomic) UIImage *checkedImage; // @synthesize checkedImage=_checkedImage;
@property(nonatomic) long long checkboxImageAlignment; // @synthesize checkboxImageAlignment=_checkboxImageAlignment;
@property(nonatomic) id <AJCheckboxDelegate> privateDelegate; // @synthesize privateDelegate=_privateDelegate;
- (void).cxx_destruct;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)configDefaultValue;
- (void)setupViews;
- (void)layoutSubviews;
- (void)initViews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

