//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AJHub, AJToast, NSString, UILabel, UIView;

@interface AJToastViewController : UIViewController
{
    AJToast *_toastWindow;
    AJHub *_hubWindow;
    NSString *_toastMessageStr;
    NSString *_hubMessageStr;
    long long _toastPosition;
    UIView *_toastContainView;
    UILabel *_toastMessageLabel;
    UIView *_hubContainView;
}

@property(retain, nonatomic) UIView *hubContainView; // @synthesize hubContainView=_hubContainView;
@property(retain, nonatomic) UILabel *toastMessageLabel; // @synthesize toastMessageLabel=_toastMessageLabel;
@property(retain, nonatomic) UIView *toastContainView; // @synthesize toastContainView=_toastContainView;
@property(nonatomic) long long toastPosition; // @synthesize toastPosition=_toastPosition;
@property(copy, nonatomic) NSString *hubMessageStr; // @synthesize hubMessageStr=_hubMessageStr;
@property(copy, nonatomic) NSString *toastMessageStr; // @synthesize toastMessageStr=_toastMessageStr;
@property(nonatomic) __weak AJHub *hubWindow; // @synthesize hubWindow=_hubWindow;
@property(nonatomic) __weak AJToast *toastWindow; // @synthesize toastWindow=_toastWindow;
- (void).cxx_destruct;
- (void)dismissHub:(CDUnknownBlockType)arg1;
- (void)showHub:(CDUnknownBlockType)arg1;
- (void)refreshHubView;
- (void)dismissToast:(CDUnknownBlockType)arg1;
- (void)showToast:(CDUnknownBlockType)arg1;
- (void)refreshViewFrameWithMessage;
- (void)setupHubView;
- (void)setupToastView;
- (void)viewDidLoad;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;

@end

