//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class AJToastViewController, NSMutableArray, ToastMessage;

@interface AJToast : UIWindow
{
    _Bool _toastBackgroundCanClick;
    _Bool _isShowing;
    AJToastViewController *_toastVC;
    long long _toastPosition;
    NSMutableArray *_messageArray;
    ToastMessage *_showingMsg;
}

+ (id)shareInstance;
@property(retain, nonatomic) ToastMessage *showingMsg; // @synthesize showingMsg=_showingMsg;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(retain, nonatomic) NSMutableArray *messageArray; // @synthesize messageArray=_messageArray;
@property(nonatomic) long long toastPosition; // @synthesize toastPosition=_toastPosition;
@property(retain, nonatomic) AJToastViewController *toastVC; // @synthesize toastVC=_toastVC;
@property(nonatomic) _Bool toastBackgroundCanClick; // @synthesize toastBackgroundCanClick=_toastBackgroundCanClick;
- (void).cxx_destruct;
- (void)showMessage:(id)arg1 position:(long long)arg2 afterDelay:(double)arg3;
- (void)showMessage:(id)arg1 position:(long long)arg2;
- (void)showMessage:(id)arg1 afterDelay:(double)arg2;
- (void)showMessage:(id)arg1;
- (id)oldestMessage;
- (_Bool)checkExist:(id)arg1;
- (void)addMessage:(id)arg1 duration:(double)arg2;
- (void)dismiss;
- (double)topWindowLevel;

@end

