//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APIManagerBase.h"

@interface APIManager : APIManagerBase
{
}

+ (id)initRequest:(id)arg1;
+ (void)requestSafeApiMAQ:(id)arg1 CallBack:(CDUnknownBlockType)arg2;
+ (void)requestSafeApi:(id)arg1 CallBack:(CDUnknownBlockType)arg2;
+ (void)requestApiMAQ:(id)arg1 CallBack:(CDUnknownBlockType)arg2;
+ (void)requestApi:(id)arg1 CallBack:(CDUnknownBlockType)arg2;

@end

