//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppShieldManager : NSObject
{
    NSString *_lastVersion;
}

+ (id)shareManager;
@property(retain, nonatomic) NSString *lastVersion; // @synthesize lastVersion=_lastVersion;
- (void).cxx_destruct;
- (void)checkLastVersion;
- (_Bool)isLastVersion;
- (id)init;

@end

