//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface BaiduMapView : UIView
{
    struct CGImage *m_mapImageRef;
}

- (struct CGImage *)getMapImage;
- (void)setMapImage:(struct CGImage *)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

