//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "NJKWebViewProgressDelegate.h"
#import "UIWebViewDelegate.h"

@class NJKWebViewProgress, NJKWebViewProgressView, NSMutableArray, NSString, UIBarButtonItem, UIView, UIWebView;

@interface BaseWebViewController : BaseNavViewController <NJKWebViewProgressDelegate, UIWebViewDelegate>
{
    UIWebView *_baseWebView;
    NSString *_loadUrl;
    id _willBackViewController;
    NJKWebViewProgress *_progressProxy;
    NJKWebViewProgressView *_progressView;
    UIBarButtonItem *_closeBarItem;
    NSMutableArray *_leftBarItems;
    long long _backTimes;
    UIView *_errView;
}

@property(retain, nonatomic) UIView *errView; // @synthesize errView=_errView;
@property(nonatomic) long long backTimes; // @synthesize backTimes=_backTimes;
@property(retain, nonatomic) NSMutableArray *leftBarItems; // @synthesize leftBarItems=_leftBarItems;
@property(retain, nonatomic) UIBarButtonItem *closeBarItem; // @synthesize closeBarItem=_closeBarItem;
@property(retain, nonatomic) NJKWebViewProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NJKWebViewProgress *progressProxy; // @synthesize progressProxy=_progressProxy;
@property(nonatomic) __weak id willBackViewController; // @synthesize willBackViewController=_willBackViewController;
@property(copy, nonatomic) NSString *loadUrl; // @synthesize loadUrl=_loadUrl;
@property(retain, nonatomic) UIWebView *baseWebView; // @synthesize baseWebView=_baseWebView;
- (void).cxx_destruct;
- (void)executeJS:(id)arg1;
- (void)popToWillBackViewController;
- (void)exitPage;
- (void)closeBarBtnClick;
- (void)popViewController;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewProgress:(id)arg1 updateProgress:(float)arg2;
- (void)startToLoad:(id)arg1;
- (void)checkNetWork;
- (void)viewDidLoad;
- (void)dealloc;
- (void)didReceiveMemoryWarning;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

