//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class NSString, WTReParser;

@interface BaseTextField : UITextField
{
    NSString *_lastAcceptedValue;
    WTReParser *_parser;
}

- (void).cxx_destruct;
- (void)formatInput:(id)arg1;
@property(retain, nonatomic) NSString *pattern;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

