//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMAddressInfoNode : NSObject
{
    NSString *_uid;
    NSString *_name;
    NSString *_address;
    struct BMPoint _point;
    int _nodeType;
    int _nodeFlag;
}

@property(nonatomic) int nodeFlag; // @synthesize nodeFlag=_nodeFlag;
@property(nonatomic) int nodeType; // @synthesize nodeType=_nodeType;
@property(nonatomic) struct BMPoint point; // @synthesize point=_point;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

