//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMBusRouteNode : NSObject
{
    _Bool _bBusStop;
    struct BMPoint _pt;
    NSString *_uid;
    NSString *_name;
}

@property(nonatomic) _Bool bBusStop; // @synthesize bBusStop=_bBusStop;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(nonatomic) struct BMPoint pt; // @synthesize pt=_pt;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

