//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMBusRouteNode, BMCityInfo, BMTaxiInfo, NSArray, NSMutableArray, NSString;

@interface BMCarRoute : NSObject
{
    int _total;
    int _sy;
    int _planKind;
    BMCityInfo *_currentCity;
    BMBusRouteNode *_startPoint;
    BMBusRouteNode *_endPoint;
    NSMutableArray *_wayPoints;
    BMCityInfo *_startCity;
    BMCityInfo *_endCity;
    NSMutableArray *_carRoutes;
    NSString *_urlMd5;
    _Bool _isMutilCityCarRoute;
    BMTaxiInfo *_taxiInfo;
    _Bool _avoid_jam;
}

@property(retain, nonatomic) BMTaxiInfo *taxiInfo; // @synthesize taxiInfo=_taxiInfo;
@property(nonatomic) _Bool isMutilCityCarRoute; // @synthesize isMutilCityCarRoute=_isMutilCityCarRoute;
@property(nonatomic) _Bool avoid_jam; // @synthesize avoid_jam=_avoid_jam;
@property(retain, nonatomic) NSString *urlMd5; // @synthesize urlMd5=_urlMd5;
@property(retain, nonatomic) BMCityInfo *endCity; // @synthesize endCity=_endCity;
@property(retain, nonatomic) BMCityInfo *startCity; // @synthesize startCity=_startCity;
@property(retain, nonatomic) NSArray *wayPoints; // @synthesize wayPoints=_wayPoints;
@property(retain, nonatomic) BMBusRouteNode *endPoint; // @synthesize endPoint=_endPoint;
@property(retain, nonatomic) BMBusRouteNode *startPoint; // @synthesize startPoint=_startPoint;
@property(retain, nonatomic) BMCityInfo *currentCity; // @synthesize currentCity=_currentCity;
@property(retain, nonatomic) NSMutableArray *carRoutes; // @synthesize carRoutes=_carRoutes;
@property(nonatomic) int planKind; // @synthesize planKind=_planKind;
@property(nonatomic) int sy; // @synthesize sy=_sy;
@property(nonatomic) int total; // @synthesize total=_total;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

