//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOverlay.h"

@class BMHeatMapService;

@interface BMHeatMapOverlay : BaseOverlay
{
    unsigned long long _uHeatMaplayerID;
    BMHeatMapService *_heatMapService;
}

+ (void)removeObserverLayers;
+ (void)removeObserverLayer:(id)arg1;
+ (void)addObserverlayer:(id)arg1;
@property(nonatomic) unsigned long long uHeatMaplayerID; // @synthesize uHeatMaplayerID=_uHeatMaplayerID;
@property(retain, nonatomic) BMHeatMapService *heatMapService; // @synthesize heatMapService=_heatMapService;
- (void).cxx_destruct;
- (void)heatMapNeedClean;
- (_Bool)getheatMapDataCallBackInter:(struct CVBundle *)arg1 andLayerID:(unsigned long long)arg2;
- (void)show:(_Bool)arg1;
- (void)removeHeatMapLayer;
- (void)updateHeatMapLayer;
- (void)initHeatMapLayer;
- (void)dealloc;
- (void)uninit;
- (id)initWithMapView:(id)arg1;

@end

