//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMKAddressComponent : NSObject
{
    NSString *_streetNumber;
    NSString *_streetName;
    NSString *_district;
    NSString *_city;
    NSString *_province;
}

@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *district; // @synthesize district=_district;
@property(retain, nonatomic) NSString *streetName; // @synthesize streetName=_streetName;
@property(retain, nonatomic) NSString *streetNumber; // @synthesize streetNumber=_streetNumber;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

