//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKOverlayGLBasicView.h"

@class BMKArcline;

@interface BMKArclineView : BMKOverlayGLBasicView
{
}

- (void)glRender;
@property(readonly, nonatomic) BMKArcline *arcline;
- (id)initWithArcline:(id)arg1;
- (id)initWithOverlay:(id)arg1;

@end

