//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKBasePoiSearchOption.h"

@interface BMKBoundSearchOption : BMKBasePoiSearchOption
{
    CDStruct_2c43369c _leftBottom;
    CDStruct_2c43369c _rightTop;
}

@property(nonatomic) CDStruct_c3b9c2ee rightTop; // @synthesize rightTop=_rightTop;
@property(nonatomic) CDStruct_c3b9c2ee leftBottom; // @synthesize leftBottom=_leftBottom;
- (id)init;

@end

