//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKCloudSearchInfo.h"

@class NSString;

@interface BMKCloudBoundSearchInfo : BMKCloudSearchInfo
{
    NSString *_bounds;
}

@property(retain, nonatomic) NSString *bounds; // @synthesize bounds=_bounds;
- (void).cxx_destruct;
- (id)getUrlString;
- (void)dealloc;
- (id)init;

@end

