//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKBaseCloudSearchInfo.h"

@class NSString;

@interface BMKCloudSearchInfo : BMKBaseCloudSearchInfo
{
    NSString *_keyword;
    NSString *_tags;
    NSString *_sortby;
    NSString *_filter;
    long long _pageIndex;
    long long _pageSize;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(retain, nonatomic) NSString *filter; // @synthesize filter=_filter;
@property(retain, nonatomic) NSString *sortby; // @synthesize sortby=_sortby;
@property(retain, nonatomic) NSString *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
- (void).cxx_destruct;
- (id)getUrlString;
- (void)dealloc;
- (id)init;

@end

