//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMKGeoCodeResult, BMKGeoCodeSearch, BMKReverseGeoCodeResult;

@protocol BMKGeoCodeSearchDelegate <NSObject>

@optional
- (void)onGetReverseGeoCodeResult:(BMKGeoCodeSearch *)arg1 result:(BMKReverseGeoCodeResult *)arg2 errorCode:(int)arg3;
- (void)onGetGeoCodeResult:(BMKGeoCodeSearch *)arg1 result:(BMKGeoCodeResult *)arg2 errorCode:(int)arg3;
@end

