//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKOverlayView.h"

@class NSArray, UIColor;

@interface BMKOverlayPathView : BMKOverlayView
{
    UIColor *_fillColor;
    UIColor *_strokeColor;
    double _lineWidth;
    int _lineJoin;
    int _lineCap;
    double _miterLimit;
    double _lineDashPhase;
    NSArray *_lineDashPattern;
    struct CGPath *_path;
    int lineJoin;
    int lineCap;
    UIColor *fillColor;
    UIColor *strokeColor;
    double lineWidth;
    double miterLimit;
    double lineDashPhase;
    NSArray *lineDashPattern;
    struct CGPath *path;
}

@property struct CGPath *path; // @synthesize path;
@property(copy) NSArray *lineDashPattern; // @synthesize lineDashPattern;
@property double lineDashPhase; // @synthesize lineDashPhase;
@property double miterLimit; // @synthesize miterLimit;
@property int lineCap; // @synthesize lineCap;
@property int lineJoin; // @synthesize lineJoin;
@property double lineWidth; // @synthesize lineWidth;
@property(retain) UIColor *strokeColor; // @synthesize strokeColor;
@property(retain) UIColor *fillColor; // @synthesize fillColor;
- (void).cxx_destruct;
- (void)setNeedsDisplayInMapRect:(CDStruct_90e2a262)arg1;
- (void)drawMapRect:(CDStruct_90e2a262)arg1 zoomScale:(double)arg2 inContext:(struct CGContext *)arg3;
- (_Bool)canDrawMapRect:(CDStruct_90e2a262)arg1 zoomScale:(double)arg2;
- (void)fillPath:(struct CGPath *)arg1 inContext:(struct CGContext *)arg2;
- (void)strokePath:(struct CGPath *)arg1 inContext:(struct CGContext *)arg2;
- (void)applyFillPropertiesToContext:(struct CGContext *)arg1 atZoomScale:(double)arg2;
- (void)applyStrokePropertiesToContext:(struct CGContext *)arg1 atZoomScale:(double)arg2;
- (void)invalidatePath;
- (void)createPath;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithOverlay:(id)arg1;
- (id)init;

@end

