//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMKOpenOption : NSObject
{
    _Bool isSupportWeb;
    NSString *appScheme;
}

@property(nonatomic) _Bool isSupportWeb; // @synthesize isSupportWeb;
@property(retain, nonatomic) NSString *appScheme; // @synthesize appScheme;
- (void).cxx_destruct;
- (id)init;

@end

