//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKBasePoiSearchOption.h"

@class NSString;

@interface BMKPoiIndoorSearchOption : BMKBasePoiSearchOption
{
    NSString *_indoorId;
    NSString *_floor;
}

@property(retain, nonatomic) NSString *floor; // @synthesize floor=_floor;
@property(retain, nonatomic) NSString *indoorId; // @synthesize indoorId=_indoorId;
- (void).cxx_destruct;

@end

