//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMKPlanNode;

@interface BMKRoutePlanShareURLOption : NSObject
{
    int _routePlanType;
    BMKPlanNode *_from;
    BMKPlanNode *_to;
    unsigned long long _cityID;
    unsigned long long _routeIndex;
}

@property(nonatomic) unsigned long long routeIndex; // @synthesize routeIndex=_routeIndex;
@property(nonatomic) unsigned long long cityID; // @synthesize cityID=_cityID;
@property(retain, nonatomic) BMKPlanNode *to; // @synthesize to=_to;
@property(retain, nonatomic) BMKPlanNode *from; // @synthesize from=_from;
@property(nonatomic) int routePlanType; // @synthesize routePlanType=_routePlanType;
- (void).cxx_destruct;

@end

