//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMKAddressComponent, NSArray, NSString;

@interface BMKReverseGeoCodeResult : NSObject
{
    BMKAddressComponent *_addressDetail;
    NSString *_address;
    CDStruct_2c43369c _location;
    NSArray *_poiList;
    NSString *_businessCircle;
}

@property(retain, nonatomic) NSString *businessCircle; // @synthesize businessCircle=_businessCircle;
@property(retain, nonatomic) NSArray *poiList; // @synthesize poiList=_poiList;
@property(nonatomic) CDStruct_c3b9c2ee location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) BMKAddressComponent *addressDetail; // @synthesize addressDetail=_addressDetail;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

