//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMKDateRange;

@interface BMKRadarNearbySearchOption : NSObject
{
    int _sortType;
    unsigned long long _radius;
    long long _pageIndex;
    long long _pageCapacity;
    BMKDateRange *_dateRange;
    CDStruct_2c43369c _centerPt;
}

@property(retain, nonatomic) BMKDateRange *dateRange; // @synthesize dateRange=_dateRange;
@property(nonatomic) int sortType; // @synthesize sortType=_sortType;
@property(nonatomic) long long pageCapacity; // @synthesize pageCapacity=_pageCapacity;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(nonatomic) unsigned long long radius; // @synthesize radius=_radius;
@property(nonatomic) CDStruct_c3b9c2ee centerPt; // @synthesize centerPt=_centerPt;
- (void).cxx_destruct;
- (id)init;

@end

