//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMRadarDelegate.h"

@class BMRadar, NSMutableArray, NSString, NSTimer;

@interface BMKRadarManager : NSObject <BMRadarDelegate>
{
    BMRadar *_radar;
    _Bool _autoUploadIsOn;
    NSTimer *_autoUploadTimer;
    long long _curPageIndex;
    long long _pageCapacity;
    double _lastUploadTimeStamp;
    NSMutableArray *_delegateList;
    NSString *_userId;
}

+ (id)alloc;
+ (void)releaseRadarManagerInstance;
+ (id)getRadarManagerInstance;
+ (void)initialize;
- (void).cxx_destruct;
- (id)getNSStringFromCVString:(struct CVString *)arg1;
- (_Bool)parseRadarNearbySearchResult:(id)arg1 rarderResult:(id)arg2;
- (void)handleRadarNearbyResult:(long long)arg1 string:(id)arg2;
- (void)handleRadarClearResult:(long long)arg1;
- (void)handleRadarUploadResult:(long long)arg1;
- (int)getErrorCodeWithResStatus:(long long)arg1;
- (_Bool)getRadarNearbySearchRequest:(id)arg1;
- (_Bool)clearMyInfoRequest;
- (_Bool)uploadInfoRequest:(id)arg1;
- (void)stopAutoUpload;
- (void)autoUploadTimerAction;
- (void)startAutoUpload:(double)arg1;
- (void)removeRadarManagerDelegate:(id)arg1;
- (void)addRadarManagerDelegate:(id)arg1;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

