//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMKOverlay.h"

@class MapView, NSString;

@interface BMKTileLayer : NSObject <BMKOverlay>
{
    unsigned long long _tileLayerID;
    MapView *_mapView;
    long long _minZoom;
    long long _maxZoom;
    CDStruct_2c43369c _coordinate;
    CDStruct_02837cd9 _visibleMapRect;
    CDStruct_02837cd9 _boundingMapRect;
}

@property(readonly, nonatomic) CDStruct_90e2a262 boundingMapRect; // @synthesize boundingMapRect=_boundingMapRect;
@property(nonatomic) CDStruct_90e2a262 visibleMapRect; // @synthesize visibleMapRect=_visibleMapRect;
@property(nonatomic) long long maxZoom; // @synthesize maxZoom=_maxZoom;
@property(nonatomic) long long minZoom; // @synthesize minZoom=_minZoom;
@property(nonatomic) __weak MapView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) unsigned long long tileLayerID; // @synthesize tileLayerID=_tileLayerID;
@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate;
- (void).cxx_destruct;
- (_Bool)intersectsMapRect:(CDStruct_90e2a262)arg1;
- (_Bool)checkDataValid;
- (void)setTileShowPara;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

