//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSString;

@interface BMPOIInfo : NSObject
{
    struct BMPoint _GEO;
    NSString *_name;
    long long _type;
    NSString *_UID;
    NSString *_address;
    NSArray *_tel;
    NSString *_zip;
    _Bool _isContainDeepDetail;
    _Bool _accFlag;
    long long _distance;
    NSMutableDictionary *_placeInfo;
    NSString *_rpdes;
}

@property(retain, nonatomic) NSString *rpdes; // @synthesize rpdes=_rpdes;
@property(retain, nonatomic) NSMutableDictionary *placeInfo; // @synthesize placeInfo=_placeInfo;
@property(nonatomic) long long distance; // @synthesize distance=_distance;
@property(nonatomic) _Bool accFlag; // @synthesize accFlag=_accFlag;
@property(nonatomic) _Bool isContainDeepDetail; // @synthesize isContainDeepDetail=_isContainDeepDetail;
@property(retain, nonatomic) NSString *zip; // @synthesize zip=_zip;
@property(retain, nonatomic) NSArray *tel; // @synthesize tel=_tel;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *UID; // @synthesize UID=_UID;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) struct BMPoint GEO; // @synthesize GEO=_GEO;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

