//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMUpDataInfo : NSObject
{
    int _upMode;
    NSString *_compressName;
    NSString *_contentMD5;
    NSString *_rootDIR;
    NSString *_modulVersion;
    NSString *_upURL;
    NSString *_deleteFiles;
    NSString *_alterFiles;
    NSString *_modulFiles;
    NSString *_fullpathFile;
}

@property(retain, nonatomic) NSString *fullpathFile; // @synthesize fullpathFile=_fullpathFile;
@property(retain, nonatomic) NSString *modulFiles; // @synthesize modulFiles=_modulFiles;
@property(retain, nonatomic) NSString *alterFiles; // @synthesize alterFiles=_alterFiles;
@property(retain, nonatomic) NSString *deleteFiles; // @synthesize deleteFiles=_deleteFiles;
@property(nonatomic) int upMode; // @synthesize upMode=_upMode;
@property(retain, nonatomic) NSString *upURL; // @synthesize upURL=_upURL;
@property(retain, nonatomic) NSString *modulVersion; // @synthesize modulVersion=_modulVersion;
@property(retain, nonatomic) NSString *rootDIR; // @synthesize rootDIR=_rootDIR;
@property(retain, nonatomic) NSString *contentMD5; // @synthesize contentMD5=_contentMD5;
@property(retain, nonatomic) NSString *compressName; // @synthesize compressName=_compressName;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

