//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface BTGCrashInfo : NSObject
{
    NSString *_name;
    NSString *_reason;
    NSString *_className;
    NSString *_method;
    NSString *_lineNumber;
    NSString *_cause;
    NSArray *_stack;
    NSArray *_returnAddresses;
}

@property(retain, nonatomic) NSArray *returnAddresses; // @synthesize returnAddresses=_returnAddresses;
@property(retain, nonatomic) NSArray *stack; // @synthesize stack=_stack;
@property(retain, nonatomic) NSString *cause; // @synthesize cause=_cause;
@property(retain, nonatomic) NSString *lineNumber; // @synthesize lineNumber=_lineNumber;
@property(retain, nonatomic) NSString *method; // @synthesize method=_method;
@property(retain, nonatomic) NSString *className; // @synthesize className=_className;
@property(retain, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)json;
- (id)dictionary;

@end

