//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTGBaseView.h"

#import "BTGTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class BTGTagMenuButton, BTGTagView, BTGTextView, NSDictionary, NSMutableArray, NSString, UIButton, UIPageControl, UITableView, UIView;

@interface BTGCreateTagView : BTGBaseView <UITextViewDelegate, UITableViewDataSource, UITableViewDelegate, BTGTableViewCellDelegate>
{
    int _type;
    int _priority;
    NSString *_content;
    id <BTGCreateTagViewDelegate> _delegate;
    NSDictionary *_assignee;
    BTGTagView *_tagView;
    BTGTextView *_textView;
    UITableView *_tableView;
    UIPageControl *_pageControl;
    UIView *_containerView;
    UIView *_priorityView;
    UIView *_assigneeView;
    BTGTagMenuButton *_typeButton;
    BTGTagMenuButton *_priorityButton;
    BTGTagMenuButton *_assigneeButton;
    UIButton *_submitButton;
    UIButton *_cancelButton;
    NSMutableArray *_priorityButtons;
    NSMutableArray *_members;
    struct CGPoint _position;
}

+ (id)createWithTagView:(id)arg1 delegate:(id)arg2;
+ (id)createWithPosition:(struct CGPoint)arg1 delegate:(id)arg2;
@property(retain, nonatomic) NSMutableArray *members; // @synthesize members=_members;
@property(retain, nonatomic) NSMutableArray *priorityButtons; // @synthesize priorityButtons=_priorityButtons;
@property(nonatomic) __weak UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(nonatomic) __weak BTGTagMenuButton *assigneeButton; // @synthesize assigneeButton=_assigneeButton;
@property(nonatomic) __weak BTGTagMenuButton *priorityButton; // @synthesize priorityButton=_priorityButton;
@property(nonatomic) __weak BTGTagMenuButton *typeButton; // @synthesize typeButton=_typeButton;
@property(retain, nonatomic) UIView *assigneeView; // @synthesize assigneeView=_assigneeView;
@property(retain, nonatomic) UIView *priorityView; // @synthesize priorityView=_priorityView;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak BTGTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak BTGTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) NSDictionary *assignee; // @synthesize assignee=_assignee;
@property(nonatomic) int priority; // @synthesize priority=_priority;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(nonatomic) __weak id <BTGCreateTagViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onButtonClick:(id)arg1;
- (void)pageChanged:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableViewCell:(id)arg1 touchUpInView:(id)arg2 data:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismiss;
- (void)showInView:(id)arg1;
- (void)onPriorityItemClick:(id)arg1;
- (void)toggleView:(id)arg1 sender:(id)arg2;
- (void)onTagMenuClick:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)awakeFromNib;
- (void)initialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

