//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary, NSString;

@interface BTGIssue : NSObject <NSCoding>
{
    int _type;
    int _state;
    NSString *_uuid;
    NSString *_des;
    NSMutableDictionary *_image;
    NSMutableDictionary *_env;
    NSMutableDictionary *_log;
}

+ (id)issue;
@property(nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) NSMutableDictionary *log; // @synthesize log=_log;
@property(retain, nonatomic) NSMutableDictionary *env; // @synthesize env=_env;
@property(retain, nonatomic) NSMutableDictionary *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *des; // @synthesize des=_des;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (id)json;
- (id)dictionary;
- (void)removeAllTags;
- (void)addTag:(id)arg1;
- (void)setImageUrl:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

