//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTGQueue, NSMutableDictionary, NSObject<OS_dispatch_source>;

@interface BTGLoggerCatcher : NSObject
{
    NSObject<OS_dispatch_source> *_source;
    long long _consoleLogId;
    _Bool _trackingUserSteps;
    _Bool _trackingConsoleLog;
    _Bool _trackingNetwork;
    _Bool _pause;
    NSMutableDictionary *_userData;
    BTGQueue *_userStepLogs;
    BTGQueue *_consoleLogs;
    BTGQueue *_bugtagsLogs;
    BTGQueue *_networkLogs;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool pause; // @synthesize pause=_pause;
@property(nonatomic, getter=isTrackingNetwork) _Bool trackingNetwork; // @synthesize trackingNetwork=_trackingNetwork;
@property(nonatomic, getter=isTrackingConsoleLog) _Bool trackingConsoleLog; // @synthesize trackingConsoleLog=_trackingConsoleLog;
@property(nonatomic, getter=isTrackingUserSteps) _Bool trackingUserSteps; // @synthesize trackingUserSteps=_trackingUserSteps;
@property(retain, nonatomic) BTGQueue *networkLogs; // @synthesize networkLogs=_networkLogs;
@property(retain, nonatomic) BTGQueue *bugtagsLogs; // @synthesize bugtagsLogs=_bugtagsLogs;
@property(retain, nonatomic) BTGQueue *consoleLogs; // @synthesize consoleLogs=_consoleLogs;
@property(retain, nonatomic) BTGQueue *userStepLogs; // @synthesize userStepLogs=_userStepLogs;
@property(retain, nonatomic) NSMutableDictionary *userData; // @synthesize userData=_userData;
- (void).cxx_destruct;
- (void)clearAllLogs;
- (void)removeAllNetworkLogs;
- (void)removeAllBugtagsLogs;
- (void)removeAllConsoleLogs;
- (void)removeAllUserStepLogs;
- (void)removeAllUserData;
- (void)removeUserDataForKey:(id)arg1;
- (void)setUserData:(id)arg1 forKey:(id)arg2;
- (id)formatLog:(id)arg1 time:(double)arg2;
- (void)updateConsoleLogs;
- (void)logNetwork:(id)arg1;
- (void)logUserStep:(id)arg1;
- (void)logBugtags:(id)arg1;
- (void)application:(id)arg1;
- (id)init;

@end

