//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BTGBaseViewController.h"

@interface BTGScreenshotViewController : BTGBaseViewController
{
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (id)init;

@end

