//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BTGCreateTagViewDelegate.h"
#import "BTGTagViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class BTGIssue, NSMutableArray, NSString, UIImage, UIImageView, UIWindow;

@interface BTGScreenshotView : UIView <BTGCreateTagViewDelegate, BTGTagViewDelegate, UIAlertViewDelegate, UIGestureRecognizerDelegate>
{
    UIImage *_image;
    NSMutableArray *_tags;
    BTGIssue *_issue;
    UIImageView *_imageView;
    UIImageView *_pinImageView;
    UIWindow *_screenshotWindow;
}

+ (id)createWithImage:(id)arg1;
@property(retain, nonatomic) UIWindow *screenshotWindow; // @synthesize screenshotWindow=_screenshotWindow;
@property(retain, nonatomic) UIImageView *pinImageView; // @synthesize pinImageView=_pinImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) BTGIssue *issue; // @synthesize issue=_issue;
@property(retain, nonatomic) NSMutableArray *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)dealloc;
- (void)discard;
- (_Bool)submit;
- (void)removeAllTags;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tagViewDidLongPress:(id)arg1;
- (void)createTagViewDidCancel:(id)arg1;
- (void)createTagViewDidOK:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleGesture:(id)arg1;
- (void)showTagTipsView;
- (void)dismiss;
- (void)show;
- (void)applicationWillEnterForeground:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

