//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface BugtagsOptions : NSObject <NSCopying>
{
    _Bool _trackingCrashes;
    _Bool _trackingUserSteps;
    _Bool _trackingConsoleLog;
    _Bool _trackingUserLocation;
    _Bool _trackingNetwork;
    _Bool _trackingNetworkContinueWithInvalidCertificate;
    _Bool _crashWithScreenshot;
    _Bool _ignorePIPESignalCrash;
    NSString *_trackingNetworkURLFilter;
    unsigned long long _supportedInterfaceOrientations;
    NSString *_version;
    NSString *_build;
}

@property(copy, nonatomic) NSString *build; // @synthesize build=_build;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(nonatomic) unsigned long long supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
@property(nonatomic) _Bool ignorePIPESignalCrash; // @synthesize ignorePIPESignalCrash=_ignorePIPESignalCrash;
@property(nonatomic) _Bool crashWithScreenshot; // @synthesize crashWithScreenshot=_crashWithScreenshot;
@property(nonatomic) _Bool trackingNetworkContinueWithInvalidCertificate; // @synthesize trackingNetworkContinueWithInvalidCertificate=_trackingNetworkContinueWithInvalidCertificate;
@property(copy, nonatomic) NSString *trackingNetworkURLFilter; // @synthesize trackingNetworkURLFilter=_trackingNetworkURLFilter;
@property(nonatomic) _Bool trackingNetwork; // @synthesize trackingNetwork=_trackingNetwork;
@property(nonatomic) _Bool trackingUserLocation; // @synthesize trackingUserLocation=_trackingUserLocation;
@property(nonatomic) _Bool trackingConsoleLog; // @synthesize trackingConsoleLog=_trackingConsoleLog;
@property(nonatomic) _Bool trackingUserSteps; // @synthesize trackingUserSteps=_trackingUserSteps;
@property(nonatomic) _Bool trackingCrashes; // @synthesize trackingCrashes=_trackingCrashes;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

