//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CalendarDateUtil : NSObject
{
}

+ (id)dateSinceNowWithInterval:(long long)arg1;
+ (long long)numberOfDaysInMonth:(long long)arg1 year:(long long)arg2;
+ (long long)getDayWithDate:(id)arg1;
+ (long long)getMonthWithDate:(id)arg1;
+ (long long)getCurrentDay;
+ (long long)getCurrentMonth;
+ (long long)getCurrentYear;
+ (long long)numberOfDaysInMonth:(long long)arg1;
+ (_Bool)isLeapYear:(long long)arg1;

@end

