//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChatBaseBean.h"

@class NSString;

@interface ChatUserInfoBean : ChatBaseBean
{
    NSString *_userId;
    NSString *_name;
    NSString *_headUrl;
    long long _accountStatus;
    long long _logoStatus;
    long long _fromType;
    long long _type;
}

+ (id)shareInstance;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long fromType; // @synthesize fromType=_fromType;
@property(nonatomic) long long logoStatus; // @synthesize logoStatus=_logoStatus;
@property(nonatomic) long long accountStatus; // @synthesize accountStatus=_accountStatus;
@property(retain, nonatomic) NSString *headUrl; // @synthesize headUrl=_headUrl;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

@end

