//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChatBaseViewController.h"

#import "ChatGroupSettingViewControllerDelegate.h"

@class NSString;

@interface ChatGroupViewController : ChatBaseViewController <ChatGroupSettingViewControllerDelegate>
{
}

- (void)toChatViewCtrl:(id)arg1 conversationBean:(id)arg2 chatType:(unsigned long long)arg3;
- (void)toChatGroupSettingViewCtrl:(id)arg1;
- (void)getIMUserInfo:(id)arg1;
- (void)removeMessageSuccess;
- (void)didReceiveMessage:(id)arg1;
- (void)routerEventWithName:(id)arg1 userInfo:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)checkIMUser:(id)arg1;
- (_Bool)isChatGroup;
- (void)rightBtnHandler:(id)arg1;
- (id)umPageKey;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

