//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSString;

@interface ChatterInfoModel : ObjectBeanBase
{
    NSString *_uid;
    NSString *_headUrl;
    NSString *_name;
}

+ (id)chatterInfoArrayWithGroupMemberArray:(id)arg1;
+ (id)chatterInfoArrayWithChatUserInfoBeanArray:(id)arg1;
+ (id)chatterInfoArrayWithIMUserInfoBeanArray:(id)arg1;
+ (id)chatterInfoArrayWithGroupInfoArray:(id)arg1;
+ (id)initWithGroupMemberInfo:(id)arg1;
+ (id)initWithChatExt:(id)arg1;
+ (id)initWithChatUserInfoBean:(id)arg1;
+ (id)initWithIMUserInfoBean:(id)arg1;
+ (id)initWithGroupInfo:(id)arg1;
+ (id)majorKey;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *headUrl; // @synthesize headUrl=_headUrl;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

