//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonCellBase.h"

@class UILabel, UIView;

@interface CommonDetailVerticalContentCell : CommonCellBase
{
    UIView *_customView;
    double _contentViewHeight;
    UILabel *_lblTitle;
    UIView *_verticalContentView;
}

@property(nonatomic) __weak UIView *verticalContentView; // @synthesize verticalContentView=_verticalContentView;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle=_lblTitle;
@property(nonatomic) double contentViewHeight; // @synthesize contentViewHeight=_contentViewHeight;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
- (void).cxx_destruct;
- (double)cellHeight;
- (void)setDataSource:(id)arg1;

@end

