//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CommonCellModelBase, NSDictionary;

@protocol CommonCellModelBaseGenerator <NSObject>

@optional
- (NSDictionary *)generatorModelsWithDataSource:(id)arg1;
- (CommonCellModelBase *)generatorModelWithDataSource:(id)arg1;
@end

