//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CompassOverlay, MapView, TapDetectingView, UIImageView;

@interface CompassView : UIView
{
    TapDetectingView *_tapDetectingView;
    UIImageView *_compassView;
    UIImageView *_compassBackGroundView;
    CompassOverlay *_compassLay;
    MapView *_matchInternalMap;
}

@property(nonatomic) __weak MapView *matchInternalMap; // @synthesize matchInternalMap=_matchInternalMap;
@property(nonatomic) __weak CompassOverlay *compassLay; // @synthesize compassLay=_compassLay;
@property(retain, nonatomic) TapDetectingView *tapDetectingView; // @synthesize tapDetectingView=_tapDetectingView;
- (void).cxx_destruct;
- (void)hideCompassAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)hideCompassAnimation;
- (void)update;
- (void)onClickCompass;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setCompassImage:(id)arg1;
- (id)init;
- (void)dealloc;

@end

