//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISegmentedControl.h"

@class NSMutableArray, UIColor, UIImageView, UIView;

@interface CustomSegmentedControl : UISegmentedControl
{
    long long _selectedSegmentIndex;
    long long _segmentCount;
    NSMutableArray *_items;
    double _arrowSize;
    UIColor *_selectedColor;
    UIColor *_unSelectedColor;
    UIColor *_lineColor;
    UIImageView *_segmentBgView;
    UIView *_selectedLine;
    UIView *_bottomLine;
}

@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *selectedLine; // @synthesize selectedLine=_selectedLine;
@property(retain, nonatomic) UIImageView *segmentBgView; // @synthesize segmentBgView=_segmentBgView;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) UIColor *unSelectedColor; // @synthesize unSelectedColor=_unSelectedColor;
@property(retain, nonatomic) UIColor *selectedColor; // @synthesize selectedColor=_selectedColor;
@property(nonatomic) double arrowSize; // @synthesize arrowSize=_arrowSize;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)handleSelect:(id)arg1;
- (void)drawSelectedMaskAtPosition:(double)arg1;
- (void)layoutSegments;
- (void)layoutSubviews;
- (void)setBottemLineOffest:(double)arg1;
- (long long)selectedSegmentIndex;
- (void)setSelectedSegmentIndex:(long long)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (unsigned long long)numberOfSegments;
- (void)removeAllSegments;
- (void)removeSegmentAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)showNewLogoWithIndex:(long long)arg1 show:(_Bool)arg2;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (id)titleForSegmentAtIndex:(unsigned long long)arg1;
- (void)setTitle:(id)arg1 forSegmentAtIndex:(unsigned long long)arg2;
- (void)setImage:(id)arg1 forSegmentAtIndex:(unsigned long long)arg2;
- (id)imageForSegmentAtIndex:(unsigned long long)arg1;
- (void)insertSegmentWithImage:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)commonInit;
- (id)initWithItems:(id)arg1;
- (id)init;

@end

