//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface DDXMLNode : NSObject <NSCopying>
{
    struct _xmlKind *genericPtr;
    DDXMLNode *owner;
}

+ (id)lastError;
+ (void)removeAllChildrenFromNode:(struct _xmlNode *)arg1;
+ (void)removeChild:(struct _xmlNode *)arg1;
+ (void)detachChild:(struct _xmlNode *)arg1;
+ (void)detachChild:(struct _xmlNode *)arg1 andClean:(_Bool)arg2 andFixNamespaces:(_Bool)arg3;
+ (void)removeAllAttributesFromNode:(struct _xmlNode *)arg1;
+ (void)removeAttribute:(struct _xmlAttr *)arg1;
+ (void)detachAttribute:(struct _xmlAttr *)arg1;
+ (void)detachAttribute:(struct _xmlAttr *)arg1 andClean:(_Bool)arg2;
+ (void)removeAllNamespacesFromNode:(struct _xmlNode *)arg1;
+ (void)removeNamespace:(struct _xmlNs *)arg1 fromNode:(struct _xmlNode *)arg2;
+ (void)detachNamespace:(struct _xmlNs *)arg1 fromNode:(struct _xmlNode *)arg2;
+ (void)recursiveFixDefaultNamespacesInNode:(struct _xmlNode *)arg1 withNewRoot:(struct _xmlNode *)arg2;
+ (void)recursiveMigrateNamespace:(struct _xmlNs *)arg1 to:(struct _xmlNs *)arg2 node:(struct _xmlNode *)arg3;
+ (void)recursiveStripNamespace:(struct _xmlNs *)arg1 fromNode:(struct _xmlNode *)arg2;
+ (void)recursiveStripDocPointersFromNode:(struct _xmlNode *)arg1;
+ (void)stripDocPointersFromAttr:(struct _xmlAttr *)arg1;
+ (id)prefixForName:(id)arg1;
+ (id)localNameForName:(id)arg1;
+ (void)getPrefix:(id *)arg1 localName:(id *)arg2 forName:(id)arg3;
+ (void)getHasPrefix:(_Bool *)arg1 localName:(id *)arg2 forName:(id)arg3;
+ (id)nodeWithPrimitive:(struct _xmlKind *)arg1 owner:(id)arg2;
+ (id)nodeWithUnknownPrimitive:(struct _xmlKind *)arg1 owner:(id)arg2;
+ (id)textWithStringValue:(id)arg1;
+ (id)commentWithStringValue:(id)arg1;
+ (id)processingInstructionWithName:(id)arg1 stringValue:(id)arg2;
+ (id)namespaceWithName:(id)arg1 stringValue:(id)arg2;
+ (id)attributeWithName:(id)arg1 URI:(id)arg2 stringValue:(id)arg3;
+ (id)attributeWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1 URI:(id)arg2;
+ (id)elementWithName:(id)arg1 children:(id)arg2 attributes:(id)arg3;
+ (id)elementWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (_Bool)_hasParent;
- (id)nodesForXPath:(id)arg1 error:(id *)arg2;
- (id)XMLStringWithOptions:(unsigned long long)arg1;
- (id)XMLString;
- (id)description;
- (id)URI;
- (void)setURI:(id)arg1;
- (id)prefix;
- (id)localName;
- (id)XPath;
- (struct _xmlStd *)_XPathPreProcess:(id)arg1;
- (void)detach;
- (id)nextNode;
- (id)previousNode;
- (id)nextSibling;
- (id)previousSibling;
- (id)childAtIndex:(unsigned long long)arg1;
- (id)children;
- (unsigned long long)childCount;
- (id)parent;
- (id)rootDocument;
- (unsigned long long)level;
- (unsigned long long)index;
- (id)stringValue;
- (void)setStringValue:(id)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (unsigned long long)kind;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithPrimitive:(struct _xmlKind *)arg1 owner:(id)arg2;

@end

