//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DebugModelBase.h"

@class JWEnvironmentBase, NSString;

@interface DebugModel : DebugModelBase
{
    NSString *_name;
    NSString *_scheme;
    NSString *_host;
    JWEnvironmentBase *_environment;
}

+ (id)initWithJWEnvironment:(id)arg1;
@property(retain, nonatomic) JWEnvironmentBase *environment; // @synthesize environment=_environment;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)readWithKey:(id)arg1;

@end

