//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePopView.h"

#import "DebugDatasource.h"
#import "DebugDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UIImageView, UILabel, UITableView, UIView;

@interface DebugListPopView : BasePopView <UITableViewDataSource, UITableViewDelegate, DebugDatasource, DebugDelegate>
{
    id <DebugListPopViewDelegate> _debugListPopViewDelegate;
    UIView *_titleView;
    UILabel *_titleLab;
    UIImageView *_topLineView;
    UIView *_contentView;
    UITableView *_tableView;
    NSArray *_dataSource;
}

@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImageView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(nonatomic) __weak id <DebugListPopViewDelegate> debugListPopViewDelegate; // @synthesize debugListPopViewDelegate=_debugListPopViewDelegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onShow:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithMessage:(id)arg1 dataSource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

