//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView, XHMessageTextView;

@protocol DXMessageToolBarDelegate <NSObject>
- (void)didChangeFrameToHeight:(double)arg1;

@optional
- (void)didDragInsideAction:(UIView *)arg1;
- (void)didDragOutsideAction:(UIView *)arg1;
- (void)didFinishRecoingVoiceAction:(UIView *)arg1;
- (void)didCancelRecordingVoiceAction:(UIView *)arg1;
- (void)didStartRecordingVoiceAction:(UIView *)arg1;
- (void)didSendFace:(NSString *)arg1;
- (void)didSendText:(NSString *)arg1;
- (void)inputTextViewWillBeginEditing:(XHMessageTextView *)arg1;
- (void)inputTextViewDidBeginEditing:(XHMessageTextView *)arg1;
- (void)didStyleChangeToRecord:(_Bool)arg1;
@end

