//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UIImageView, UILabel;

@interface DXRecordView : UIView
{
    NSTimer *_timer;
    UIImageView *_recordAnimationView;
    UILabel *_textLabel;
}

- (void).cxx_destruct;
- (void)setVoiceImage;
- (void)recordButtonDragOutside;
- (void)recordButtonDragInside;
- (void)recordButtonTouchUpOutside;
- (void)recordButtonTouchUpInside;
- (void)recordButtonTouchDown;
- (id)initWithFrame:(struct CGRect)arg1;

@end

