//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MessageModel, THProgressView, UIImageView, UITapGestureRecognizer;

@interface EMChatBaseBubbleView : UIView
{
    THProgressView *_progressView;
    MessageModel *_model;
    UIImageView *_backImageView;
    UITapGestureRecognizer *_bubbleViewPressedTap;
}

+ (double)heightForBubbleWithObject:(id)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *bubbleViewPressedTap; // @synthesize bubbleViewPressedTap=_bubbleViewPressedTap;
@property(retain, nonatomic) THProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(retain, nonatomic) MessageModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)progress:(double)arg1;
- (void)bubbleViewPressed:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

