//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMChatImageBubbleView.h"

@class UIButton;

@interface EMChatVideoBubbleView : EMChatImageBubbleView
{
    UIButton *_videoPlayButton;
}

@property(retain, nonatomic) UIButton *videoPlayButton; // @synthesize videoPlayButton=_videoPlayButton;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)playVideoAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

