//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMChatManagerBuddyDelegate.h"
#import "EMChatManagerChatDelegate.h"
#import "EMChatManagerChatroomDelegate.h"
#import "EMChatManagerDebugDelegate.h"
#import "EMChatManagerEncryptionDelegate.h"
#import "EMChatManagerGroupDelegate.h"
#import "EMChatManagerLoginDelegate.h"
#import "EMChatManagerPushNotificationDelegate.h"
#import "EMChatManagerUtilDelegate.h"

@protocol EMChatManagerDelegate <EMChatManagerChatDelegate, EMChatManagerLoginDelegate, EMChatManagerEncryptionDelegate, EMChatManagerBuddyDelegate, EMChatManagerUtilDelegate, EMChatManagerGroupDelegate, EMChatManagerPushNotificationDelegate, EMChatManagerChatroomDelegate, EMChatManagerDebugDelegate>
@end

