//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMChatManagerDelegateBase.h"

@class EMChatroom, NSString;

@protocol EMChatManagerChatroomDelegate <EMChatManagerDelegateBase>

@optional
- (void)didReceiveChatroomInvitationFrom:(NSString *)arg1 inviter:(NSString *)arg2 message:(NSString *)arg3;
- (void)beKickedOutFromChatroom:(EMChatroom *)arg1 reason:(long long)arg2;
- (void)chatroom:(EMChatroom *)arg1 occupantDidLeave:(NSString *)arg2;
- (void)chatroom:(EMChatroom *)arg1 occupantDidJoin:(NSString *)arg2;
@end

