//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EMChatObjectInternal : NSObject
{
    id <IEMMessageBody> messageBody;
}

@property(nonatomic) __weak id <IEMMessageBody> messageBody; // @synthesize messageBody;
- (void).cxx_destruct;
- (_Bool)update;
- (id)description;

@end

