//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMChatObjectInternal.h"

@class NSString;

@interface EMChatTextInternal : EMChatObjectInternal
{
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)description;
- (id)initWithText:(id)arg1;

@end

