//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DXDBManager, EMMessage, NSDictionary, NSString;

@interface EMConversationInternal : NSObject
{
    id <ConversationDelegate> _delegate;
    EMMessage *_latestMessage;
    DXDBManager *_dbman;
    _Bool _enableUnreadMessagesCountEvent;
    NSString *_chatter;
    long long _unreadMessagesCount;
    NSDictionary *_ext;
    long long _conversationType;
}

@property(readonly, nonatomic) long long conversationType; // @synthesize conversationType=_conversationType;
@property(retain, nonatomic) NSDictionary *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) EMMessage *latestMessage; // @synthesize latestMessage=_latestMessage;
@property(nonatomic) long long unreadMessagesCount; // @synthesize unreadMessagesCount=_unreadMessagesCount;
@property(nonatomic) _Bool enableUnreadMessagesCountEvent; // @synthesize enableUnreadMessagesCountEvent=_enableUnreadMessagesCountEvent;
@property(retain, nonatomic) NSString *chatter; // @synthesize chatter=_chatter;
@property(nonatomic) __weak id <ConversationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)latestMessageFromOthers;
- (id)loadMessagesBefore:(long long)arg1 limit:(unsigned long long)arg2 bodyType:(long long)arg3;
- (id)loadMessagesBefore:(long long)arg1 limit:(unsigned long long)arg2;
- (id)loadAllMessagesFromDB;
- (id)loadMessagesWithIds:(id)arg1;
- (id)loadMessageWithId:(id)arg1;
- (unsigned long long)loadUnreadMessagesCount;
- (unsigned long long)removeAllMessages;
- (_Bool)removeMessage:(id)arg1;
- (unsigned long long)removeMessageWithIds:(id)arg1;
- (_Bool)removeMessageWithId:(id)arg1;
- (_Bool)_removeMessage:(id)arg1;
- (_Bool)_removeMessageFiles:(id)arg1;
- (_Bool)_removeMessageBodyFile:(id)arg1;
- (_Bool)insertMessages:(id)arg1 append2Chat:(_Bool)arg2;
- (_Bool)insertMessage:(id)arg1 append2Chat:(_Bool)arg2 sendEvent:(_Bool)arg3;
- (_Bool)insertMessage:(id)arg1 append2Chat:(_Bool)arg2;
- (_Bool)markMessageWithId:(id)arg1 asRead:(_Bool)arg2;
- (_Bool)markAllMessagesAsRead:(_Bool)arg1;
- (_Bool)updateMessageWithId:(id)arg1 deliveredAcked:(_Bool)arg2;
- (_Bool)updateMessageWithId:(id)arg1 readAcked:(_Bool)arg2;
- (void)updateConversationExt:(id)arg1;
- (void)updateUnreadMessagesCountEventToEnable:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isGroup;
- (void)dealloc;
- (id)initWithChatter:(id)arg1 isGroup:(_Bool)arg2;
- (id)initWithChatter:(id)arg1 conversationType:(long long)arg2;

@end

