//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol EMDeviceManagerNetworkDelegate <NSObject>

@optional
- (void)didConnectionChanged:(long long)arg1 fromConnectionType:(long long)arg2;
@end

