//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class EMGCDAsyncSocket, NSData, NSError, NSString;

@protocol EMGCDAsyncSocketDelegate

@optional
- (void)socket:(EMGCDAsyncSocket *)arg1 didReceiveTrust:(struct __SecTrust *)arg2 completionHandler:(void (^)(_Bool))arg3;
- (void)socketDidSecure:(EMGCDAsyncSocket *)arg1;
- (void)socketDidDisconnect:(EMGCDAsyncSocket *)arg1 withError:(NSError *)arg2;
- (void)socketDidCloseReadStream:(EMGCDAsyncSocket *)arg1;
- (double)socket:(EMGCDAsyncSocket *)arg1 shouldTimeoutWriteWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (double)socket:(EMGCDAsyncSocket *)arg1 shouldTimeoutReadWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (void)socket:(EMGCDAsyncSocket *)arg1 didWritePartialDataOfLength:(unsigned long long)arg2 tag:(long long)arg3;
- (void)socket:(EMGCDAsyncSocket *)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socket:(EMGCDAsyncSocket *)arg1 didReadPartialDataOfLength:(unsigned long long)arg2 tag:(long long)arg3;
- (void)socket:(EMGCDAsyncSocket *)arg1 didReadData:(NSData *)arg2 withTag:(long long)arg3;
- (void)socket:(EMGCDAsyncSocket *)arg1 didConnectToHost:(NSString *)arg2 port:(unsigned short)arg3;
- (void)socket:(EMGCDAsyncSocket *)arg1 didAcceptNewSocket:(EMGCDAsyncSocket *)arg2;
- (struct dispatch_queue_s *)newSocketQueueForConnectionFromAddress:(NSData *)arg1 onSocket:(EMGCDAsyncSocket *)arg2;
@end

