//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEMGroup.h"

@class EMGroupInternal, EMGroupStyleSetting, NSArray, NSString;

@interface EMGroup : NSObject <IEMGroup>
{
    EMGroupInternal *_internal;
    NSString *_password;
    NSArray *_admins;
}

+ (id)groupWithId:(id)arg1;
+ (void)cancelAllPendingOperations;
@property(readonly, nonatomic) NSArray *admins; // @synthesize admins=_admins;
@property(readonly, nonatomic) NSString *password; // @synthesize password=_password;
- (void).cxx_destruct;
- (id)occupantWithUsername:(id)arg1;
@property(readonly, nonatomic) NSArray *occupants; // @dynamic occupants;
@property(readonly, nonatomic) NSArray *bans; // @dynamic bans;
@property(readonly, nonatomic) NSArray *members; // @dynamic members;
@property(readonly, nonatomic) NSString *owner; // @dynamic owner;
@property(readonly, nonatomic) _Bool isBlocked; // @dynamic isBlocked;
@property(readonly, nonatomic) _Bool isPushNotificationEnabled; // @dynamic isPushNotificationEnabled;
@property(readonly, nonatomic) EMGroupStyleSetting *groupSetting; // @dynamic groupSetting;
@property(readonly, nonatomic) _Bool isPublic;
@property(readonly, nonatomic) long long groupOnlineOccupantsCount; // @dynamic groupOnlineOccupantsCount;
@property(readonly, nonatomic) long long groupOccupantsCount; // @dynamic groupOccupantsCount;
@property(readonly, nonatomic) NSString *groupSubject; // @dynamic groupSubject;
@property(readonly, nonatomic) NSString *groupDescription; // @dynamic groupDescription;
@property(readonly, nonatomic) NSString *groupId; // @dynamic groupId;
@property(retain, nonatomic) EMGroupInternal *internal; // @dynamic internal;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithGroupId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

