//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface EMGroupOccupantMap : NSObject
{
    NSMutableDictionary *_occupantMap;
}

+ (id)occupantMapWithJSONString:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *occupantMap; // @synthesize occupantMap=_occupantMap;
- (void).cxx_destruct;
- (void)removeAllObjects;
- (id)occupantWithUsername:(id)arg1;
- (void)addOccupantToMap:(id)arg1;
- (id)init;
- (id)toJSONString;

@end

