//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMFileMessageBodyInternal.h"

@class EMChatImage, NSString;

@interface EMImageMessageBodyInternal : EMFileMessageBodyInternal
{
    EMChatImage *_image;
    EMChatImage *_thumbnailImage;
    NSString *_thumbnailRemotePath;
    NSString *_thumbnailSecretKey;
    unsigned long long _thumbnailDownloadStatus;
}

@property(nonatomic) unsigned long long thumbnailDownloadStatus; // @synthesize thumbnailDownloadStatus=_thumbnailDownloadStatus;
@property(readonly, nonatomic) EMChatImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(readonly, nonatomic) EMChatImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *thumbnailSecretKey; // @synthesize thumbnailSecretKey=_thumbnailSecretKey;
@property(retain, nonatomic) NSString *thumbnailRemotePath; // @synthesize thumbnailRemotePath=_thumbnailRemotePath;
- (void).cxx_destruct;
- (long long)messageBodyType;
- (id)generateThumbnailImage:(id)arg1;
- (id)initWithChatObject:(id)arg1;
- (id)initWithImage:(id)arg1 thumbnailImage:(id)arg2;
- (id)description;
@property(nonatomic) struct CGSize size; // @dynamic size;
@property(nonatomic) long long thumbnailFileLength; // @dynamic thumbnailFileLength;
@property(nonatomic) struct CGSize thumbnailSize; // @dynamic thumbnailSize;
@property(retain, nonatomic) NSString *thumbnailLocalPath; // @dynamic thumbnailLocalPath;
@property(retain, nonatomic) NSString *thumbnailDisplayName; // @dynamic thumbnailDisplayName;

@end

