//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EMLogMessage, NSString;

@protocol EMLogger <NSObject>
@property(retain, nonatomic) id <EMLogFormatter> logFormatter;
- (void)logMessage:(EMLogMessage *)arg1;

@optional
@property(readonly, nonatomic) NSString *loggerName;
@property(readonly, nonatomic) struct dispatch_queue_s *loggerQueue;
- (void)flush;
- (void)willRemoveLogger;
- (void)didAddLogger;
@end

