//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EMReachability;

@interface EMNetworkMonitor : NSObject
{
    EMReachability *_reachability;
    EMReachability *_hostReachability;
    long long _currentConnectionType;
    id <EMNetworkMonitorDelegate> networkMonitorDelegate;
}

@property(nonatomic) __weak id <EMNetworkMonitorDelegate> networkMonitorDelegate; // @synthesize networkMonitorDelegate;
- (void).cxx_destruct;
- (void)restartMonitor;
- (void)stopMonitor;
- (void)startMonitor;
- (id)initWithConnectionName:(long long)arg1;
- (id)init;
- (long long)calculateConnectionType;
@property(readonly, nonatomic) long long currentConnectionType; // @dynamic currentConnectionType;
@property(readonly, nonatomic) _Bool isReachableNetwork; // @dynamic isReachableNetwork;
- (id)connectionName2String:(long long)arg1;
- (id)connectionType2String:(long long)arg1;
- (void)updateReachabilityStatus:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)registerNotifications;
- (void)unregisterNotifications;
- (void)dealloc;

@end

