//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IEMFileMessageBody.h"

@class EMMessage, EMVoiceMessageBodyInternal, NSString;

@interface EMVoiceMessageBody : NSObject <IEMFileMessageBody>
{
    EMVoiceMessageBodyInternal *_internal;
}

+ (id)voiceMessageBodyFromBodyDict:(id)arg1 forChatter:(id)arg2;
- (void).cxx_destruct;
- (id)initWithChatObject:(id)arg1;
- (id)init;
@property(nonatomic) unsigned long long attachmentDownloadStatus;
@property(nonatomic) long long duration; // @dynamic duration;
@property(readonly, nonatomic) long long messageBodyType; // @dynamic messageBodyType;
@property(readonly, nonatomic) id <IEMChatObject> chatObject; // @dynamic chatObject;
@property(readonly, copy) NSString *description;
@property(nonatomic) __weak EMMessage *message; // @dynamic message;
@property(nonatomic) long long fileLength; // @dynamic fileLength;
@property(retain, nonatomic) NSString *displayName; // @dynamic displayName;
@property(retain, nonatomic) NSString *uuid; // @dynamic uuid;
@property(retain, nonatomic) NSString *secretKey; // @dynamic secretKey;
@property(retain, nonatomic) NSString *remotePath; // @dynamic remotePath;
@property(retain, nonatomic) NSString *localPath; // @dynamic localPath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

