//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TipsPopViewDelegate.h"

@class NSString, UIButton, UIViewController;

@interface ExportJobData : NSObject <TipsPopViewDelegate>
{
    UIViewController *_hostController;
    UIButton *_actionBtn;
    NSString *_jobID;
    NSString *_jobTitle;
}

@property(copy, nonatomic) NSString *jobTitle; // @synthesize jobTitle=_jobTitle;
@property(copy, nonatomic) NSString *jobID; // @synthesize jobID=_jobID;
@property(retain, nonatomic) UIButton *actionBtn; // @synthesize actionBtn=_actionBtn;
@property(nonatomic) __weak UIViewController *hostController; // @synthesize hostController=_hostController;
- (void).cxx_destruct;
- (void)requestBillExcel;
- (void)requestEmployExcel;
- (void)showActivityView:(id)arg1 path:(id)arg2 title:(id)arg3 targetView:(id)arg4;
- (void)tipsPopView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showExportPopView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

