//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseOverlay.h"

@interface GroundOverlay : BaseOverlay
{
}

- (_Bool)updateGroundData:(id)arg1;
- (_Bool)addGroundData:(id)arg1 isAdd:(_Bool)arg2;
- (_Bool)removeGroundData:(int)arg1;
- (void)dealloc;
- (id)initWithMapView:(id)arg1;

@end

