//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

@class GroupMemberHeadModel, UIImageView, UILabel;

@interface GroupMemberHeadView : BaseView
{
    UIImageView *_headView;
    UILabel *_nameLab;
    GroupMemberHeadModel *_model;
}

@property(retain, nonatomic) GroupMemberHeadModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UIImageView *headView; // @synthesize headView=_headView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

