//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "AJAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ConversationBean, NSArray, NSMutableArray, NSString, UIButton, UITableView;

@interface GroupMemberEditViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate, AJAlertViewDelegate>
{
    unsigned long long _style;
    ConversationBean *_conversationBean;
    NSArray *_dataSource;
    UIButton *_rightBtn;
    UITableView *_tableView;
    NSArray *_firstLetterArray;
    NSMutableArray *_selectIndexPathArray;
}

@property(retain, nonatomic) NSMutableArray *selectIndexPathArray; // @synthesize selectIndexPathArray=_selectIndexPathArray;
@property(retain, nonatomic) NSArray *firstLetterArray; // @synthesize firstLetterArray=_firstLetterArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) ConversationBean *conversationBean; // @synthesize conversationBean=_conversationBean;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)delGroupMemberHandler;
- (void)delGroupMember;
- (void)addGroupMemberHandler;
- (void)addGroupMember;
- (id)userIdsFromSelect;
- (void)getAllMembersHandler:(id)arg1;
- (void)getAllMembers;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)formatData:(id)arg1;
- (void)updateCount;
- (void)updateCell:(id)arg1;
- (void)updateUI;
- (void)addIndex:(id)arg1;
- (void)removeIndex:(id)arg1;
- (_Bool)checkIndex:(id)arg1;
- (void)alertView:(id)arg1 buttonClick:(long long)arg2;
- (void)createPopView_delGroupMember;
- (void)rightHandler:(id)arg1;
- (void)initView;
- (void)initData;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

