//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseCell.h"

@class UIImageView, UILabel;

@interface GroupMemberEditCell : BaseCell
{
    UIImageView *_selectView;
    UIImageView *_headView;
    UILabel *_nameLab;
    unsigned long long _selectStyle;
}

@property(nonatomic) unsigned long long selectStyle; // @synthesize selectStyle=_selectStyle;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UIImageView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) UIImageView *selectView; // @synthesize selectView=_selectView;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

