//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

@class NSMutableArray;

@interface GroupSettingTitleView : BaseView
{
    id <GroupSettingTitleViewDelegate> _delegate;
    NSMutableArray *_modelArray;
    NSMutableArray *_itemArray;
    double _totalHeight;
}

@property(nonatomic) double totalHeight; // @synthesize totalHeight=_totalHeight;
@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
@property(retain, nonatomic) NSMutableArray *modelArray; // @synthesize modelArray=_modelArray;
@property(nonatomic) __weak id <GroupSettingTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setupHeightForTitleView;
- (void)headTapHandler:(id)arg1;
- (void)cleanAllSubViews;
- (void)setupHeadInfo:(id)arg1 countOfRow:(long long)arg2 hasAdd:(_Bool)arg3 hasDelete:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

