//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class BaseTextField, NSString, NSTimer, UIButton, UIColor;

@interface HJCAjustNumButton : UIView <UITextFieldDelegate>
{
    UIButton *_decreaseBtn;
    UIButton *_increaseBtn;
    BaseTextField *_textField;
    UIView *_oneLine;
    UIView *_twoLine;
    NSTimer *_timer;
    id <HJCAjustNumButtonDelegate> _delegate;
    UIColor *_lineColor;
    long long _maxNum;
    long long _minNum;
}

@property(nonatomic) long long minNum; // @synthesize minNum=_minNum;
@property(nonatomic) long long maxNum; // @synthesize maxNum=_maxNum;
@property(nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) __weak id <HJCAjustNumButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)endEditStatus;
- (void)cleanTimer;
- (void)dealloc;
- (id)readImageFromBundle:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)callBack:(id)arg1 correct:(_Bool)arg2;
- (void)numValueChange;
- (void)decrease;
- (void)increase;
- (void)setupButton:(id)arg1 normalImage:(id)arg2 HighlightImage:(id)arg3;
- (void)commonSetup;
- (void)setupViews;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(copy, nonatomic) NSString *currentNum;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

