//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IChatManagerBase.h"

@class EMMessage, NSDictionary, NSString;

@protocol IChatManagerChat <IChatManagerBase>
- (EMMessage *)asyncResendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2 prepare:(void (^)(EMMessage *, EMError *))arg3 onQueue:(struct dispatch_queue_s *)arg4 completion:(void (^)(EMMessage *, EMError *))arg5 onQueue:(struct dispatch_queue_s *)arg6;
- (EMMessage *)asyncResendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2;
- (EMMessage *)resendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2 error:(id *)arg3;
- (void)sendReadAckForMessage:(EMMessage *)arg1;
- (EMMessage *)asyncSendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2 prepare:(void (^)(EMMessage *, EMError *))arg3 onQueue:(struct dispatch_queue_s *)arg4 completion:(void (^)(EMMessage *, EMError *))arg5 onQueue:(struct dispatch_queue_s *)arg6;
- (EMMessage *)asyncSendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2;
- (EMMessage *)sendMessage:(EMMessage *)arg1 progress:(id <IEMChatProgressDelegate>)arg2 error:(id *)arg3;

@optional
- (EMMessage *)asyncForwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 messageType:(long long)arg4 progress:(id <IEMChatProgressDelegate>)arg5 prepare:(void (^)(EMMessage *, EMError *))arg6 onQueue:(struct dispatch_queue_s *)arg7 completion:(void (^)(EMMessage *, EMError *))arg8 onQueue:(struct dispatch_queue_s *)arg9;
- (EMMessage *)asyncForwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 messageType:(long long)arg4 progress:(id <IEMChatProgressDelegate>)arg5;
- (EMMessage *)forwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 messageType:(long long)arg4 progress:(id <IEMChatProgressDelegate>)arg5 error:(id *)arg6;
- (EMMessage *)asyncForwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 isGroup:(_Bool)arg4 progress:(id <IEMChatProgressDelegate>)arg5 prepare:(void (^)(EMMessage *, EMError *))arg6 onQueue:(struct dispatch_queue_s *)arg7 completion:(void (^)(EMMessage *, EMError *))arg8 onQueue:(struct dispatch_queue_s *)arg9;
- (EMMessage *)asyncForwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 isGroup:(_Bool)arg4 progress:(id <IEMChatProgressDelegate>)arg5;
- (EMMessage *)forwardMessage:(EMMessage *)arg1 ext:(NSDictionary *)arg2 to:(NSString *)arg3 isGroup:(_Bool)arg4 progress:(id <IEMChatProgressDelegate>)arg5 error:(id *)arg6;
- (void)sendHasReadResponseForMessage:(EMMessage *)arg1;
@end

