//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IChatManagerBase.h"

@class EMError, NSArray, NSString;

@protocol IChatManagerBuddy <IChatManagerBase>
@property(readonly, nonatomic) NSArray *blockedList;
@property(readonly, nonatomic) NSArray *buddyList;
- (void)asyncUnblockBuddy:(NSString *)arg1 withCompletion:(void (^)(NSString *, EMError *))arg2 onQueue:(struct dispatch_queue_s *)arg3;
- (void)asyncUnblockBuddy:(NSString *)arg1;
- (EMError *)unblockBuddy:(NSString *)arg1;
- (void)asyncBlockBuddy:(NSString *)arg1 relationship:(long long)arg2 withCompletion:(void (^)(NSString *, EMError *))arg3 onQueue:(struct dispatch_queue_s *)arg4;
- (void)asyncBlockBuddy:(NSString *)arg1 relationship:(long long)arg2;
- (EMError *)blockBuddy:(NSString *)arg1 relationship:(long long)arg2;
- (void)asyncFetchBlockedListWithCompletion:(void (^)(NSArray *, EMError *))arg1 onQueue:(struct dispatch_queue_s *)arg2;
- (void)asyncFetchBlockedList;
- (NSArray *)fetchBlockedList:(id *)arg1;
- (_Bool)rejectBuddyRequest:(NSString *)arg1 reason:(NSString *)arg2 error:(id *)arg3;
- (_Bool)acceptBuddyRequest:(NSString *)arg1 error:(id *)arg2;
- (_Bool)removeBuddy:(NSString *)arg1 removeFromRemote:(_Bool)arg2 error:(id *)arg3;
- (_Bool)addBuddy:(NSString *)arg1 message:(NSString *)arg2 toGroups:(NSArray *)arg3 error:(id *)arg4;
- (_Bool)addBuddy:(NSString *)arg1 message:(NSString *)arg2 error:(id *)arg3;
- (void *)asyncFetchBuddyListWithCompletion:(void (^)(NSArray *, EMError *))arg1 onQueue:(struct dispatch_queue_s *)arg2;
- (void *)asyncFetchBuddyList;
- (NSArray *)fetchBuddyListWithError:(id *)arg1;

@optional
@property(readonly, nonatomic) NSArray *buddyGroupList;
- (void)asyncFetchBlockListWithCompletion:(void (^)(NSArray *, EMError *))arg1 onQueue:(struct dispatch_queue_s *)arg2;
- (_Bool)addBuddy:(NSString *)arg1 withNickname:(NSString *)arg2 message:(NSString *)arg3 toGroups:(NSArray *)arg4 error:(id *)arg5;
- (_Bool)addBuddy:(NSString *)arg1 withNickname:(NSString *)arg2 message:(NSString *)arg3 error:(id *)arg4;
@end

