//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IEMChatObject.h"

@class NSData, NSString;

@protocol IEMChatFile <IEMChatObject>
@property(nonatomic) long long fileLength;
@property(retain, nonatomic) NSString *localPath;
@property(retain, nonatomic) NSString *displayName;
- (id)initWithFile:(NSString *)arg1 displayName:(NSString *)arg2;
- (id)initWithData:(NSData *)arg1 displayName:(NSString *)arg2;
@end

