//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableSet, NSNotification, NSString, UIColor, UIFont, UIScrollView, UITapGestureRecognizer, UIView, UIViewController;

@interface IQKeyboardManager : NSObject <UIGestureRecognizerDelegate>
{
    UIView *_textFieldView;
    struct CGRect _textFieldViewIntialFrame;
    struct CGRect _topViewBeginRect;
    UIViewController *_rootViewController;
    double _layoutGuideConstraintInitialConstant;
    UIScrollView *_lastScrollView;
    struct UIEdgeInsets _startingContentInsets;
    struct UIEdgeInsets _startingScrollIndicatorInsets;
    struct CGPoint _startingContentOffset;
    NSNotification *_kbShowNotification;
    struct CGSize _kbSize;
    double _animationDuration;
    long long _animationCurve;
    UITapGestureRecognizer *_tapGesture;
    UIColor *_defaultToolbarTintColor;
    NSMutableSet *_disabledClasses;
    NSMutableSet *_disabledToolbarClasses;
    NSMutableSet *_toolbarPreviousNextConsideredClass;
    struct {
        unsigned int isTextFieldViewFrameChanged:1;
        unsigned int isKeyboardShowing:1;
    } _keyboardManagerFlags;
    _Bool _enable;
    _Bool _preventShowingBottomBlankSpace;
    _Bool _overrideKeyboardAppearance;
    _Bool _enableAutoToolbar;
    _Bool _shouldToolbarUsesTextFieldTintColor;
    _Bool _shouldShowTextFieldPlaceholder;
    _Bool _canAdjustTextView;
    _Bool _shouldFixTextViewClip;
    _Bool _shouldResignOnTouchOutside;
    _Bool _shouldPlayInputClicks;
    _Bool _shouldAdoptDefaultKeyboardAnimation;
    _Bool _layoutIfNeededOnUpdate;
    _Bool _shouldRestoreScrollViewContentOffset;
    double _keyboardDistanceFromTextField;
    long long _keyboardAppearance;
    long long _toolbarManageBehaviour;
    UIFont *_placeholderFont;
}

+ (id)sharedManager;
+ (void)load;
@property(nonatomic) _Bool shouldRestoreScrollViewContentOffset; // @synthesize shouldRestoreScrollViewContentOffset=_shouldRestoreScrollViewContentOffset;
@property(nonatomic) _Bool layoutIfNeededOnUpdate; // @synthesize layoutIfNeededOnUpdate=_layoutIfNeededOnUpdate;
@property(nonatomic) _Bool shouldAdoptDefaultKeyboardAnimation; // @synthesize shouldAdoptDefaultKeyboardAnimation=_shouldAdoptDefaultKeyboardAnimation;
@property(nonatomic) _Bool shouldPlayInputClicks; // @synthesize shouldPlayInputClicks=_shouldPlayInputClicks;
@property(nonatomic) _Bool shouldResignOnTouchOutside; // @synthesize shouldResignOnTouchOutside=_shouldResignOnTouchOutside;
@property(nonatomic) _Bool shouldFixTextViewClip; // @synthesize shouldFixTextViewClip=_shouldFixTextViewClip;
@property(nonatomic) _Bool canAdjustTextView; // @synthesize canAdjustTextView=_canAdjustTextView;
@property(retain, nonatomic) UIFont *placeholderFont; // @synthesize placeholderFont=_placeholderFont;
@property(nonatomic) _Bool shouldShowTextFieldPlaceholder; // @synthesize shouldShowTextFieldPlaceholder=_shouldShowTextFieldPlaceholder;
@property(nonatomic) _Bool shouldToolbarUsesTextFieldTintColor; // @synthesize shouldToolbarUsesTextFieldTintColor=_shouldToolbarUsesTextFieldTintColor;
@property(nonatomic) long long toolbarManageBehaviour; // @synthesize toolbarManageBehaviour=_toolbarManageBehaviour;
@property(nonatomic, getter=isEnableAutoToolbar) _Bool enableAutoToolbar; // @synthesize enableAutoToolbar=_enableAutoToolbar;
@property(nonatomic) long long keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(nonatomic) _Bool overrideKeyboardAppearance; // @synthesize overrideKeyboardAppearance=_overrideKeyboardAppearance;
@property(nonatomic) _Bool preventShowingBottomBlankSpace; // @synthesize preventShowingBottomBlankSpace=_preventShowingBottomBlankSpace;
@property(nonatomic) double keyboardDistanceFromTextField; // @synthesize keyboardDistanceFromTextField=_keyboardDistanceFromTextField;
@property(nonatomic, getter=isEnabled) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (_Bool)isConsiderToolbarPreviousNextInViewClass:(Class)arg1;
- (void)removeConsiderToolbarPreviousNextInViewClass:(Class)arg1;
- (void)considerToolbarPreviousNextInViewClass:(Class)arg1;
- (_Bool)isDisableToolbarInViewControllerClass:(Class)arg1;
- (void)removeDisableToolbarInViewControllerClass:(Class)arg1;
- (void)disableToolbarInViewControllerClass:(Class)arg1;
- (_Bool)isDisableInViewControllerClass:(Class)arg1;
- (void)removeDisableInViewControllerClass:(Class)arg1;
- (void)disableInViewControllerClass:(Class)arg1;
- (void)doneAction:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)previousAction:(id)arg1;
- (void)removeToolbarIfRequired;
- (void)addToolbarIfRequired;
- (id)responderViews;
- (_Bool)goNext;
- (_Bool)goPrevious;
@property(readonly, nonatomic) _Bool canGoNext;
@property(readonly, nonatomic) _Bool canGoPrevious;
- (_Bool)resignFirstResponder;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)tapRecognized:(id)arg1;
- (void)willChangeStatusBarOrientation:(id)arg1;
- (void)textFieldViewDidChange:(id)arg1;
- (void)textFieldViewDidEndEditing:(id)arg1;
- (void)textFieldViewDidBeginEditing:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)adjustFrame;
- (void)setRootViewFrame:(struct CGRect)arg1;
- (id)keyWindow;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

