//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IQBarButtonItem.h"

@class UIFont, UILabel, UIView;

@interface IQTitleBarButtonItem : IQBarButtonItem
{
    UIView *_titleView;
    UILabel *_titleLabel;
    UIFont *_font;
}

@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;

@end

