//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ITTCalDay, NSMutableArray;

@interface ITTCalMonth : NSObject
{
    unsigned long long _month;
    unsigned long long _year;
    unsigned long long _numberOfDays;
    ITTCalDay *_today;
    NSMutableArray *daysOfMonth;
    unsigned long long days;
}

- (void).cxx_destruct;
- (id)lastDay;
- (id)firstDay;
- (id)calDayAtDay:(unsigned long long)arg1;
- (unsigned long long)getMonth;
- (unsigned long long)getYear;
@property(readonly, nonatomic) unsigned long long days; // @synthesize days;
- (id)description;
- (id)initWithMonth:(unsigned long long)arg1 year:(unsigned long long)arg2 day:(unsigned long long)arg3;
- (id)initWithDate:(id)arg1;
- (id)initWithMonth:(unsigned long long)arg1 year:(unsigned long long)arg2;
- (id)initWithMonth:(unsigned long long)arg1;
- (id)previousMonth;
- (id)nextMonth;
- (void)caculateMonth;

@end

