//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ITTCalendarGridViewDelegate.h"
#import "ITTCalendarScrollViewDelegate.h"
#import "ITTCalendarViewFooterViewDelegate.h"
#import "ITTCalendarViewHeaderViewDelegate.h"

@class ITTCalDay, ITTCalMonth, ITTCalendarScrollView, ITTCalendarViewFooterView, ITTCalendarViewHeaderView, NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface ITTCalendarView : UIView <ITTCalendarGridViewDelegate, ITTCalendarViewHeaderViewDelegate, ITTCalendarViewFooterViewDelegate, ITTCalendarScrollViewDelegate>
{
    _Bool _moved;
    _Bool _firstLayout;
    _Bool _allowsMultipleSelection;
    int _selectedPeriod;
    CDStruct_ecc15559 _previousSelectedIndex;
    struct CGSize _gridSize;
    NSDate *_date;
    NSDate *_minimumDate;
    NSDate *_maximumDate;
    ITTCalDay *_minimumDay;
    ITTCalDay *_maximumDay;
    ITTCalDay *_selectedDay;
    ITTCalMonth *_calMonth;
    ITTCalendarViewHeaderView *_calendarHeaderView;
    ITTCalendarViewFooterView *_calendarFooterView;
    UIView *_parentView;
    NSMutableArray *_gridViewsArray;
    NSMutableArray *_monthGridViewsArray;
    NSMutableDictionary *_recyledGridSetDic;
    NSMutableDictionary *_selectedGridViewIndicesDic;
    NSMutableDictionary *_selectedDayDic;
    id <ITTCalendarViewDataSource> _dataSource;
    id <ITTCalendarViewDelegate> _delegate;
    double _swipeTimeInterval;
    double _begintimeInterval;
    _Bool appear;
    _Bool _isAllowSelect;
    NSArray *selectedDateArray;
    NSDate *selectedDate;
    UIView *_weekHintView;
    UIView *_headerView;
    UIView *_footerView;
    ITTCalendarScrollView *_gridScrollView;
    long long _showMode;
    NSMutableDictionary *_customDateDic;
    struct CGSize gridSize;
}

+ (id)viewFromNib;
@property(retain, nonatomic) NSMutableDictionary *customDateDic; // @synthesize customDateDic=_customDateDic;
@property(nonatomic) long long showMode; // @synthesize showMode=_showMode;
@property(nonatomic) _Bool isAllowSelect; // @synthesize isAllowSelect=_isAllowSelect;
@property(retain, nonatomic) NSMutableDictionary *selectedDayDic; // @synthesize selectedDayDic=_selectedDayDic;
@property(nonatomic) struct CGSize gridSize; // @synthesize gridSize;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(retain, nonatomic) ITTCalendarScrollView *gridScrollView; // @synthesize gridScrollView=_gridScrollView;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) id <ITTCalendarViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) id <ITTCalendarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDate *maximumDate; // @synthesize maximumDate=_maximumDate;
@property(retain, nonatomic) NSDate *minimumDate; // @synthesize minimumDate=_minimumDate;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, retain, nonatomic) ITTCalDay *selectedDay; // @synthesize selectedDay=_selectedDay;
@property(retain, nonatomic) UIView *weekHintView; // @synthesize weekHintView=_weekHintView;
@property(retain, nonatomic) ITTCalMonth *calMonth; // @synthesize calMonth=_calMonth;
@property(nonatomic) int selectedPeriod; // @synthesize selectedPeriod=_selectedPeriod;
@property(nonatomic) _Bool appear; // @synthesize appear;
- (void).cxx_destruct;
- (void)calendarSrollViewTouchesEnded:(id)arg1 touches:(id)arg2 withEvent:(id)arg3;
- (void)calendarSrollViewTouchesCancelled:(id)arg1 touches:(id)arg2 withEvent:(id)arg3;
- (void)calendarSrollViewTouchesMoved:(id)arg1 touches:(id)arg2 withEvent:(id)arg3;
- (void)calendarSrollViewTouchesBegan:(id)arg1 touches:(id)arg2 withEvent:(id)arg3;
- (void)show;
- (void)ittCalendarGridViewDidSelectGrid:(id)arg1;
- (void)calendarViewFooterViewDidSelectPeriod:(id)arg1 periodType:(int)arg2;
- (void)calendarViewHeaderViewDidSelection:(id)arg1;
- (void)calendarViewHeaderViewDidCancel:(id)arg1;
- (void)calendarViewHeaderViewPreviousMonth:(id)arg1;
- (void)calendarViewHeaderViewNextMonth:(id)arg1;
- (void)previousMonth;
- (void)nextMonth;
- (void)showInView:(id)arg1;
- (void)hide;
@property(readonly, retain, nonatomic) NSArray *selectedDateArray; // @synthesize selectedDateArray;
@property(readonly, retain, nonatomic) NSDate *selectedDate; // @synthesize selectedDate;
- (id)dequeueCalendarGridViewWithIdentifier:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (void)swipe:(id)arg1;
- (void)layoutSubviews;
- (void)animationChangeMonth:(_Bool)arg1;
- (id)disableGridViewAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2 calDay:(id)arg3;
- (id)gridViewAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2 calDay:(id)arg3;
- (id)findFooterview;
- (id)findHeaderView;
- (struct CGRect)getFrameForRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (void)layoutGridCells;
- (void)addGridViewAtRow:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3;
- (void)removeGridViewAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (_Bool)isAfterMaximumDay:(id)arg1;
- (_Bool)isEarlyerMinimumDay:(id)arg1;
- (void)updateSelectedGridViewState;
- (_Bool)isCustomSelectedDay:(id)arg1;
- (_Bool)isHistorySelectedDay:(id)arg1;
- (id)getSelectedDayKey:(id)arg1;
- (id)getSelectedDayKey:(long long)arg1 column:(long long)arg2;
- (void)resetFoucsMatrix;
- (void)resetSelectedIndicesMatrix;
- (_Bool)isGridViewSelectedEnableAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (_Bool)isSelectedAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (void)setSelectedAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2 selected:(_Bool)arg3;
- (id)getGridViewAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (void)recyleAllGridViews;
- (id)findWeekTitles;
- (id)findMonthDescription;
- (CDStruct_ecc15559)getGridViewIndex:(id)arg1 touches:(id)arg2;
- (_Bool)isValidGridViewIndex:(CDStruct_ecc15559)arg1;
- (unsigned long long)getMonthDayAtRow:(unsigned long long)arg1 column:(unsigned long long)arg2;
- (unsigned long long)getRows;
- (void)initParameters;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

