//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JobAndResumeManagerBaseViewController.h"

@class JobManagerCleanBarView, JobPrepayInfoBean, UIImageView, UILabel;

@interface JobAndResumeManagerUndercarriageViewController : JobAndResumeManagerBaseViewController
{
    JobManagerCleanBarView *_barView;
    JobPrepayInfoBean *_jobPrepayInfo;
    UIImageView *_typeIconImageView;
    UILabel *_titleLabel;
    UILabel *_areaLabel;
    UILabel *_timeLabel;
    UILabel *_reasonLabel;
}

@property(nonatomic) __weak UILabel *reasonLabel; // @synthesize reasonLabel=_reasonLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *areaLabel; // @synthesize areaLabel=_areaLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *typeIconImageView; // @synthesize typeIconImageView=_typeIconImageView;
- (void).cxx_destruct;
- (void)requestGetJobPrePayInfo;
- (void)getUndercarriageReason;
- (void)cleanBarHandler:(id)arg1;
- (void)updateUndercarriageReason:(id)arg1;
- (void)getJobPrePayInfo;
- (void)showCleanBarView:(_Bool)arg1;
- (void)updateCleanBar;
- (void)reloadListData;
- (void)initView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPartimeJob:(id)arg1;

@end

