//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSArray;

@interface JobDateObj : ObjectBeanBase
{
    long long _job_date_type;
    NSArray *_job_date_list;
}

@property(retain, nonatomic) NSArray *job_date_list; // @synthesize job_date_list=_job_date_list;
@property(nonatomic) long long job_date_type; // @synthesize job_date_type=_job_date_type;
- (void).cxx_destruct;

@end

