//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

@class NSArray, UIButton, UILabel, UISegmentedControl;

@interface JobManagerSignupConditionView : BaseView
{
    UILabel *_selectCountLab;
    UIButton *_selectBtn;
    UISegmentedControl *_segmentCtrl;
    id <JobManagerSignupConditionViewDelegate> _delegate;
    NSArray *_titleArray;
}

@property(retain, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
@property(nonatomic) __weak id <JobManagerSignupConditionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UISegmentedControl *segmentCtrl; // @synthesize segmentCtrl=_segmentCtrl;
@property(retain, nonatomic) UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(retain, nonatomic) UILabel *selectCountLab; // @synthesize selectCountLab=_selectCountLab;
- (void).cxx_destruct;
- (void)setSelectStatus:(_Bool)arg1;
- (void)segmentCtrlHandler:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

