//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseBarView.h"

@class UIButton, UILabel;

@interface JobPayBarView : BaseBarView
{
    UILabel *_totalPriceLab;
    UILabel *_prePriceLab;
    UILabel *_needPriceLab;
    UIButton *_sureBtn;
}

@property(retain, nonatomic) UIButton *sureBtn; // @synthesize sureBtn=_sureBtn;
@property(retain, nonatomic) UILabel *needPriceLab; // @synthesize needPriceLab=_needPriceLab;
@property(retain, nonatomic) UILabel *prePriceLab; // @synthesize prePriceLab=_prePriceLab;
@property(retain, nonatomic) UILabel *totalPriceLab; // @synthesize totalPriceLab=_totalPriceLab;
- (void).cxx_destruct;
- (void)setJobPayBarType:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

