//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UILabel;

@interface JobPayTitleView : UIImageView
{
    UIImageView *_iconView;
    UIImageView *_statusView;
    UILabel *_titleLab;
    UIImageView *_timeIconView;
    UILabel *_timeLab;
    UIImageView *_arrawView;
    UIImageView *_bottomLine;
}

@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIImageView *arrawView; // @synthesize arrawView=_arrawView;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UIImageView *timeIconView; // @synthesize timeIconView=_timeIconView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

