//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "PaySelectDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class JobPaySelectedPeopleTitleView, NSMutableArray, NSString, PartimeJobBean, UIButton, UITableView;

@interface JobPaySelectedPeopleViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate, PaySelectDelegate>
{
    JobPaySelectedPeopleTitleView *_jobPaySelectedPeopleTitleView;
    UITableView *_tableView;
    UIButton *_rightBtn;
    PartimeJobBean *_jobBean;
    NSMutableArray *_dataSource;
}

@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) PartimeJobBean *jobBean; // @synthesize jobBean=_jobBean;
- (void).cxx_destruct;
- (void)toPaySelectVCWithDatasource:(id)arg1;
- (void)filterPeopleHasSelected:(id)arg1;
- (void)requestNoPayList;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)payDidSelect:(id)arg1;
- (void)deleteBtnHandler:(id)arg1;
- (void)rightHandler:(id)arg1;
- (void)updateTitleUI;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

