//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseBarView.h"

@class UIButton;

@interface JobPendingBarView : BaseBarView
{
    UIButton *_canclePublishBtn;
}

@property(retain, nonatomic) UIButton *canclePublishBtn; // @synthesize canclePublishBtn=_canclePublishBtn;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

