//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "ReleaseJobAlertViewDelegate.h"
#import "TagTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSString, ReleaseJobAlertView, ReleaseJobTypeBean, UITableView;

@interface JobTypeSelectedForHostJobViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate, TagTableViewCellDelegate, ReleaseJobAlertViewDelegate>
{
    id <JobTypeSelectViewControllerDelegate> _delegate;
    NSString *_provinceStr;
    NSString *_cityStr;
    NSString *_areaStr;
    UITableView *_tableView;
    NSMutableArray *_typeArray;
    ReleaseJobAlertView *_alertView;
    NSArray *_standardJobTypeArray;
    ReleaseJobTypeBean *_selectedJobTypeBean;
}

@property(retain, nonatomic) ReleaseJobTypeBean *selectedJobTypeBean; // @synthesize selectedJobTypeBean=_selectedJobTypeBean;
@property(retain, nonatomic) NSArray *standardJobTypeArray; // @synthesize standardJobTypeArray=_standardJobTypeArray;
@property(retain, nonatomic) ReleaseJobAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) NSMutableArray *typeArray; // @synthesize typeArray=_typeArray;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *areaStr; // @synthesize areaStr=_areaStr;
@property(copy, nonatomic) NSString *cityStr; // @synthesize cityStr=_cityStr;
@property(copy, nonatomic) NSString *provinceStr; // @synthesize provinceStr=_provinceStr;
@property(nonatomic) __weak id <JobTypeSelectViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)readNewJobType;
- (void)checkUserFrozen;
- (void)readJobTypes;
- (void)checkQuickPayJobPermission;
- (void)releaseJobAlertView:(id)arg1 didSelectedJobType:(long long)arg2;
- (void)tagTableViewCell:(id)arg1 didSelectItem:(id)arg2 selectedRow:(long long)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)standardJobTypeWithJobTypeName:(id)arg1;
- (void)changeDataBean:(id)arg1:(id)arg2;
- (void)releaseQuickPayJob;
- (void)initView;
- (void)initData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

