//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JPFLocalNotificationManager : NSObject
{
}

+ (void)p_deleteCacheObjectWithKey:(id)arg1 UsingBlock:(CDUnknownBlockType)arg2;
+ (void)clearAllLocalNotifications;
+ (void)deleteLocalNotification:(id)arg1;
+ (void)deleteLocalNotificationWithIdentifierKey:(id)arg1;
+ (id)findLocalNotificationWithIdentifier:(id)arg1;
+ (void)showLocalNotificationAtFront:(id)arg1 identifierKey:(id)arg2;
+ (void)addNotificationToCacheWithNotification:(id)arg1 andKey:(id)arg2;
+ (id)setLocalNotification:(id)arg1 alertBody:(id)arg2 badge:(int)arg3 alertAction:(id)arg4 identifierKey:(id)arg5 userInfo:(id)arg6 soundName:(id)arg7 region:(id)arg8 regionTriggersOnce:(_Bool)arg9 category:(id)arg10;

@end

