//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JPFReportRequest.h"

@interface JPFLocationReportRequest : JPFReportRequest
{
}

- (void)setResponseBlock;
- (void)p_checkLocationInfoChanged:(id)arg1;
- (_Bool)packData;
- (id)init;

@end

