//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JPFNetElement : NSObject
{
    unsigned char _version;
    unsigned char _protocolType;
    unsigned short _rid;
}

@property(nonatomic) unsigned short rid; // @synthesize rid=_rid;
@property(nonatomic) unsigned char protocolType; // @synthesize protocolType=_protocolType;
@property(nonatomic) unsigned char version; // @synthesize version=_version;

@end

