//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JPFPushConfig : NSObject
{
    int _configApsEnvironment;
    NSString *_applicationKey;
    NSString *_pushChanel;
}

@property(readonly, nonatomic) int configApsEnvironment; // @synthesize configApsEnvironment=_configApsEnvironment;
@property(readonly, nonatomic) NSString *pushChanel; // @synthesize pushChanel=_pushChanel;
@property(readonly, nonatomic) NSString *applicationKey; // @synthesize applicationKey=_applicationKey;
- (void).cxx_destruct;
- (_Bool)isValidAppKey:(id)arg1;
- (id)lowerCase:(id)arg1;
- (_Bool)loadWithUrl:(id)arg1;

@end

