//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSInvocation, NSSet, NSString, NSTimer;

@interface JPFSetTagAliasArg : NSObject <NSCopying>
{
    unsigned short _sequence;
    NSSet *_tags;
    NSString *_alias;
    NSInvocation *_cbInvocation;
    id _target;
    NSTimer *_timeoutTimer;
}

@property(nonatomic) __weak NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(nonatomic) unsigned short sequence; // @synthesize sequence=_sequence;
@property(retain, nonatomic) id target; // @synthesize target=_target;
@property(retain, nonatomic) NSInvocation *cbInvocation; // @synthesize cbInvocation=_cbInvocation;
@property(retain, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(retain, nonatomic) NSSet *tags; // @synthesize tags=_tags;
- (void).cxx_destruct;
- (void)onTimeout:(id)arg1;
- (void)stopTimeoutTimer;
- (void)beginTimeoutTimer;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

