//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<JPFTcpSocketDelegate>, NSString;

@interface JPFTcpSocket : NSObject
{
    struct __CFSocket *_socket;
    struct __CFRunLoopSource *_rls;
    unsigned long long _ulReceivedLen;
    char *_receivingBuffer;
    char *_receivingBufferLength;
    unsigned long long _ulDefaultReceiveBufferSize;
    unsigned long long _ulSendingDataSentLen;
    NSMutableArray *_sendQueue;
    unsigned short _expectedBufferLen;
    unsigned short _packageSize;
    _Bool _isSetuped;
    _Bool _careAllDataSent;
    unsigned short _port;
    int _connectionState;
    NSObject<JPFTcpSocketDelegate> *_delegate;
    NSString *_host;
}

@property(nonatomic) _Bool careAllDataSent; // @synthesize careAllDataSent=_careAllDataSent;
@property(readonly, nonatomic) int connectionState; // @synthesize connectionState=_connectionState;
@property(readonly, nonatomic) unsigned short port; // @synthesize port=_port;
@property(readonly, copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(nonatomic) __weak NSObject<JPFTcpSocketDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)doCheck;
- (void)delayedDidSendData:(id)arg1;
- (void)delayedDidReceiveElement:(id)arg1;
- (_Bool)sendData:(id)arg1;
- (void)reenableSocketCallbacks;
- (void)resetReadInfo;
- (void)doSend;
- (void)doRead;
- (void)onConnectedWithErrorCode:(struct __CFData *)arg1;
- (id)remoteAddress;
- (id)localAddress;
- (_Bool)isConnected;
- (void)doCFSocketCallback:(unsigned long long)arg1 forSocket:(struct __CFSocket *)arg2 withData:(struct __CFData *)arg3;
- (void)close;
- (void)p_cleanSocket;
- (_Bool)setup;
- (void)dealloc;
- (id)initWithHost:(id)arg1 port:(unsigned int)arg2 delegate:(id)arg3;

@end

