//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class UIColor;

@interface JWBarButtonItem : UIBarButtonItem
{
    _Bool _showBadge;
    UIColor *_showColor;
}

@property(retain, nonatomic) UIColor *showColor; // @synthesize showColor=_showColor;
@property(nonatomic) _Bool showBadge; // @synthesize showBadge=_showBadge;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;

@end

