//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface JWDeviceService : NSObject
{
    NSArray *_ignoreKeys;
}

+ (id)sys_info_sign;
+ (id)sys_info;
+ (id)instance;
@property(retain, nonatomic) NSArray *ignoreKeys; // @synthesize ignoreKeys=_ignoreKeys;
- (void).cxx_destruct;
- (id)removeIgnoreKeys:(id)arg1;
- (id)init;

@end

