//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JWEnvironmentBase, NSDictionary;

@interface JWEnvironmentConfig : NSObject
{
    unsigned long long _environment_status;
    JWEnvironmentBase *_current_environment;
    JWEnvironmentBase *_environmentDebug;
    JWEnvironmentBase *_environmentFakeData;
    JWEnvironmentBase *_environmentCSB;
    JWEnvironmentBase *_environmentYYC;
    JWEnvironmentBase *_environmentTest;
    JWEnvironmentBase *_environmentBeta;
    JWEnvironmentBase *_environmentSimulation;
    JWEnvironmentBase *_environmentPro;
    JWEnvironmentBase *_environmentCustom;
    NSDictionary *_environmentDic;
}

+ (id)shareInstance;
@property(readonly, nonatomic) NSDictionary *environmentDic; // @synthesize environmentDic=_environmentDic;
@property(retain, nonatomic) JWEnvironmentBase *environmentCustom; // @synthesize environmentCustom=_environmentCustom;
@property(retain, nonatomic) JWEnvironmentBase *environmentPro; // @synthesize environmentPro=_environmentPro;
@property(retain, nonatomic) JWEnvironmentBase *environmentSimulation; // @synthesize environmentSimulation=_environmentSimulation;
@property(retain, nonatomic) JWEnvironmentBase *environmentBeta; // @synthesize environmentBeta=_environmentBeta;
@property(retain, nonatomic) JWEnvironmentBase *environmentTest; // @synthesize environmentTest=_environmentTest;
@property(retain, nonatomic) JWEnvironmentBase *environmentYYC; // @synthesize environmentYYC=_environmentYYC;
@property(retain, nonatomic) JWEnvironmentBase *environmentCSB; // @synthesize environmentCSB=_environmentCSB;
@property(retain, nonatomic) JWEnvironmentBase *environmentFakeData; // @synthesize environmentFakeData=_environmentFakeData;
@property(retain, nonatomic) JWEnvironmentBase *environmentDebug; // @synthesize environmentDebug=_environmentDebug;
@property(retain, nonatomic) JWEnvironmentBase *current_environment; // @synthesize current_environment=_current_environment;
@property(readonly, nonatomic) unsigned long long environment_status; // @synthesize environment_status=_environment_status;
- (void).cxx_destruct;
- (_Bool)canAppShieldManager;
- (_Bool)canStaticsticsManager;
- (_Bool)canDebugManager;
- (_Bool)canLog;
- (_Bool)canAnalyticsManager;
- (void)configEnvironmentCommon;
- (void)setupEnvironment:(unsigned long long)arg1;
@property(readonly, nonatomic) JWEnvironmentBase *environment;
@property(readonly, nonatomic) NSDictionary *environmentDictionary;
- (void)configEnvironmentList;
- (id)init;

@end

