//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSMutableDictionary;

@interface KeyboardNumberButtons : UIButton
{
    NSMutableDictionary *buttons;
}

@property(retain, nonatomic) NSMutableDictionary *buttons; // @synthesize buttons;
- (void).cxx_destruct;
- (void)creatButtons;
- (id)init;

@end

