//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePopView.h"

@class UIButton, UIImageView, UILabel;

@interface LeaderPopView : BasePopView
{
    _Bool _isAnimating;
    long long _type;
    UIImageView *_ropeView;
    UIImageView *_contentView;
    UIImageView *_iconView;
    UILabel *_titleLab;
    UILabel *_contentLab;
    UIButton *_confirmBtn;
    UIButton *_cancleBtn;
}

+ (id)sharedInstance;
@property(retain, nonatomic) UIButton *cancleBtn; // @synthesize cancleBtn=_cancleBtn;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImageView *ropeView; // @synthesize ropeView=_ropeView;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
- (void).cxx_destruct;
- (void)didEnterBackground;
- (void)didBecomeActive;
- (void)addDecayPositionAnimationWithVelocity:(struct CGPoint)arg1;
- (void)tapHandler:(id)arg1;
- (void)onHide:(_Bool)arg1;
- (void)onHide:(_Bool)arg1 off:(_Bool)arg2;
- (void)dismiss;
- (void)onShow:(_Bool)arg1;
- (id)lastWindow;
- (void)actionHandler:(id)arg1;
- (void)updateWithType:(long long)arg1 title:(id)arg2 content:(id)arg3 confirm:(id)arg4 cancle:(id)arg5 delegate:(id)arg6 tag:(long long)arg7;
- (void)configAlertWithType:(long long)arg1 title:(id)arg2 content:(id)arg3 confirm:(id)arg4 cancle:(id)arg5 delegate:(id)arg6 tag:(long long)arg7;
- (void)initView;

@end

