//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PagedRequestManager, UITableView;

@interface LeaderAllOrdersViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tblOrder;
    PagedRequestManager *_pageManager;
    NSArray *_latestOrders;
}

@property(retain, nonatomic) NSArray *latestOrders; // @synthesize latestOrders=_latestOrders;
@property(retain, nonatomic) PagedRequestManager *pageManager; // @synthesize pageManager=_pageManager;
@property(nonatomic) __weak UITableView *tblOrder; // @synthesize tblOrder=_tblOrder;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)jobItemClick:(long long)arg1;
- (void)getHistoryOrdersWithLoadMode:(long long)arg1;
- (void)getLatestOrders;
- (void)mj_loadMoreData;
- (void)mj_refreshData;
- (void)viewDidLoad;
- (void)initData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

