//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class KRLCollectionViewGridLayout, NSArray, NSString, UICollectionView;

@interface LeaderFunctionCell : UITableViewCell <UICollectionViewDataSource, UICollectionViewDelegate>
{
    id <LeaderFunctionCellDelegate> _delegate;
    NSArray *_functionArray;
    UICollectionView *_collectionView;
    KRLCollectionViewGridLayout *_collectionLayout;
}

@property(nonatomic) __weak KRLCollectionViewGridLayout *collectionLayout; // @synthesize collectionLayout=_collectionLayout;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *functionArray; // @synthesize functionArray=_functionArray;
@property(nonatomic) __weak id <LeaderFunctionCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

