//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class LeaderHeaderJobBean, UIButton, UILabel;

@interface LeaderHeaderView : UIView
{
    long long _modeType;
    long long _headerType;
    id <LeaderHeaderViewDelegate> _delegate;
    LeaderHeaderJobBean *_headerJobBean;
    long long _hireCount;
    long long _consultCount;
    long long _applyNew;
    long long _commentNew;
    UIView *_noOrderView;
    UIButton *_noOrder_actionBtn;
    UILabel *_noOrder_tipLabel;
    UILabel *_lblApplyNew;
    UILabel *_lblCommentNew;
    UIView *_orderVIew;
    UIView *_reviewView;
    UIButton *_jobNameBtn;
    UILabel *_singupCountLabel;
    UILabel *_hireCountLabel;
    UILabel *_consultCountLabel;
    UIButton *_readCountBtn;
    UIButton *_totalHireCountBtn;
    UIView *_signupCountParentView;
    UIView *_hireCountParentView;
    UIView *_consultParentView;
}

@property(nonatomic) __weak UIView *consultParentView; // @synthesize consultParentView=_consultParentView;
@property(nonatomic) __weak UIView *hireCountParentView; // @synthesize hireCountParentView=_hireCountParentView;
@property(nonatomic) __weak UIView *signupCountParentView; // @synthesize signupCountParentView=_signupCountParentView;
@property(nonatomic) __weak UIButton *totalHireCountBtn; // @synthesize totalHireCountBtn=_totalHireCountBtn;
@property(nonatomic) __weak UIButton *readCountBtn; // @synthesize readCountBtn=_readCountBtn;
@property(nonatomic) __weak UILabel *consultCountLabel; // @synthesize consultCountLabel=_consultCountLabel;
@property(nonatomic) __weak UILabel *hireCountLabel; // @synthesize hireCountLabel=_hireCountLabel;
@property(nonatomic) __weak UILabel *singupCountLabel; // @synthesize singupCountLabel=_singupCountLabel;
@property(nonatomic) __weak UIButton *jobNameBtn; // @synthesize jobNameBtn=_jobNameBtn;
@property(nonatomic) __weak UIView *reviewView; // @synthesize reviewView=_reviewView;
@property(nonatomic) __weak UIView *orderVIew; // @synthesize orderVIew=_orderVIew;
@property(nonatomic) __weak UILabel *lblCommentNew; // @synthesize lblCommentNew=_lblCommentNew;
@property(nonatomic) __weak UILabel *lblApplyNew; // @synthesize lblApplyNew=_lblApplyNew;
@property(nonatomic) __weak UILabel *noOrder_tipLabel; // @synthesize noOrder_tipLabel=_noOrder_tipLabel;
@property(nonatomic) __weak UIButton *noOrder_actionBtn; // @synthesize noOrder_actionBtn=_noOrder_actionBtn;
@property(nonatomic) __weak UIView *noOrderView; // @synthesize noOrderView=_noOrderView;
@property(nonatomic) long long commentNew; // @synthesize commentNew=_commentNew;
@property(nonatomic) long long applyNew; // @synthesize applyNew=_applyNew;
@property(nonatomic) long long consultCount; // @synthesize consultCount=_consultCount;
@property(nonatomic) long long hireCount; // @synthesize hireCount=_hireCount;
@property(retain, nonatomic) LeaderHeaderJobBean *headerJobBean; // @synthesize headerJobBean=_headerJobBean;
@property(nonatomic) __weak id <LeaderHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long headerType; // @synthesize headerType=_headerType;
@property(nonatomic) long long modeType; // @synthesize modeType=_modeType;
- (void).cxx_destruct;
- (void)eventCallBack:(long long)arg1;
- (void)consultParentViewTap;
- (void)hireCountParentViewTap;
- (void)signupCountParentViewTap;
- (void)switchOrderBtnClick:(id)arg1;
- (void)acceptOrderBtnClick:(id)arg1;
- (void)awakeFromNib;

@end

