//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSString;

@interface LeaderBannerBean : ObjectBeanBase
{
    NSString *_id;
    NSString *_img;
    NSString *_remark;
    NSString *_url;
    long long _url_state;
}

@property(nonatomic) long long url_state; // @synthesize url_state=_url_state;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(retain, nonatomic) NSString *img; // @synthesize img=_img;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

