//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseWebViewController.h"

@class UIButton;

@interface LeaderApplyViewController : BaseWebViewController
{
    UIButton *_shareBtn;
}

@property(retain, nonatomic) UIButton *shareBtn; // @synthesize shareBtn=_shareBtn;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)shareHandler:(id)arg1 sender:(id)arg2;
- (void)shareBtnHandler:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

