//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSArray, NSString;

@interface LeaderOrderBean : ObjectBeanBase
{
    NSString *_bonus;
    NSString *_salary;
    NSString *_title;
    NSString *_trusteeship_id;
    NSString *_job_type;
    long long _resume_num;
    long long _assign_days;
    long long _status;
    NSString *_address;
    NSString *_area;
    NSString *_city;
    NSString *_admin_remark;
    NSString *_latitude;
    NSString *_longitude;
    NSArray *_requirement;
    NSString *_remark;
    NSString *_salary_unit;
    NSString *_scheme_id;
    NSString *_trust_name;
    NSString *_work_days;
    NSString *_money;
    NSString *_job_id;
}

@property(retain, nonatomic) NSString *job_id; // @synthesize job_id=_job_id;
@property(retain, nonatomic) NSString *money; // @synthesize money=_money;
@property(retain, nonatomic) NSString *work_days; // @synthesize work_days=_work_days;
@property(retain, nonatomic) NSString *trust_name; // @synthesize trust_name=_trust_name;
@property(retain, nonatomic) NSString *scheme_id; // @synthesize scheme_id=_scheme_id;
@property(retain, nonatomic) NSString *salary_unit; // @synthesize salary_unit=_salary_unit;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(retain, nonatomic) NSArray *requirement; // @synthesize requirement=_requirement;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *admin_remark; // @synthesize admin_remark=_admin_remark;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) long long assign_days; // @synthesize assign_days=_assign_days;
@property(nonatomic) long long resume_num; // @synthesize resume_num=_resume_num;
@property(retain, nonatomic) NSString *job_type; // @synthesize job_type=_job_type;
@property(retain, nonatomic) NSString *trusteeship_id; // @synthesize trusteeship_id=_trusteeship_id;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *salary; // @synthesize salary=_salary;
@property(retain, nonatomic) NSString *bonus; // @synthesize bonus=_bonus;
- (void).cxx_destruct;
- (id)orderStatusColor;
- (id)orderStatusString;

@end

