//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LocalMapElement;

@interface LocalMapInfo : NSObject
{
    LocalMapElement *_local;
    LocalMapElement *_server;
    struct BMRect _bound;
}

@property(nonatomic) struct BMRect bound; // @synthesize bound=_bound;
@property(retain, nonatomic) LocalMapElement *serverData; // @synthesize serverData=_server;
@property(retain, nonatomic) LocalMapElement *localData; // @synthesize localData=_local;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

