//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSString, NSTimer, UIPageControl, UIScrollView;

@interface LQCycleBannerView : UIView <UIScrollViewDelegate>
{
    UIView *preView;
    UIView *curView;
    UIView *nextView;
    double curXOffset;
    NSTimer *autoScrollTimer;
    _Bool canAutoScroll;
    UIPageControl *pageControl;
    long long pageCount;
    UIScrollView *scrollView;
    id <LQCycleBannerViewDataSource> dataSource;
    double autoScrollDuration;
    long long curPage;
}

@property(nonatomic) long long curPage; // @synthesize curPage;
@property(nonatomic) double autoScrollDuration; // @synthesize autoScrollDuration;
@property(nonatomic) _Bool canAutoScroll; // @synthesize canAutoScroll;
@property(nonatomic) __weak id <LQCycleBannerViewDataSource> dataSource; // @synthesize dataSource;
@property(readonly, nonatomic) long long pageCount; // @synthesize pageCount;
- (void).cxx_destruct;
- (id)placeholder;
- (void)reloadData;
- (void)reloadView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)pageChanged:(id)arg1;
@property(readonly, nonatomic) UIPageControl *pageControl; // @synthesize pageControl;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView;
- (void)config;
- (void)autoScroll;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

