//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSFileManager, NSObject<OS_dispatch_queue>, NSString;

@interface LYCache : NSObject
{
    NSCache *_cache;
    NSString *_diskCachePath;
    NSFileManager *_fileManager;
    NSObject<OS_dispatch_queue> *_fileQueue;
}

+ (id)instance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *fileQueue; // @synthesize fileQueue=_fileQueue;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(retain, nonatomic) NSString *diskCachePath; // @synthesize diskCachePath=_diskCachePath;
@property(retain, nonatomic) NSCache *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (void)logError:(id)arg1;
- (unsigned long long)diskCacheCapacity;
- (void)clearDisk;
- (void)clearMemoryCache;
- (void)cleanAllCache;
- (void)removeCacheForKey:(id)arg1 fromDisk:(_Bool)arg2;
- (id)readForKey:(id)arg1 fromDisk:(_Bool)arg2;
- (id)readForKey:(id)arg1;
- (id)filePathForKey:(id)arg1;
- (void)write:(id)arg1 forKey:(id)arg2 toDisk:(_Bool)arg3;
- (void)write:(id)arg1 forKey:(id)arg2;
- (void)setCacheCountLimit:(long long)arg1;
- (void)setCacheTotalCostLimit:(long long)arg1;
- (void)initCache;

@end

