//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LYCacheUtils : NSObject
{
}

+ (id)ly_md5:(id)arg1 accessory:(id)arg2;
+ (id)ly_dateForGMT:(id)arg1;
+ (id)ly_dateFromDateString:(id)arg1;
+ (id)ly_currentDateStr;
+ (id)ly_currentDateForGMT;

@end

