//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LYMenuView;

@interface LYMenu : NSObject
{
    _Bool _showing;
    LYMenuView *_menuView;
}

+ (void)dismissMenu:(_Bool)arg1;
+ (void)showMenuInView:(id)arg1 fromRect:(struct CGRect)arg2 menuItems:(id)arg3;
+ (id)sharedMenu;
@property(retain, nonatomic) LYMenuView *menuView; // @synthesize menuView=_menuView;
@property(nonatomic) _Bool showing; // @synthesize showing=_showing;
- (void).cxx_destruct;
- (void)dealloc;
- (void)dismissMenu:(_Bool)arg1;
- (void)showMenuInView:(id)arg1 fromRect:(struct CGRect)arg2 menuItems:(id)arg3;
- (id)init;

@end

