//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LYMenuItem : NSObject
{
    _Bool _canResponse;
    NSString *_title;
    NSString *_imagePath;
    id _target;
    id _userInfo;
    SEL _action;
}

+ (id)menuItem:(id)arg1 imagePath:(id)arg2 target:(id)arg3 action:(SEL)arg4 userInfo:(id)arg5 canResponse:(_Bool)arg6;
@property(nonatomic) _Bool canResponse; // @synthesize canResponse=_canResponse;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(retain, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithMenuItem:(id)arg1 imagePath:(id)arg2 target:(id)arg3 action:(SEL)arg4 userInfo:(id)arg5 canResponse:(_Bool)arg6;

@end

