//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MAFileUtil : NSObject
{
}

+ (void)deleteAll:(id)arg1;
+ (long long)_folderSizeAtPath:(const char *)arg1;
+ (long long)folderSizeAtPath:(id)arg1;
+ (id)getFolderSize:(long long)arg1;
+ (_Bool)removeFile:(id)arg1;
+ (id)readStringFromFile:(id)arg1;
+ (_Bool)appendStringToFile:(id)arg1 string:(id)arg2;
+ (id)applicationStorageDirectory;
+ (id)applicationDocumentsDirectory;
+ (id)directory:(unsigned long long)arg1;
+ (_Bool)createDirectoryAtDocument:(id)arg1;
+ (_Bool)createFileAtPath:(id)arg1;
+ (_Bool)createFileAtDirectory:(id)arg1 fileName:(id)arg2;
+ (_Bool)createDirectoryAtPath:(id)arg1;

@end

