//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "CommonCellModelBaseGenerator.h"
#import "PersonalSignDetailDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ManualSignStatConfiguration, NSString, PagedRequestManager, UITableView;

@interface ManualSignStatViewController : BaseNavViewController <UITableViewDelegate, UITableViewDataSource, CommonCellModelBaseGenerator, PersonalSignDetailDelegate>
{
    ManualSignStatConfiguration *_configuration;
    UITableView *_tableView;
    PagedRequestManager *_pageManager;
}

@property(retain, nonatomic) PagedRequestManager *pageManager; // @synthesize pageManager=_pageManager;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) ManualSignStatConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)updateAllDataWithViewCtrl:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)generatorModelWithDataSource:(id)arg1;
- (void)getDataWithLoadMode:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)mj_loadMoreData;
- (void)mj_refreshData;
- (void)initView;
- (void)initData;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

