//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMItsEvent, BMStreetScapeEvent, NSMutableArray;

@interface MapEventObj : NSObject
{
    NSMutableArray *_dataset;
    BMItsEvent *_itsEvent;
    BMStreetScapeEvent *_streetScapeEvent;
    int _nodeKind;
}

@property(retain, nonatomic) BMStreetScapeEvent *streetScapeEvent; // @synthesize streetScapeEvent=_streetScapeEvent;
@property(nonatomic) int nodeKind; // @synthesize nodeKind=_nodeKind;
@property(retain, nonatomic) BMItsEvent *itsEvent; // @synthesize itsEvent=_itsEvent;
@property(retain, nonatomic) NSMutableArray *dataset; // @synthesize dataset=_dataset;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

