//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MD5Util : NSObject
{
}

+ (id)md5MakeByDic:(id)arg1 md5key:(id)arg2;
+ (id)calc:(id)arg1;
+ (id)companyMd5ExamNum:(id)arg1 md5Key:(id)arg2;
+ (id)md5ExamNum:(id)arg1;

@end

