//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MOAspectsStore : NSObject
{
    NSMutableDictionary *_targetStore;
}

+ (id)keyWithClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3;
+ (id)sharedStore;
@property(retain, nonatomic) NSMutableDictionary *targetStore; // @synthesize targetStore=_targetStore;
- (void).cxx_destruct;
- (id)targetForKey:(id)arg1;
- (void)setTarget:(id)arg1 forKey:(id)arg2;

@end

