//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MOAspects : NSObject
{
}

+ (void)overwritingMessageForwardMethodForClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3;
+ (void)overwritingMethodForClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3 implementationBlock:(id)arg4;
+ (_Bool)copyMethodForClass:(Class)arg1 atSelector:(SEL)arg2 toSelector:(SEL)arg3 methodType:(long long)arg4;
+ (_Bool)hasMethodForClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3;
+ (_Bool)addMethodForClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3 block:(id)arg4;
+ (Class)rootClassForResponodsToClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3;
+ (_Bool)shouldInvokeTarget:(id)arg1 toObject:(id)arg2 selector:(SEL)arg3;
+ (_Bool)isSwiftClass:(Class)arg1;
+ (id)targetInStoreWithClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3 hookRange:(struct _MOAspectsHookRange)arg4;
+ (void)invokeWithTarget:(id)arg1 toObject:(id)arg2 invocation:(id)arg3;
+ (id)invocationWithBaseInvocation:(id)arg1 targetObject:(id)arg2;
+ (_Bool)isValidClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3;
+ (void)addHookMethodWithTarget:(id)arg1 class:(Class)arg2 aspectsPosition:(long long)arg3 usingBlock:(id)arg4;
+ (SEL)afterSelectorWithTarget:(id)arg1;
+ (SEL)beforeSelectorWithTarget:(id)arg1;
+ (_Bool)putMethodForClass:(Class)arg1 selector:(SEL)arg2 methodTyoe:(long long)arg3;
+ (_Bool)hookMethodForClass:(Class)arg1 selector:(SEL)arg2 methodType:(long long)arg3 aspectsPosition:(long long)arg4 hookRange:(struct _MOAspectsHookRange)arg5 usingBlock:(id)arg6;
+ (_Bool)hookClassMethodForClass:(Class)arg1 selector:(SEL)arg2 aspectsPosition:(long long)arg3 hookRange:(struct _MOAspectsHookRange)arg4 usingBlock:(id)arg5;
+ (_Bool)hookClassMethodForClass:(Class)arg1 selector:(SEL)arg2 aspectsPosition:(long long)arg3 usingBlock:(id)arg4;
+ (_Bool)hookInstanceMethodForClass:(Class)arg1 selector:(SEL)arg2 aspectsPosition:(long long)arg3 hookRange:(struct _MOAspectsHookRange)arg4 usingBlock:(id)arg5;
+ (_Bool)hookInstanceMethodForClass:(Class)arg1 selector:(SEL)arg2 aspectsPosition:(long long)arg3 usingBlock:(id)arg4;
+ (_Bool)hookClassMethodForClass:(Class)arg1 selector:(SEL)arg2 position:(long long)arg3 usingParameterBlock0:(CDUnknownBlockType)arg4;
+ (_Bool)hookClassMethodForClass:(Class)arg1 selector:(SEL)arg2 position:(long long)arg3 usingNoParameterBlock:(CDUnknownBlockType)arg4;
+ (_Bool)hookInstanceMethodForClass:(Class)arg1 selector:(SEL)arg2 position:(long long)arg3 usingParameterBlock0:(CDUnknownBlockType)arg4;
+ (_Bool)hookInstanceMethodForClass:(Class)arg1 selector:(SEL)arg2 position:(long long)arg3 usingNoParameterBlock:(CDUnknownBlockType)arg4;

@end

