//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSURL;

@interface MOBFImageObserver : NSObject
{
    NSURL *_url;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    CDUnknownBlockType _resultHandler;
}

@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)fault:(id)arg1;
- (void)result:(id)arg1;
- (id)initWithURL:(id)arg1 result:(CDUnknownBlockType)arg2;

@end

