//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface MOBFImageListener : NSObject
{
    NSURL *_imageURL;
    CDUnknownBlockType _resultHandler;
    CDUnknownBlockType _failHandler;
    CDUnknownBlockType _loadingHandler;
}

@property(copy, nonatomic) CDUnknownBlockType loadingHandler; // @synthesize loadingHandler=_loadingHandler;
@property(copy, nonatomic) CDUnknownBlockType failHandler; // @synthesize failHandler=_failHandler;
@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (id)initWithURL:(id)arg1 resultHandler:(CDUnknownBlockType)arg2 failHandler:(CDUnknownBlockType)arg3 loadingHandler:(CDUnknownBlockType)arg4;

@end

