//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHTTPURLResponse, NSMutableData, NSMutableDictionary, NSMutableURLRequest, NSString, NSURLConnection;

@interface MOBFHttpService : NSObject
{
    _Bool _isCacheResponse;
    _Bool _autoFillRequestForm;
    NSMutableURLRequest *_request;
    NSURLConnection *_connection;
    NSHTTPURLResponse *_response;
    NSMutableData *_responseData;
    NSMutableDictionary *_parameters;
    NSString *_boundaryString;
    MOBFHttpService *_selfReference;
    CDUnknownBlockType _resultHandler;
    CDUnknownBlockType _faultHandler;
    CDUnknownBlockType _uploadProgressHandler;
}

+ (id)sendHttpRequestByURLString:(id)arg1 method:(id)arg2 parameters:(id)arg3 headers:(id)arg4 onResult:(CDUnknownBlockType)arg5 onFault:(CDUnknownBlockType)arg6 onUploadProgress:(CDUnknownBlockType)arg7;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressHandler; // @synthesize uploadProgressHandler=_uploadProgressHandler;
@property(copy, nonatomic) CDUnknownBlockType faultHandler; // @synthesize faultHandler=_faultHandler;
@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(retain, nonatomic) MOBFHttpService *selfReference; // @synthesize selfReference=_selfReference;
@property(copy, nonatomic) NSString *boundaryString; // @synthesize boundaryString=_boundaryString;
@property(retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(nonatomic) _Bool autoFillRequestForm; // @synthesize autoFillRequestForm=_autoFillRequestForm;
@property(nonatomic) _Bool isCacheResponse; // @synthesize isCacheResponse=_isCacheResponse;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)multipartFormDataUsingEncoding:(unsigned long long)arg1;
- (id)parametersDataUsingEncoding:(unsigned long long)arg1;
- (id)parametersStringUsingEncoding:(unsigned long long)arg1;
- (void)setupDeleteParams;
- (void)setupPostParams;
- (void)setupGetParams;
- (void)sendRequest;
- (void)prepareSendRequest;
- (void)genBoundaryString;
- (void)cancelRequest;
- (void)sendRequestOnResult:(CDUnknownBlockType)arg1 onFault:(CDUnknownBlockType)arg2 onUploadProgress:(CDUnknownBlockType)arg3;
- (void)setBody:(id)arg1;
- (void)addFileParameter:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3 transferEncoding:(id)arg4 forKey:(id)arg5;
- (void)addParameters:(id)arg1;
- (void)addParameter:(id)arg1 forKey:(id)arg2;
- (void)addHeaders:(id)arg1;
- (void)addHeader:(id)arg1 value:(id)arg2;
@property(copy, nonatomic) NSString *method;
- (id)initWithRequest:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithURLString:(id)arg1;
- (id)init;
- (void)dealloc;

@end

