//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "AJAlertViewDelegate.h"
#import "UITextViewDelegate.h"

@class JWTextView, NSArray, NSObject<OS_dispatch_queue>, NSString, PartimeJobBean, UIButton, UILabel;

@interface NotificationViewController : BaseNavViewController <AJAlertViewDelegate, UITextViewDelegate>
{
    UIButton *_rightBtn;
    long long _employLastCount;
    NSObject<OS_dispatch_queue> *_notificaionQueue;
    NSArray *_dataSource;
    PartimeJobBean *_partimeJobBean;
    unsigned long long _notificationType;
    UILabel *_letterCountLabel;
    UILabel *_notificationTitleLab;
    UILabel *_countLab;
    JWTextView *_contentTextView;
    UILabel *_warmLab;
}

@property(retain, nonatomic) UILabel *warmLab; // @synthesize warmLab=_warmLab;
@property(retain, nonatomic) JWTextView *contentTextView; // @synthesize contentTextView=_contentTextView;
@property(retain, nonatomic) UILabel *countLab; // @synthesize countLab=_countLab;
@property(retain, nonatomic) UILabel *notificationTitleLab; // @synthesize notificationTitleLab=_notificationTitleLab;
@property(nonatomic) __weak UILabel *letterCountLabel; // @synthesize letterCountLabel=_letterCountLabel;
@property(nonatomic) unsigned long long notificationType; // @synthesize notificationType=_notificationType;
@property(retain, nonatomic) PartimeJobBean *partimeJobBean; // @synthesize partimeJobBean=_partimeJobBean;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)toFlagShowVCWithFlag:(unsigned long long)arg1;
- (void)notification;
- (void)popToMainViewCtrl;
- (void)getCanNotificationUserCount:(long long)arg1;
- (void)alertView:(id)arg1 buttonClick:(long long)arg2;
- (void)createPopView_doApplyError:(id)arg1 needToast:(_Bool)arg2;
- (void)requestApplyWith:(long long)arg1;
- (void)requestGroupNotifity:(long long)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)insertMessage:(id)arg1;
- (void)backupMessage:(id)arg1;
- (id)applyidFromDatasource:(id)arg1;
- (void)updateInfo;
- (void)rightHandler:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

