//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (EMEncryption)
+ (id)EMMD5HexDigest:(id)arg1;
+ (id)EMMD5Digest:(id)arg1;
+ (id)em_dataWithBase64EncodedString:(id)arg1;
- (id)EMMD5HexDigest;
- (id)EMMD5Digest;
- (id)EMAES256DecryptWithKey:(id)arg1;
- (id)EMAES256EncryptWithKey:(id)arg1;
- (id)EMAES256Encrypt;
- (id)EMAES256Decrypt;
- (id)em_base64EncodedString;
- (id)em_base64EncodedStringWithWrapWidth:(unsigned long long)arg1;
@end

