//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (BTGBase64)
+ (id)btg_dataFromBase64String:(id)arg1;
- (id)btg_base64EncodedString;
@end

