//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (EMCompression)
+ (id)em_gz_dataWithCompressedData:(id)arg1;
+ (id)em_gz_dataWithCompressedBytes:(const void *)arg1 length:(unsigned long long)arg2;
+ (id)em_gz_compressedDataWithData:(id)arg1;
+ (id)em_gz_compressedDataWithBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (id)em_gzipDeflate;
- (id)em_gzipInflate;
- (id)em_zlibDeflate;
- (id)em_zlibInflate;
@end

