//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (Category)
+ (id)attributedStringWithHTMLString:(id)arg1;
- (void)insertImage:(id)arg1 inRect:(struct CGRect)arg2 atIndex:(long long)arg3;
@end

