//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (BTGNetworkKitAdditions)
+ (id)btg_uniqueString;
- (id)btg_urlDecodedString;
- (id)btg_urlEncodedString;
- (id)btg_md5;
@end

