//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (emdecoration)
- (id)em_substringFrom:(long long)arg1 to:(long long)arg2;
- (id)em_splitByDelimeter:(id)arg1;
- (id)em_splitOnChar:(BOOL)arg1;
- (id)em_stringByStrippingWhitespace;
- (_Bool)em_contains:(id)arg1;
- (_Bool)em_isBlank;
- (id)em_trim:(id)arg1;
- (id)em_trimRight:(id)arg1;
- (id)em_trimLeft:(id)arg1;
@end

