//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIResponder<UITextInput>;

@interface NumKeyboard : UIView
{
    struct {
        unsigned int textInputSupportsShouldChangeTextInRange:1;
        unsigned int delegateSupportsTextFieldShouldChangeCharactersInRange:1;
        unsigned int delegateSupportsTextViewShouldChangeTextInRange:1;
    } _delegateFlags;
    UIResponder<UITextInput> *_textInput;
    UIButton *_num_1_Button;
    UIButton *_num_2_Button;
    UIButton *_num_3_Button;
    UIButton *_num_4_Button;
    UIButton *_num_5_Button;
    UIButton *_num_6_Button;
    UIButton *_num_7_Button;
    UIButton *_num_8_Button;
    UIButton *_num_9_Button;
    UIButton *_num_0_Button;
    UIButton *_num_clear_Button;
}

+ (struct _NSRange)selectedRange:(id)arg1;
@property(nonatomic) __weak UIButton *num_clear_Button; // @synthesize num_clear_Button=_num_clear_Button;
@property(nonatomic) __weak UIButton *num_0_Button; // @synthesize num_0_Button=_num_0_Button;
@property(nonatomic) __weak UIButton *num_9_Button; // @synthesize num_9_Button=_num_9_Button;
@property(nonatomic) __weak UIButton *num_8_Button; // @synthesize num_8_Button=_num_8_Button;
@property(nonatomic) __weak UIButton *num_7_Button; // @synthesize num_7_Button=_num_7_Button;
@property(nonatomic) __weak UIButton *num_6_Button; // @synthesize num_6_Button=_num_6_Button;
@property(nonatomic) __weak UIButton *num_5_Button; // @synthesize num_5_Button=_num_5_Button;
@property(nonatomic) __weak UIButton *num_4_Button; // @synthesize num_4_Button=_num_4_Button;
@property(nonatomic) __weak UIButton *num_3_Button; // @synthesize num_3_Button=_num_3_Button;
@property(nonatomic) __weak UIButton *num_2_Button; // @synthesize num_2_Button=_num_2_Button;
@property(nonatomic) __weak UIButton *num_1_Button; // @synthesize num_1_Button=_num_1_Button;
@property(nonatomic) __weak UIResponder<UITextInput> *textInput; // @synthesize textInput=_textInput;
- (void).cxx_destruct;
- (void)clearButtonAction;
- (void)numberButtonAction:(id)arg1;
- (void)btnClick:(id)arg1;
- (void)finishBtnClick:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)textDidBeginEditing:(id)arg1;
- (void)addNotificationsObservers;
- (void)setupView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

