//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UILabel;

@interface PaopaoButton : UIControl
{
    UIImageView *_leftImage;
    UIImageView *_rightImage;
    UILabel *_label;
    UILabel *_detailLabel;
    double _minWidth;
    double _maxWidth;
    double _textPadding;
    double _paopaoHeight;
}

@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) double paopaoHeight; // @synthesize paopaoHeight=_paopaoHeight;
@property(nonatomic) double minWidth; // @synthesize minWidth=_minWidth;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setHighlighted:(_Bool)arg1;
- (void)setText:(id)arg1 andDetailText:(id)arg2;
- (void)adjustPaopaoForWidth:(double)arg1 withLeftOffset:(double)arg2;
- (id)initWithLeftImage:(id)arg1 highlightedLeftImage:(id)arg2 leftStretchRect:(struct CGRect)arg3 andRightImage:(id)arg4 highlightedRightImage:(id)arg5 rightStretchRect:(struct CGRect)arg6;
- (void)initElements;

@end

