//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseCell.h"

@class JobTypeImageView, NSString, UIImageView, UILabel, UIView;

@interface PartimeJobListBaseCell : BaseCell
{
    UIView *_midView;
    UIImageView *_midLineView;
    UIView *_bottomView;
    UIView *_marginView;
    JobTypeImageView *_logoView;
    UILabel *_titleLab;
    UIImageView *_addressLogoView;
    UILabel *_addressLab;
    UIImageView *_timeLogoView;
    UILabel *_timeLab;
    NSString *_jobTypeName;
    long long _status;
    long long _jobType;
    long long _cellType;
}

+ (double)cellHeight;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) long long jobType; // @synthesize jobType=_jobType;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *jobTypeName; // @synthesize jobTypeName=_jobTypeName;
@property(retain, nonatomic) UILabel *timeLab; // @synthesize timeLab=_timeLab;
@property(retain, nonatomic) UIImageView *timeLogoView; // @synthesize timeLogoView=_timeLogoView;
@property(retain, nonatomic) UILabel *addressLab; // @synthesize addressLab=_addressLab;
@property(retain, nonatomic) UIImageView *addressLogoView; // @synthesize addressLogoView=_addressLogoView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) JobTypeImageView *logoView; // @synthesize logoView=_logoView;
@property(retain, nonatomic) UIView *marginView; // @synthesize marginView=_marginView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *midLineView; // @synthesize midLineView=_midLineView;
@property(retain, nonatomic) UIView *midView; // @synthesize midView=_midView;
- (void).cxx_destruct;
- (void)buildView:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

