//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PartimeJobManagerBaseCell.h"

@class UILabel;

@interface PartimeJobManagerUndercarriageCell : PartimeJobManagerBaseCell
{
    UILabel *_statusLab;
}

@property(retain, nonatomic) UILabel *statusLab; // @synthesize statusLab=_statusLab;
- (void).cxx_destruct;
- (void)setShowType:(long long)arg1;
- (void)showControl:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

