//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "PartimeJobManagerBaseViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class CustomSegmentedControl, NSArray, NSString, PartimeJobPendingViewController, PartimeJobRecruitViewController, PartimeJobUndercarriageViewController, UIButton, UIScrollView;

@interface PartimeJobManagerViewController : BaseNavViewController <PartimeJobManagerBaseViewControllerDelegate, UIScrollViewDelegate>
{
    CustomSegmentedControl *_segmentCtrl;
    UIScrollView *_scrollView;
    NSArray *_titleArray;
    long long _tag;
    PartimeJobPendingViewController *_pendingViewCtrl;
    PartimeJobRecruitViewController *_recruitViewCtrl;
    PartimeJobUndercarriageViewController *_undercarriageViewCtrl;
    UIButton *_rightBtn;
    long long _managerType;
}

- (void).cxx_destruct;
- (void)selectToIndexHandler:(id)arg1;
- (void)notificationHandler:(id)arg1;
- (void)logoutHandler:(id)arg1;
- (void)toSceneEmployViewController:(id)arg1;
- (void)toWagePaymentViewController:(id)arg1;
- (void)toPayViewController:(id)arg1 partimejobBean:(id)arg2 paymentType:(long long)arg3;
- (void)toExplainVC:(id)arg1;
- (void)toTrusteeshipDetailVC:(id)arg1 trusteeshipDetailType:(unsigned long long)arg2;
- (void)toLeaderPushVC:(id)arg1;
- (void)toTrusteeshipConditionViewCtrl:(id)arg1;
- (void)toTrusteeshipJobPaymentVC:(id)arg1;
- (void)toPushJobVC:(long long)arg1;
- (void)toJobAndResumeManagerVC:(id)arg1 jobAndResumeType:(unsigned long long)arg2 partTimeJobType:(long long)arg3 partimeJobType:(long long)arg4;
- (void)toJobDetailVC:(id)arg1 jobDetailType:(unsigned long long)arg2 isSpread:(_Bool)arg3;
- (void)pushToSceneEmployViewControlle:(id)arg1;
- (void)pushToWagePaymentViewController:(id)arg1;
- (void)pushToPayViewController:(id)arg1 partimejobBean:(id)arg2 paymentType:(long long)arg3;
- (void)pushToExplainViewController:(id)arg1;
- (void)pushToTrusteeshipDetailVC:(id)arg1 trusteeshipDetailType:(unsigned long long)arg2;
- (void)pushToLeaderPushVC:(id)arg1;
- (void)pushToTrusteeshipConditionViewCtrl:(id)arg1;
- (void)pushToTrusteeshipJobPaymentVC:(id)arg1;
- (void)pushToPushJobVC:(long long)arg1;
- (void)pushToJobAndResumeManagerVC:(id)arg1 jobAndResumeType:(unsigned long long)arg2 partTimeJobType:(long long)arg3 partimeJobType:(long long)arg4;
- (void)pushToJobDetailVC:(id)arg1 jobDetailType:(unsigned long long)arg2 isSpread:(_Bool)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectToUndercarriage:(_Bool)arg1;
- (void)selectToRecruit:(_Bool)arg1;
- (void)selectToPending:(_Bool)arg1;
- (void)segmentedControlHandler:(id)arg1;
- (void)updateStatus;
- (void)makeTabBarHidden:(_Bool)arg1;
- (void)showControl:(_Bool)arg1;
- (void)rightHandler:(id)arg1;
- (void)reloadUndercarriage;
- (void)reloadRecuitData;
- (void)reloadPending;
- (void)initialization;
- (void)refreshPushSurplus;
- (void)refreshRefreshSurplus;
- (void)initData;
- (void)initUndercarriage;
- (void)initRecruit;
- (void)initPending;
- (void)initView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

