//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PartimeJobListBaseCell.h"

@class UIButton, UIImageView, UILabel;

@interface PartimeJobListCommonCell : PartimeJobListBaseCell
{
    UIImageView *_postBgView;
    UILabel *_postCountLab;
    UILabel *_statusLab;
    UIButton *_firstBtn;
    UIButton *_secondBtn;
    UIButton *_thirdBtn;
    UIButton *_fourthBtn;
    UIImageView *_rightBtnArrawView;
}

@property(retain, nonatomic) UIImageView *rightBtnArrawView; // @synthesize rightBtnArrawView=_rightBtnArrawView;
@property(retain, nonatomic) UIButton *fourthBtn; // @synthesize fourthBtn=_fourthBtn;
@property(retain, nonatomic) UIButton *thirdBtn; // @synthesize thirdBtn=_thirdBtn;
@property(retain, nonatomic) UIButton *secondBtn; // @synthesize secondBtn=_secondBtn;
@property(retain, nonatomic) UIButton *firstBtn; // @synthesize firstBtn=_firstBtn;
@property(retain, nonatomic) UILabel *statusLab; // @synthesize statusLab=_statusLab;
@property(retain, nonatomic) UILabel *postCountLab; // @synthesize postCountLab=_postCountLab;
@property(retain, nonatomic) UIImageView *postBgView; // @synthesize postBgView=_postBgView;
- (void).cxx_destruct;
- (void)showNew:(_Bool)arg1;
- (void)buildView:(id)arg1;
- (void)setCellType:(long long)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

