//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

@class UIButton;

@interface PaymentSuccessViewController : BaseNavViewController
{
    UIButton *_completeBtn;
}

@property(nonatomic) __weak UIButton *completeBtn; // @synthesize completeBtn=_completeBtn;
- (void).cxx_destruct;
- (void)completeBtnClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

