//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JWPayInputPopViewDelegate.h"
#import "WXApiDelegate.h"

@class NSString, PayTypeBean;

@interface PaymentService : NSObject <JWPayInputPopViewDelegate, WXApiDelegate>
{
    PayTypeBean *_currentBill;
    CDUnknownBlockType _alipayCallback;
    CDUnknownBlockType _weChatCallback;
    CDUnknownBlockType _walletCallbcak;
    CDUnknownBlockType _cmbWalletCallbcak;
    CDUnknownBlockType _prePayCallback;
    CDUnknownBlockType _jzmPayCallback;
}

+ (id)defaultService;
@property(copy, nonatomic) CDUnknownBlockType jzmPayCallback; // @synthesize jzmPayCallback=_jzmPayCallback;
@property(copy, nonatomic) CDUnknownBlockType prePayCallback; // @synthesize prePayCallback=_prePayCallback;
@property(copy, nonatomic) CDUnknownBlockType cmbWalletCallbcak; // @synthesize cmbWalletCallbcak=_cmbWalletCallbcak;
@property(copy, nonatomic) CDUnknownBlockType walletCallbcak; // @synthesize walletCallbcak=_walletCallbcak;
@property(copy, nonatomic) CDUnknownBlockType weChatCallback; // @synthesize weChatCallback=_weChatCallback;
@property(copy, nonatomic) CDUnknownBlockType alipayCallback; // @synthesize alipayCallback=_alipayCallback;
@property(retain, nonatomic) PayTypeBean *currentBill; // @synthesize currentBill=_currentBill;
- (void).cxx_destruct;
- (void)jWPayInputPopView:(id)arg1 password:(id)arg2 buttonIndex:(long long)arg3;
- (void)payWithCredit:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)payWithPrepay:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)payWithCMBWallet:(id)arg1 andNav:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)payWithWallet:(id)arg1 andView:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)onResp:(id)arg1;
- (void)payWithWeChat:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)handleAlipayResult:(id)arg1;
- (void)payWithAlipay:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)notifyServerUpdatePayStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

