//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PersonalSignDetailConfiguration : NSObject
{
    _Bool _isManualSignedOnly;
    NSString *_applyID;
    NSString *_date;
}

@property(nonatomic) _Bool isManualSignedOnly; // @synthesize isManualSignedOnly=_isManualSignedOnly;
@property(retain, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *applyID; // @synthesize applyID=_applyID;
- (void).cxx_destruct;

@end

