//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSIndexPath, PSTCollectionViewLayout;

@interface PSTCollectionViewExt : NSObject
{
    id <PSTCollectionViewDelegate> _collectionViewDelegate;
    PSTCollectionViewLayout *_nibLayout;
    NSDictionary *_nibCellsExternalObjects;
    NSDictionary *_supplementaryViewsExternalObjects;
    NSIndexPath *_touchingIndexPath;
    NSIndexPath *_currentIndexPath;
}

@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(retain, nonatomic) NSIndexPath *touchingIndexPath; // @synthesize touchingIndexPath=_touchingIndexPath;
@property(retain, nonatomic) NSDictionary *supplementaryViewsExternalObjects; // @synthesize supplementaryViewsExternalObjects=_supplementaryViewsExternalObjects;
@property(retain, nonatomic) NSDictionary *nibCellsExternalObjects; // @synthesize nibCellsExternalObjects=_nibCellsExternalObjects;
@property(retain, nonatomic) PSTCollectionViewLayout *nibLayout; // @synthesize nibLayout=_nibLayout;
@property(nonatomic) id <PSTCollectionViewDelegate> collectionViewDelegate; // @synthesize collectionViewDelegate=_collectionViewDelegate;
- (void).cxx_destruct;

@end

