//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

@class BaseTextField, SecondCountDownTool, UIButton, UITextField;

@interface RegisterStep1ViewController : BaseNavViewController
{
    UITextField *_phoneTF;
    UITextField *_verifyCodeTF;
    BaseTextField *_passwordTF;
    UIButton *_varifyCodeBtn;
    UIButton *_readLicenseCheckBtn;
    SecondCountDownTool *_secondTool;
}

@property(retain, nonatomic) SecondCountDownTool *secondTool; // @synthesize secondTool=_secondTool;
@property(nonatomic) __weak UIButton *readLicenseCheckBtn; // @synthesize readLicenseCheckBtn=_readLicenseCheckBtn;
@property(nonatomic) __weak UIButton *varifyCodeBtn; // @synthesize varifyCodeBtn=_varifyCodeBtn;
@property(nonatomic) __weak BaseTextField *passwordTF; // @synthesize passwordTF=_passwordTF;
@property(nonatomic) __weak UITextField *verifyCodeTF; // @synthesize verifyCodeTF=_verifyCodeTF;
@property(nonatomic) __weak UITextField *phoneTF; // @synthesize phoneTF=_phoneTF;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)btnClick:(id)arg1;
- (void)readVarifyCodeWithPhone:(id)arg1;
- (void)checkPhoneExist:(id)arg1;
- (void)checkAuthCode;
- (void)startToNextStep;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)refreshSecondDown:(id)arg1;
- (void)viewDidLoad;

@end

