//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBean, NSIndexPath, NSMutableArray;

@interface ReleaseJobBridge : NSObject
{
    _Bool _hadStandard;
    NSMutableArray *_cellIDArray;
    AccountBean *_account;
    long long _currentReleaseJobType;
    NSIndexPath *_indexPath_jobTitle;
    NSIndexPath *_indexPath_jobType;
    NSIndexPath *_indexPath_workTime;
    NSIndexPath *_indexPath_workTimeSlot;
    NSIndexPath *_indexPath_hireCount;
    NSIndexPath *_indexPath_wage;
    NSIndexPath *_indexPath_workCount;
    NSIndexPath *_indexPath_gender;
    NSIndexPath *_indexPath_jobDesc;
    NSIndexPath *_indexPath_workAddr;
    NSIndexPath *_indexPath_hostName;
    NSIndexPath *_indexPath_phone;
    NSIndexPath *_indexPath_email;
    NSIndexPath *_indexPath_consult;
    NSIndexPath *_indexPath_footer;
    NSIndexPath *_indexPath_hireRequirement;
}

@property(retain, nonatomic) NSIndexPath *indexPath_hireRequirement; // @synthesize indexPath_hireRequirement=_indexPath_hireRequirement;
@property(retain, nonatomic) NSIndexPath *indexPath_footer; // @synthesize indexPath_footer=_indexPath_footer;
@property(retain, nonatomic) NSIndexPath *indexPath_consult; // @synthesize indexPath_consult=_indexPath_consult;
@property(retain, nonatomic) NSIndexPath *indexPath_email; // @synthesize indexPath_email=_indexPath_email;
@property(retain, nonatomic) NSIndexPath *indexPath_phone; // @synthesize indexPath_phone=_indexPath_phone;
@property(retain, nonatomic) NSIndexPath *indexPath_hostName; // @synthesize indexPath_hostName=_indexPath_hostName;
@property(retain, nonatomic) NSIndexPath *indexPath_workAddr; // @synthesize indexPath_workAddr=_indexPath_workAddr;
@property(retain, nonatomic) NSIndexPath *indexPath_jobDesc; // @synthesize indexPath_jobDesc=_indexPath_jobDesc;
@property(retain, nonatomic) NSIndexPath *indexPath_gender; // @synthesize indexPath_gender=_indexPath_gender;
@property(retain, nonatomic) NSIndexPath *indexPath_workCount; // @synthesize indexPath_workCount=_indexPath_workCount;
@property(retain, nonatomic) NSIndexPath *indexPath_wage; // @synthesize indexPath_wage=_indexPath_wage;
@property(retain, nonatomic) NSIndexPath *indexPath_hireCount; // @synthesize indexPath_hireCount=_indexPath_hireCount;
@property(retain, nonatomic) NSIndexPath *indexPath_workTimeSlot; // @synthesize indexPath_workTimeSlot=_indexPath_workTimeSlot;
@property(retain, nonatomic) NSIndexPath *indexPath_workTime; // @synthesize indexPath_workTime=_indexPath_workTime;
@property(retain, nonatomic) NSIndexPath *indexPath_jobType; // @synthesize indexPath_jobType=_indexPath_jobType;
@property(retain, nonatomic) NSIndexPath *indexPath_jobTitle; // @synthesize indexPath_jobTitle=_indexPath_jobTitle;
@property(nonatomic) long long currentReleaseJobType; // @synthesize currentReleaseJobType=_currentReleaseJobType;
@property(retain, nonatomic) AccountBean *account; // @synthesize account=_account;
@property(nonatomic) _Bool hadStandard; // @synthesize hadStandard=_hadStandard;
@property(retain, nonatomic) NSMutableArray *cellIDArray; // @synthesize cellIDArray=_cellIDArray;
- (void).cxx_destruct;

@end

