//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@interface RequestBeanLeaderPushInfo : RequestBeanBase
{
    long long _trusteeship_id;
}

@property(nonatomic) long long trusteeship_id; // @synthesize trusteeship_id=_trusteeship_id;
- (id)apiPath;

@end

