//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanRepayMoney : RequestBeanBase
{
    NSString *_arrearage_id;
}

@property(copy, nonatomic) NSString *arrearage_id; // @synthesize arrearage_id=_arrearage_id;
- (void).cxx_destruct;
- (double)timeout;
- (id)apiPath;

@end

