//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanOpenArea : RequestBeanBase
{
    NSString *_pre;
    NSString *_mark;
    long long _apiType;
}

@property(nonatomic) long long apiType; // @synthesize apiType=_apiType;
@property(copy, nonatomic) NSString *mark; // @synthesize mark=_mark;
@property(copy, nonatomic) NSString *pre; // @synthesize pre=_pre;
- (void).cxx_destruct;
- (id)apiPath;
- (void)configApiType:(long long)arg1;

@end

