//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanPrepayBill : RequestBeanBase
{
    NSString *_job_id;
    long long _redbag_id;
    long long _resume_num;
    NSString *_salary;
    long long _work_days;
}

@property(nonatomic) long long work_days; // @synthesize work_days=_work_days;
@property(copy, nonatomic) NSString *salary; // @synthesize salary=_salary;
@property(nonatomic) long long resume_num; // @synthesize resume_num=_resume_num;
@property(nonatomic) long long redbag_id; // @synthesize redbag_id=_redbag_id;
@property(copy, nonatomic) NSString *job_id; // @synthesize job_id=_job_id;
- (void).cxx_destruct;
- (double)timeout;
- (id)apiPath;

@end

