//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanRedBagList : RequestBeanBase
{
    NSString *_phone;
    long long _page;
    long long _money;
}

@property(nonatomic) long long money; // @synthesize money=_money;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
- (void).cxx_destruct;
- (id)apiPath;

@end

