//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePagedRequestBean.h"

@class NSString;

@interface RequestBeanGetManualSignStat : BasePagedRequestBean
{
    NSString *_job_id;
    NSString *_dates;
}

@property(retain, nonatomic) NSString *dates; // @synthesize dates=_dates;
@property(retain, nonatomic) NSString *job_id; // @synthesize job_id=_job_id;
- (void).cxx_destruct;
- (id)apiPath;

@end

