//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanHttpsBase.h"

@class NSString;

@interface RequestBeanSetPaymentPwd : RequestBeanHttpsBase
{
    NSString *_pwd;
}

@property(retain, nonatomic) NSString *pwd; // @synthesize pwd=_pwd;
- (void).cxx_destruct;
- (double)timeout;
- (id)apiPath;

@end

