//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanGetAliveSignedList : RequestBeanBase
{
    long long _page;
    NSString *_code_id;
    long long _tag;
}

@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *code_id; // @synthesize code_id=_code_id;
@property(nonatomic) long long page; // @synthesize page=_page;
- (void).cxx_destruct;
- (id)apiPath;

@end

