//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanUpdateGroupInfo : RequestBeanBase
{
    _Bool _is_message_shield;
    _Bool _is_suitable;
    NSString *_group_id;
}

@property(nonatomic) _Bool is_suitable; // @synthesize is_suitable=_is_suitable;
@property(nonatomic) _Bool is_message_shield; // @synthesize is_message_shield=_is_message_shield;
@property(retain, nonatomic) NSString *group_id; // @synthesize group_id=_group_id;
- (void).cxx_destruct;
- (double)timeout;
- (id)apiPath;

@end

