//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@interface RequestBeanIncomeList : RequestBeanBase
{
    long long _page;
}

@property(nonatomic) long long page; // @synthesize page=_page;
- (id)apiPath;

@end

