//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestBeanBase.h"

@class NSString;

@interface RequestBeanSigninSetInvalid : RequestBeanBase
{
    NSString *_sign_id;
}

@property(retain, nonatomic) NSString *sign_id; // @synthesize sign_id=_sign_id;
- (void).cxx_destruct;
- (id)apiPath;

@end

