//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "AJAlertViewDelegate.h"
#import "JobTypeSelectViewControllerDelegate.h"
#import "TagTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, RequirementObj, TableViewFooterView, TableViewHeaderView, UITableView;

@interface RequirementViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate, TagTableViewCellDelegate, JobTypeSelectViewControllerDelegate, AJAlertViewDelegate>
{
    long long _releaseJobType;
    NSString *_jobType;
    NSString *_area;
    NSString *_city;
    NSString *_province;
    NSString *_requirementString;
    id <RequirementViewControllerDelegate> _delegate;
    UITableView *_tableView;
    TableViewFooterView *_footerView;
    TableViewHeaderView *_headerView;
    NSMutableArray *_requirementList;
    NSMutableArray *_prePequirementList;
    RequirementObj *_requirementObj;
    NSMutableArray *_selectedRowArray;
}

@property(retain, nonatomic) NSMutableArray *selectedRowArray; // @synthesize selectedRowArray=_selectedRowArray;
@property(retain, nonatomic) RequirementObj *requirementObj; // @synthesize requirementObj=_requirementObj;
@property(retain, nonatomic) NSMutableArray *prePequirementList; // @synthesize prePequirementList=_prePequirementList;
@property(retain, nonatomic) NSMutableArray *requirementList; // @synthesize requirementList=_requirementList;
@property(retain, nonatomic) TableViewHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) TableViewFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <RequirementViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *requirementString; // @synthesize requirementString=_requirementString;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *jobType; // @synthesize jobType=_jobType;
@property(nonatomic) long long releaseJobType; // @synthesize releaseJobType=_releaseJobType;
- (void).cxx_destruct;
- (void)readHireRequirement;
- (void)getRequirementlist;
- (void)alertView:(id)arg1 buttonClick:(long long)arg2;
- (void)jobTypeDidSelect:(id)arg1;
- (void)tagTableViewCell:(id)arg1 didSelectItem:(id)arg2 selectedRow:(long long)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)resolveHireRequirement:(id)arg1;
- (long long)defaultSelectedRowWidthTagBeanArray:(id)arg1;
- (void)configSelectedRows;
- (void)toJobTypeSelectViewController;
- (void)factorPopViewHandler:(long long)arg1;
- (void)showPopViewFactor;
- (_Bool)checkFactorMore;
- (id)requirementBeanFromIndex:(long long)arg1;
- (void)requirementDidSelected;
- (void)sureBtnHandler:(id)arg1;
- (void)configTrusteeshipRequirementTagBean:(id)arg1 index:(long long)arg2;
- (void)configPreRequirement;
- (void)initRequirementData;
- (void)preRequirementHandler;
- (void)initView;
- (void)initTableView;
- (void)initFooterView;
- (void)initHeaderView;
- (void)initData;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

