//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResponseBeanBase.h"

@class AppVersionInfo;

@interface ResponseBeanCheckVersion : ResponseBeanBase
{
    AppVersionInfo *_obj;
}

@property(retain, nonatomic) AppVersionInfo *obj; // @synthesize obj=_obj;
- (void).cxx_destruct;

@end

