//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResponseBeanList.h"

@class NSArray;

@interface ResponseBeanCleanList : ResponseBeanList
{
}


// Remaining properties
@property(retain, nonatomic) NSArray *list; // @dynamic list;
@property(nonatomic) long long page_sum; // @dynamic page_sum;
@property(nonatomic) long long total_row; // @dynamic total_row;
@end

