//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResponseBeanBase.h"

@class JobDateObj, NSArray;

@interface ResponseBeanList : ResponseBeanBase
{
    JobDateObj *_obj;
    long long _total_row;
    long long _page_sum;
    NSArray *_list;
}

@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(nonatomic) long long page_sum; // @synthesize page_sum=_page_sum;
@property(nonatomic) long long total_row; // @synthesize total_row=_total_row;
@property(retain, nonatomic) JobDateObj *obj; // @synthesize obj=_obj;
- (void).cxx_destruct;

@end

