//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HttpBaseBean.h"

@class NSString;

@interface ResponseBeanBase : HttpBaseBean
{
    NSString *_msg;
    long long _status;
}

+ (id)ignoreSetupPropertys;
+ (void)setupPropertys:(id)arg1 propCount:(unsigned int)arg2 properties:(struct objc_property **)arg3 class:(Class)arg4;
+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
- (void).cxx_destruct;

@end

