//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResumeManagerCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface ResumeManagerEmployCell : ResumeManagerCell
{
    double _contentHeight;
    UIImageView *_statusBgView;
    UILabel *_statusLab;
    UILabel *_signDayCountLab;
    UILabel *_nameLab;
    UIImageView *_sexView;
    UILabel *_ageLab;
    UILabel *_heightLab;
    UILabel *_contentLab;
    UIButton *_editBtn;
    UILabel *_signTotalCountLab;
    UIImageView *_arrawView;
    UIImageView *_bottomSeparateLine;
    UIView *_bottomView;
    UIButton *_paySureBtn;
    UIButton *_cancleBtn;
    UIButton *_signBtn;
    UIButton *_payBtn;
    unsigned long long _employCellType;
    unsigned long long _orderStatus;
}

+ (double)heightForCell:(id)arg1;
@property(nonatomic) unsigned long long orderStatus; // @synthesize orderStatus=_orderStatus;
@property(nonatomic) unsigned long long employCellType; // @synthesize employCellType=_employCellType;
@property(retain, nonatomic) UIButton *payBtn; // @synthesize payBtn=_payBtn;
@property(retain, nonatomic) UIButton *signBtn; // @synthesize signBtn=_signBtn;
@property(retain, nonatomic) UIButton *cancleBtn; // @synthesize cancleBtn=_cancleBtn;
@property(retain, nonatomic) UIButton *paySureBtn; // @synthesize paySureBtn=_paySureBtn;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *bottomSeparateLine; // @synthesize bottomSeparateLine=_bottomSeparateLine;
@property(retain, nonatomic) UIImageView *arrawView; // @synthesize arrawView=_arrawView;
@property(retain, nonatomic) UILabel *signTotalCountLab; // @synthesize signTotalCountLab=_signTotalCountLab;
@property(retain, nonatomic) UIButton *editBtn; // @synthesize editBtn=_editBtn;
@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(retain, nonatomic) UILabel *heightLab; // @synthesize heightLab=_heightLab;
@property(retain, nonatomic) UILabel *ageLab; // @synthesize ageLab=_ageLab;
@property(retain, nonatomic) UIImageView *sexView; // @synthesize sexView=_sexView;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UILabel *signDayCountLab; // @synthesize signDayCountLab=_signDayCountLab;
@property(retain, nonatomic) UILabel *statusLab; // @synthesize statusLab=_statusLab;
@property(retain, nonatomic) UIImageView *statusBgView; // @synthesize statusBgView=_statusBgView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setContent:(id)arg1;
- (void)checkIsRead:(long long)arg1;
- (void)setName:(id)arg1;
- (void)setSex:(id)arg1;
- (void)buildView:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

