//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableDictionary, NSString, PartimeJobBean, ResumeSelectBarView, SelectTitleView, UITableView;

@interface ResumeSelectViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate>
{
    SelectTitleView *_titleView;
    ResumeSelectBarView *_barView;
    UITableView *_selectTableView;
    NSMutableDictionary *_selectedBeanDic;
    NSArray *_dataSource;
    PartimeJobBean *_partimeJobBean;
    unsigned long long _resumeSelectType;
}

@property(nonatomic) unsigned long long resumeSelectType; // @synthesize resumeSelectType=_resumeSelectType;
@property(retain, nonatomic) PartimeJobBean *partimeJobBean; // @synthesize partimeJobBean=_partimeJobBean;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)notification;
- (void)toResumeVC:(id)arg1 title:(id)arg2 resumeType:(unsigned long long)arg3;
- (void)toNotificationVC:(id)arg1 dataSource:(id)arg2 jobBean:(id)arg3 notificationType:(unsigned long long)arg4;
- (void)toFlagShowVCWithFlag:(unsigned long long)arg1;
- (void)createPopView_doApplyError:(id)arg1;
- (void)requestApplyWith:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)logoTapHandler:(id)arg1;
- (void)updateCell:(id)arg1;
- (void)cancleBtnHandler:(id)arg1;
- (void)sureBtnHandler:(id)arg1;
- (void)selectAllBtnHandler:(id)arg1;
- (void)addIndex:(id)arg1;
- (void)removeIndex:(id)arg1;
- (_Bool)checkIndex:(id)arg1;
- (void)removeResumeSelected:(id)arg1;
- (void)removeAllResumeSelected;
- (void)addAllResumeSelected;
- (void)addResumeSelected:(id)arg1;
- (_Bool)resumeIsSelected:(id)arg1;
- (id)resumeFromList:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)initData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

