//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ResumeManagerThreeCell.h"

@class UIButton, UIImageView, UILabel;

@interface ResumeManagerSignupCell : ResumeManagerThreeCell
{
    UIButton *_zmScoreBtn;
    UILabel *_nameLab;
    UIImageView *_sexView;
    UILabel *_ageLab;
    UILabel *_heightLab;
    UIImageView *_arrawView;
    UIButton *_selectedBtn;
    UILabel *_contentLab;
}

@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(retain, nonatomic) UIImageView *arrawView; // @synthesize arrawView=_arrawView;
@property(retain, nonatomic) UILabel *heightLab; // @synthesize heightLab=_heightLab;
@property(retain, nonatomic) UILabel *ageLab; // @synthesize ageLab=_ageLab;
@property(retain, nonatomic) UIImageView *sexView; // @synthesize sexView=_sexView;
@property(retain, nonatomic) UILabel *nameLab; // @synthesize nameLab=_nameLab;
@property(retain, nonatomic) UIButton *zmScoreBtn; // @synthesize zmScoreBtn=_zmScoreBtn;
- (void).cxx_destruct;
- (void)checkIsRead:(long long)arg1;
- (void)buildView:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

