//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseCell.h"

@class UIImageView, UILabel;

@interface RouteDetailCell : BaseCell
{
    UIImageView *_logoView;
    UILabel *_contentLab;
    UILabel *_distanceLab;
}

+ (double)cellHeight;
@property(retain, nonatomic) UILabel *distanceLab; // @synthesize distanceLab=_distanceLab;
@property(retain, nonatomic) UILabel *contentLab; // @synthesize contentLab=_contentLab;
@property(retain, nonatomic) UIImageView *logoView; // @synthesize logoView=_logoView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)resetFrame;
- (void)setDistance:(id)arg1;
- (void)setContent:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

