//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DataVerifier.h"

@class NSString;

@interface RSADataVerifier : NSObject <DataVerifier>
{
    NSString *_publicKey;
}

- (void).cxx_destruct;
- (_Bool)verifyString:(id)arg1 withSign:(id)arg2;
- (id)algorithmName;
- (id)formatPublicKey:(id)arg1;
- (id)initWithPublicKey:(id)arg1;

@end

