//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SceneSigninListBaseViewController.h"

@class NSString, SceneSigninBarView;

@interface SceneSigninListNOSigninViewController : SceneSigninListBaseViewController
{
    SceneSigninBarView *_barView;
}

@property(retain, nonatomic) SceneSigninBarView *barView; // @synthesize barView=_barView;
- (void).cxx_destruct;
- (void)requestSetSigninFix;
- (id)applyId;
- (void)updateEditModel:(_Bool)arg1;
- (void)setSigninFixBtnHandler:(id)arg1;
- (void)selectBtnHandler:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)updateUILocation;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) NSString *code_id;

@end

