//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface SceneSigninActivityIndicatorView : UIImageView
{
    _Bool _isActivityIndicatorAnimation;
    double _activityIndicatorDuration;
}

@property(nonatomic) _Bool isActivityIndicatorAnimation; // @synthesize isActivityIndicatorAnimation=_isActivityIndicatorAnimation;
@property(nonatomic) double activityIndicatorDuration; // @synthesize activityIndicatorDuration=_activityIndicatorDuration;
- (_Bool)isActivityIndicatorAnimating;
- (void)stopActivityIndicatorAnimating;
- (void)startActivityIndicatorAnimating;
- (void)setupImagePath:(id)arg1 size:(struct CGSize)arg2 duration:(double)arg3;
- (void)initData;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

