//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

@class SceneSigninActivityIndicatorView, UIButton, UILabel;

@interface SceneSigninTitleView : BaseView
{
    UILabel *_warnLabel;
    UILabel *_signCodeLabel;
    UIButton *_qrCodeBtn;
    UIButton *_actionBtn;
    SceneSigninActivityIndicatorView *_activityIndicatorView;
    UILabel *_signPersonsLabel;
    UILabel *_signDetailLabel;
    UIButton *_detailBtn;
    unsigned long long _signinStyle;
}

@property(nonatomic) unsigned long long signinStyle; // @synthesize signinStyle=_signinStyle;
@property(retain, nonatomic) UIButton *detailBtn; // @synthesize detailBtn=_detailBtn;
@property(retain, nonatomic) UILabel *signDetailLabel; // @synthesize signDetailLabel=_signDetailLabel;
@property(retain, nonatomic) UILabel *signPersonsLabel; // @synthesize signPersonsLabel=_signPersonsLabel;
@property(retain, nonatomic) SceneSigninActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIButton *actionBtn; // @synthesize actionBtn=_actionBtn;
@property(retain, nonatomic) UIButton *qrCodeBtn; // @synthesize qrCodeBtn=_qrCodeBtn;
@property(retain, nonatomic) UILabel *signCodeLabel; // @synthesize signCodeLabel=_signCodeLabel;
@property(retain, nonatomic) UILabel *warnLabel; // @synthesize warnLabel=_warnLabel;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

