//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableArray, NSString, SceneSigninTitleView, SigninInfoObj, UICollectionView;

@interface SceneSigninViewController : BaseNavViewController <UICollectionViewDelegate, UICollectionViewDataSource>
{
    NSString *_job_id;
    SceneSigninTitleView *_titleView;
    UICollectionView *_collectionView;
    SigninInfoObj *_signinInfo;
    NSString *_code_id;
    NSMutableArray *_dataSource;
    long long _netErrorCount;
    struct CLLocationCoordinate2D _myCoor;
}

+ (id)setStringCharacterSpacing:(id)arg1;
@property(nonatomic) long long netErrorCount; // @synthesize netErrorCount=_netErrorCount;
@property(nonatomic) struct CLLocationCoordinate2D myCoor; // @synthesize myCoor=_myCoor;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSString *code_id; // @synthesize code_id=_code_id;
@property(retain, nonatomic) SigninInfoObj *signinInfo; // @synthesize signinInfo=_signinInfo;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) SceneSigninTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSString *job_id; // @synthesize job_id=_job_id;
- (void).cxx_destruct;
- (void)requestEndSignin;
- (void)requestSigninInfoSuccessHandler;
- (void)requestSigninInfo:(id)arg1;
- (void)requestStartSignin;
- (void)popViewController;
- (id)longitude;
- (id)latitude;
- (void)signinStatusEndPlayhandler;
- (void)signinStatusPlayingHandler;
- (void)signinStatusNoPlayHandler;
- (void)toSceneSignDetailViewControllerWithJob_id:(id)arg1 code_id:(id)arg2;
- (void)baidu_locationWithLatitude:(double)arg1 longitude:(double)arg2;
- (void)showPopView_noOpenLocation;
- (void)showPopView_endSignin;
- (void)showPopView_qrCode;
- (void)jumpToSetting;
- (_Bool)isOpenLocation;
- (void)readQrCodeBtnHandler:(id)arg1;
- (void)endSigninBtnHandler:(id)arg1;
- (void)startSigninBtnHandler:(id)arg1;
- (void)actionBtnHandler:(id)arg1;
- (void)signDetailBtnHandler:(id)arg1;
- (void)endSignin;
- (void)startSignin;
- (void)updateSignDetail:(id)arg1 sign:(id)arg2 errorCount:(id)arg3;
- (void)updateSignPerson:(id)arg1 sign:(id)arg2;
- (void)updateQrCode:(id)arg1;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)initBaiduLBS;
- (void)initView;
- (void)initData;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

