//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface ScheduleUIModel : NSObject
{
    _Bool _grayRightLine;
    NSString *_title;
    UIColor *_color;
    NSString *_iconPath;
}

+ (id)createDefaultModel:(id)arg1;
+ (id)createModel:(id)arg1 color:(id)arg2 iconPath:(id)arg3;
@property(nonatomic) _Bool grayRightLine; // @synthesize grayRightLine=_grayRightLine;
@property(retain, nonatomic) NSString *iconPath; // @synthesize iconPath=_iconPath;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 color:(id)arg2 iconPath:(id)arg3;

@end

