//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseView.h"

@class UIImageView, UILabel;

@interface ScheduleIconView : BaseView
{
    UIImageView *_leftLineView;
    UIImageView *_iconView;
    UIImageView *_rightLineView;
    UILabel *_titleLab;
}

@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *rightLineView; // @synthesize rightLineView=_rightLineView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *leftLineView; // @synthesize leftLineView=_leftLineView;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

