//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface Searcher : NSObject
{
    NSMutableArray *_delegateList;
    id <SearcherDelegate> _delegate;
    struct CSearchInterface *m_search;
    int _curReqPriority;
}

@property(nonatomic) int curReqPriority; // @synthesize curReqPriority=_curReqPriority;
@property(nonatomic) id <SearcherDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CSearchInterface *search; // @synthesize search=m_search;
- (void).cxx_destruct;
- (int)checkJson:(id)arg1;
- (void)onHandleGetBkgDataResultMsg;
- (id)parsePoiBkgDataResult;
- (CVArray_59d409db)calculatePOIBkgURLArray:(struct BMRect)arg1 mapLevel:(int)arg2;
- (void)onHandleSuggestionSearchMsg;
- (id)parseSuggestionResult;
- (_Bool)suggestionSearch:(id)arg1 searchType:(int)arg2 currentCity:(id)arg3 mapBound:(struct BMRect *)arg4 mapLevel:(int)arg5 loc:(struct BMPoint *)arg6;
- (_Bool)routePlanShareUrlSearch:(int)arg1 stPoint:(id)arg2 endPoint:(id)arg3 routeType:(int)arg4 routeIndex:(int)arg5;
- (_Bool)poiDetailShareUrlSearch:(id)arg1;
- (_Bool)poiRGCShareUrlSearch:(struct BMPoint)arg1 poiName:(id)arg2 poiAddress:(id)arg3;
- (void)onHandleRoutePlanShortUrlResult;
- (void)onHandleShortUrlResultMsg;
- (id)parseShortResult;
- (void)onHandleExceptionMsg:(long long)arg1;
- (void)onHandleBusLineDetailResultMsg;
- (id)parseBusLineDetailResult;
- (_Bool)busLineDetailSearch:(id)arg1 busLine:(id)arg2;
- (void)onHandleDistrictSearchResult;
- (_Bool)districtSearch:(id)arg1 district:(id)arg2;
- (void)onHandleRouteAddrResultMsg;
- (id)parseRouteAddrResult;
- (void)onHandleBikeRouteResultMsg;
- (void)onHandleFootRouteResultMsg;
- (void)onHandleCarRouteResultMsg;
- (id)parseCarRouteResult;
- (_Bool)routePlanByBikeStPoint:(id)arg1 endPoint:(id)arg2;
- (_Bool)routePlanByFoot:(int)arg1 stPoint:(id)arg2 endPoint:(id)arg3 mapLevel:(int)arg4 mapBound:(struct BMRect)arg5 exParameter:(id)arg6;
- (_Bool)routePlanByCar:(int)arg1 stPoint:(id)arg2 endPoint:(id)arg3 wayPoints:(id)arg4 carPlanKind:(int)arg5 mapLevel:(int)arg6 mapBound:(struct BMRect)arg7 itsRoute:(id)arg8 exParameter:(id)arg9;
- (void)onHandleBusRouteResultMsg;
- (id)parseBusRouteResult;
- (_Bool)routePlanByBus:(int)arg1 cityName:(id)arg2 stPoint:(id)arg3 endPoint:(id)arg4 routeKind:(int)arg5 mapLevel:(int)arg6 mapBound:(struct BMRect)arg7 exParameter:(id)arg8;
- (void)especialQueryResult;
- (void)cityQueryResut;
- (void)cityListResult;
- (void)poiDetailSearchPlaceResult;
- (void)poiIndoorResult;
- (void)poiListResult;
- (void)reverseGEOSearchResult;
- (void)geocodeSearchResult;
- (void)poiDetailSearchResult;
- (void)areaSearchResult;
- (_Bool)reverseGEOCodingSearch:(struct BMPoint)arg1;
- (_Bool)geocode:(id)arg1 withCity:(id)arg2;
- (_Bool)poiDetailSearch:(id)arg1;
- (_Bool)poiIndoorSearchWithKey:(id)arg1 PageNumber:(long long)arg2 PageItemCount:(long long)arg3 indoorId:(id)arg4 floor:(id)arg5 placeParameter:(id)arg6;
- (_Bool)forceSearchWithKey:(id)arg1 CityID:(long long)arg2 CityName:(id)arg3 PageNumber:(long long)arg4 PageItemCount:(long long)arg5 Bound:(struct BMRect *)arg6 Level:(double)arg7 PlaceParameter:(id)arg8;
- (_Bool)mapBoundSearchWithKey:(id)arg1 CityID:(long long)arg2 PageItemCount:(long long)arg3 Level:(double)arg4 PageIndex:(long long)arg5 Bound:(struct BMRect)arg6 PlaceParameter:(id)arg7;
- (_Bool)areaSearchWithKey:(id)arg1 CityID:(long long)arg2 PageItemCount:(long long)arg3 PageIndex:(long long)arg4 Bound:(struct BMRect)arg5 PlaceParameter:(id)arg6 SortType:(long long)arg7;
- (int)onAppDataOK:(long long)arg1 errorType:(long long)arg2;
- (void)onMsgProc:(long long)arg1 resultType:(long long)arg2 errorType:(long long)arg3;
- (void)onEngineMessage:(id)arg1;
- (void)onUpdateCityInfoMessage:(id)arg1;
- (void)onUpdateCityInfoMessage;
- (void)sendMessageToObserver:(long long)arg1 selectorWithInt:(SEL)arg2;
- (void)sendExceptionMessageToObserverWithIntMessage:(long long)arg1;
- (void)sendMessageToObserver:(id)arg1 selector:(SEL)arg2;
- (void)cancelSearch;
- (_Bool)removeObserver:(id)arg1;
- (_Bool)addObserver:(id)arg1;
- (void)unInitSearch;
- (id)init;
- (void)dealloc;

@end

