//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CircleView, NSString, UILabel;

@interface SegmentItem : UIView
{
    UILabel *_itemLab;
    CircleView *_logoView;
    NSString *_content;
}

@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) CircleView *logoView; // @synthesize logoView=_logoView;
@property(retain, nonatomic) UILabel *itemLab; // @synthesize itemLab=_itemLab;
- (void).cxx_destruct;
- (void)updateItemHeight;
- (id)initWithFrame:(struct CGRect)arg1 segmentWidth:(double)arg2 title:(id)arg3;

@end

