//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLPagerTabStripViewController.h"

#import "XLPagerTabStripViewControllerDataSource.h"
#import "XLPagerTabStripViewControllerDelegate.h"

@class NSMutableArray, NSString, SelectWorker_All, SelectWorker_Selected, UISegmentedControl;

@interface SelectWorkerViewController : XLPagerTabStripViewController <XLPagerTabStripViewControllerDataSource, XLPagerTabStripViewControllerDelegate>
{
    id <SelectWorkerViewControllerDelegate> _delegate;
    NSMutableArray *_selectedWorkerArray;
    NSString *_jobId;
    UISegmentedControl *_segmentBar;
    long long _currentSelectedIndex;
    SelectWorker_All *_selectedAllPage;
    SelectWorker_Selected *_selectedPage;
}

@property(retain, nonatomic) SelectWorker_Selected *selectedPage; // @synthesize selectedPage=_selectedPage;
@property(retain, nonatomic) SelectWorker_All *selectedAllPage; // @synthesize selectedAllPage=_selectedAllPage;
@property(nonatomic) long long currentSelectedIndex; // @synthesize currentSelectedIndex=_currentSelectedIndex;
@property(retain, nonatomic) UISegmentedControl *segmentBar; // @synthesize segmentBar=_segmentBar;
@property(copy, nonatomic) NSString *jobId; // @synthesize jobId=_jobId;
@property(retain, nonatomic) NSMutableArray *selectedWorkerArray; // @synthesize selectedWorkerArray=_selectedWorkerArray;
@property(nonatomic) id <SelectWorkerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)segmentControlChange:(id)arg1;
- (void)confirmBarItemClick;
- (void)pagerTabStripViewController:(id)arg1 updateIndicatorFromIndex:(long long)arg2 toIndex:(long long)arg3;
- (id)childViewControllersForPagerTabStripViewController:(id)arg1;
- (void)stopRefreshSelectedWorkerArray;
- (void)pullRefreshAllWorkerArray;
- (void)refreshSelectedWorkerArrayWithChangedWorker:(id)arg1;
- (void)refreshAllWorkerArrayWithChangedWorker:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

