//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

@class UILabel;

@interface SettingViewController : BaseTableViewController
{
    UILabel *_notificationStatusLabel;
}

@property(nonatomic) __weak UILabel *notificationStatusLabel; // @synthesize notificationStatusLabel=_notificationStatusLabel;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

