//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ShareSDKConnector : NSObject
{
}

+ (_Bool)checkPlatformNeedConnect:(unsigned long long)arg1;
+ (void)setPlatformConnectStatus:(_Bool)arg1 byPlatformType:(unsigned long long)arg2;
+ (id)platformConnectStatusInfo;
+ (void)callback:(id)arg1 resultData:(id)arg2;
+ (void)getImage:(id)arg1 onResult:(CDUnknownBlockType)arg2;
+ (void)getImage:(id)arg1 thumbImagePath:(id)arg2 result:(CDUnknownBlockType)arg3;
+ (void)connectFacebookMessenger:(Class)arg1;
+ (void)connectYiXin:(Class)arg1;
+ (void)connectKaKao:(Class)arg1;
+ (void)connectAliPaySocial:(Class)arg1;
+ (void)connectRenren:(Class)arg1;
+ (void)connectQQ:(Class)arg1 tencentOAuthClass:(Class)arg2;
+ (void)connectWeibo:(Class)arg1;
+ (void)connectWeChat:(Class)arg1 delegate:(id)arg2;
+ (void)connectWeChat:(Class)arg1;

@end

