//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSArray, NSString;

@interface SigninInfoObj : ObjectBeanBase
{
    NSString *_code_id;
    NSString *_code;
    NSString *_exception_counts;
    NSString *_sign_counts;
    NSString *_src_code;
    unsigned long long _status;
    NSString *_total_counts;
    NSArray *_user_list;
    NSString *_create_time;
}

@property(retain, nonatomic) NSString *create_time; // @synthesize create_time=_create_time;
@property(retain, nonatomic) NSArray *user_list; // @synthesize user_list=_user_list;
@property(retain, nonatomic) NSString *total_counts; // @synthesize total_counts=_total_counts;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *src_code; // @synthesize src_code=_src_code;
@property(retain, nonatomic) NSString *sign_counts; // @synthesize sign_counts=_sign_counts;
@property(retain, nonatomic) NSString *exception_counts; // @synthesize exception_counts=_exception_counts;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(retain, nonatomic) NSString *code_id; // @synthesize code_id=_code_id;
- (void).cxx_destruct;

@end

