//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonCellModelBase.h"

@class NSString;

@interface SignStatListCellModel : CommonCellModelBase
{
    _Bool _isSigned;
    NSString *_avatar;
    NSString *_name;
    NSString *_signTimes;
}

@property(nonatomic) _Bool isSigned; // @synthesize isSigned=_isSigned;
@property(retain, nonatomic) NSString *signTimes; // @synthesize signTimes=_signTimes;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
- (void).cxx_destruct;

@end

