//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSString;

@interface SigninListObj : ObjectBeanBase
{
    NSString *_img;
    NSString *_resume_name;
    NSString *_user_id;
}

@property(retain, nonatomic) NSString *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSString *resume_name; // @synthesize resume_name=_resume_name;
@property(retain, nonatomic) NSString *img; // @synthesize img=_img;
- (void).cxx_destruct;

@end

