//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSString;

@interface SpecialBannerObj : ObjectBeanBase
{
    NSString *_banner_desc;
    NSString *_banner_img;
    NSString *_banner_remark;
    NSString *_banner_title;
}

@property(copy, nonatomic) NSString *banner_title; // @synthesize banner_title=_banner_title;
@property(copy, nonatomic) NSString *banner_remark; // @synthesize banner_remark=_banner_remark;
@property(copy, nonatomic) NSString *banner_img; // @synthesize banner_img=_banner_img;
@property(copy, nonatomic) NSString *banner_desc; // @synthesize banner_desc=_banner_desc;
- (void).cxx_destruct;

@end

