//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSDKSession.h"

@class SSDKUserQueryConditional;

@interface SSDKGetUserInfoSession : SSDKSession
{
    unsigned long long _platformType;
    CDUnknownBlockType _authorizeHandler;
    CDUnknownBlockType _stateChangedHandler;
    SSDKUserQueryConditional *_conditional;
}

@property(retain, nonatomic) SSDKUserQueryConditional *conditional; // @synthesize conditional=_conditional;
@property(copy, nonatomic) CDUnknownBlockType stateChangedHandler; // @synthesize stateChangedHandler=_stateChangedHandler;
@property(copy, nonatomic) CDUnknownBlockType authorizeHandler; // @synthesize authorizeHandler=_authorizeHandler;
@property(nonatomic) unsigned long long platformType; // @synthesize platformType=_platformType;
- (void).cxx_destruct;
- (void)start;
- (id)initWithPlatformType:(unsigned long long)arg1 conditional:(id)arg2 authorizeHandler:(CDUnknownBlockType)arg3 stateChangedHandler:(CDUnknownBlockType)arg4;

@end

