//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface SSDKImage : NSObject
{
    NSURL *_URL;
}

+ (id)imageWithObject:(id)arg1;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (id)description;
- (void)getNativeImage:(CDUnknownBlockType)arg1;
- (id)initWithImage:(id)arg1 format:(id)arg2 settings:(id)arg3;
- (id)initWithURL:(id)arg1;

@end

