//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableData;

@interface SSPEvernoteDataStream : NSObject
{
    NSMutableData *_data;
    long long _offset;
}

@property(nonatomic) long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)readStringBody:(int)arg1;
- (void)endReadList;
- (void)beginReadList:(int *)arg1 size:(int *)arg2;
- (void)endReadSet;
- (void)beginReadSet:(int *)arg1 size:(int *)arg2;
- (void)endReadMap;
- (void)beginReadMap:(int *)arg1 valueType:(int *)arg2 size:(int *)arg3;
- (void)endReadField;
- (void)beginReadField:(id *)arg1 type:(int *)arg2 fieldID:(int *)arg3;
- (void)endReadStruct;
- (void)beginReadStruct:(id *)arg1;
- (void)endReadMessage;
- (void)beginReadMessage:(id *)arg1 type:(int *)arg2 sequenceID:(int *)arg3;
- (id)readBinary;
- (double)readDouble;
- (_Bool)readBool;
- (long long)readInt64;
- (int)readInt32;
- (short)readShort;
- (unsigned char)readByte;
- (id)readString;
- (void)readBytes:(char *)arg1 offset:(long long)arg2 len:(long long)arg3;
- (void)writeBool:(_Bool)arg1;
- (void)endWriteList;
- (void)beginWriteList:(int)arg1 size:(int)arg2;
- (void)endWriteSet;
- (void)beginWriteSet:(int)arg1 size:(int)arg2;
- (void)endWriteMap;
- (void)beginWriteMap:(int)arg1 valueType:(int)arg2 size:(int)arg3;
- (void)endWriteField;
- (void)writeFieldStop;
- (void)writeBinary:(id)arg1;
- (void)writeString:(id)arg1;
- (void)writeDouble:(double)arg1;
- (void)writeInt64:(long long)arg1;
- (void)writeShort:(short)arg1;
- (void)writeInt32:(int)arg1;
- (void)beginWriteField:(id)arg1 type:(int)arg2 fieldID:(int)arg3;
- (void)endWriteStruct;
- (void)beginWriteStruct:(id)arg1;
- (void)endWriteMessage;
- (void)beginWriteMessage:(id)arg1 type:(int)arg2 sequenceID:(int)arg3;
- (void)writeByte:(unsigned char)arg1;
- (void)writeBytes:(const char *)arg1 offset:(long long)arg2 len:(long long)arg3;
- (void)appendDataStream:(id)arg1;
@property(readonly, nonatomic) NSData *dataValue;
- (id)initWithData:(id)arg1;
- (id)init;

@end

