//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ISSDKAuthView.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSDictionary, NSString, UIActivityIndicatorView, UIButton, UITableView, UITextField;

@interface SSPInstapaperAuthView : UIView <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, ISSDKAuthView>
{
    id <ISSDKAuthSession> _session;
    NSDictionary *_userData;
    NSString *_callback;
    UITableView *_tableView;
    UIButton *_loginButton;
    UITextField *_loginNameField;
    UITextField *_passwordField;
    CDUnknownBlockType _stateChangedHandler;
    CDUnknownBlockType _rawStateChangedHandelr;
    UIView *_loadingPanel;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UIView *loadingPanel; // @synthesize loadingPanel=_loadingPanel;
@property(copy, nonatomic) CDUnknownBlockType rawStateChangedHandelr; // @synthesize rawStateChangedHandelr=_rawStateChangedHandelr;
@property(copy, nonatomic) CDUnknownBlockType stateChangedHandler; // @synthesize stateChangedHandler=_stateChangedHandler;
@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) UITextField *loginNameField; // @synthesize loginNameField=_loginNameField;
@property(retain, nonatomic) UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *callback; // @synthesize callback=_callback;
@property(retain, nonatomic) NSDictionary *userData; // @synthesize userData=_userData;
@property(retain, nonatomic) id <ISSDKAuthSession> session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)onAuthStateChanged:(CDUnknownBlockType)arg1;
- (void)cancel;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)loginButtonClickHandler:(id)arg1;
- (id)standardOAuthParams;
- (void)dealloc;
- (id)initWithSession:(id)arg1 userData:(id)arg2 callback:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

