//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, SSUIHorizontalTableView, UIView<ISSUIHorizontalTableViewItem>;

@protocol SSUIHorizontalTableViewDataSource <NSObject>
- (UIView<ISSUIHorizontalTableViewItem> *)tableView:(SSUIHorizontalTableView *)arg1 itemForIndexPath:(NSIndexPath *)arg2;
- (long long)itemNumberOfTableView:(SSUIHorizontalTableView *)arg1;
@end

