//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@interface SurplusCreditBean : ObjectBeanBase
{
    double _max_money;
    double _min_money;
    double _overdraft_money;
}

@property(nonatomic) double overdraft_money; // @synthesize overdraft_money=_overdraft_money;
@property(nonatomic) double min_money; // @synthesize min_money=_min_money;
@property(nonatomic) double max_money; // @synthesize max_money=_max_money;

@end

