//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface TencentReqMgr : NSObject
{
    NSMutableDictionary *_arrReq;
}

+ (id)instance;
@property(retain, nonatomic) NSMutableDictionary *arrReq; // @synthesize arrReq=_arrReq;
- (void).cxx_destruct;
- (_Bool)isContainMessageType:(long long)arg1 messageType:(unsigned long long)arg2;
- (_Bool)isContainMessageClss:(long long)arg1 messageClass:(Class)arg2;
- (id)tencentMessageObjFromMessageType:(long long)arg1 messageType:(unsigned long long)arg2;
- (id)tencentMessageObjFromMessageClass:(long long)arg1 messageClass:(Class)arg2;
- (id)tencentMessageObjFromSeq:(long long)arg1;
- (id)respFromSeq:(long long)arg1;
- (id)reqFromSeq:(long long)arg1;
- (long long)seqFromReq:(id)arg1;
- (long long)addReq:(id)arg1;
- (void)rmSeq:(long long)arg1;
- (void)rmReq:(id)arg1;

@end

