//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSEBaseUser.h"

@class NSString;

@interface ThirdPartLoginUser : SSEBaseUser
{
    _Bool _available;
    NSString *_uid;
    NSString *_avatar;
    NSString *_nickname;
    NSString *_token;
}

@property(nonatomic) _Bool available; // @synthesize available=_available;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)updateInfo:(id)arg1;

@end

