//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TripleDESUtil : NSObject
{
}

+ (id)tripleDES:(id)arg1 encryptOrDecrypt:(unsigned int)arg2 vkey:(const void *)arg3;
+ (id)tripleDESForStatistics:(id)arg1 encryptOrDecrypt:(unsigned int)arg2;
+ (id)tripleDESForPay:(id)arg1 encryptOrDecrypt:(unsigned int)arg2;
+ (id)tripleDES:(id)arg1 encryptOrDecrypt:(unsigned int)arg2;

@end

