//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSString, TableViewFooterView, TableViewHeaderView, TrusteeshipInfoObj, UITableView;

@interface TrusteeshipDetailViewController : BaseNavViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _hideBtn;
    _Bool _hideAdmin_remark;
    NSString *_trusteeship_id;
    unsigned long long _trusteeshipDetailType;
    UITableView *_tableView;
    TableViewHeaderView *_headerView;
    TableViewFooterView *_footView;
    NSArray *_titleArray;
    TrusteeshipInfoObj *_trusteeshipInfo;
    NSMutableArray *_requirementArray;
    NSString *_headerTitle;
    NSString *_btnTitle;
}

@property(nonatomic) _Bool hideAdmin_remark; // @synthesize hideAdmin_remark=_hideAdmin_remark;
@property(retain, nonatomic) NSString *btnTitle; // @synthesize btnTitle=_btnTitle;
@property(nonatomic) _Bool hideBtn; // @synthesize hideBtn=_hideBtn;
@property(retain, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) NSMutableArray *requirementArray; // @synthesize requirementArray=_requirementArray;
@property(retain, nonatomic) TrusteeshipInfoObj *trusteeshipInfo; // @synthesize trusteeshipInfo=_trusteeshipInfo;
@property(retain, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) TableViewFooterView *footView; // @synthesize footView=_footView;
@property(retain, nonatomic) TableViewHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) unsigned long long trusteeshipDetailType; // @synthesize trusteeshipDetailType=_trusteeshipDetailType;
@property(retain, nonatomic) NSString *trusteeship_id; // @synthesize trusteeship_id=_trusteeship_id;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)toTrusteeshipJobPaymentViewController:(id)arg1;
- (void)toPayViewController:(id)arg1;
- (void)toReleaseJobViewController;
- (void)checkTrusteeshipOrder:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)getTrusteeshipInfo;
- (id)tableView:(id)arg1 configTrusteeship3Cell:(id)arg2;
- (id)tableView:(id)arg1 configTrusteeship2Cell:(id)arg2;
- (id)tableView:(id)arg1 configLeaderPush_HireRequirementCell:(id)arg2;
- (id)tableView:(id)arg1 configTrusteeship1Cell:(id)arg2;
- (id)tableView:(id)arg1 configTrusteeshipBaseCell:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)payHandler:(id)arg1;
- (void)publishHandler:(id)arg1;
- (void)actionBtnHanler:(id)arg1;
- (void)pam_alertCallBackHandle:(long long)arg1;
- (void)tableViewHeaderRereshing;
- (void)initFootView;
- (void)initHeaderView;
- (void)initTableView;
- (void)initView;
- (void)initData;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

