//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EMChatBaseBubbleView.h"

@class NSArray, NSDataDetector, UIImageView, UILabel, UIView;

@interface TrusteeshipHelperBubbleView : EMChatBaseBubbleView
{
    NSDataDetector *_detector;
    NSArray *_urlMatches;
    UIImageView *_helperBgView;
    UIView *_titleView;
    UILabel *_titleLab;
    UIImageView *_midLineView;
    UIView *_actionView;
    UILabel *_statusLab;
    UILabel *_actionLab;
    UIImageView *_actionArrawView;
}

+ (long long)textLabelLineBreakModel;
+ (double)lineSpacing;
+ (id)textLabelFont;
+ (double)heightForBubbleWithObject:(id)arg1;
@property(retain, nonatomic) UIImageView *actionArrawView; // @synthesize actionArrawView=_actionArrawView;
@property(retain, nonatomic) UILabel *actionLab; // @synthesize actionLab=_actionLab;
@property(retain, nonatomic) UILabel *statusLab; // @synthesize statusLab=_statusLab;
@property(retain, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) UIImageView *midLineView; // @synthesize midLineView=_midLineView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIImageView *helperBgView; // @synthesize helperBgView=_helperBgView;
- (void).cxx_destruct;
- (void)setModel:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

