//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSString;

@interface TrusteeshipRequirementTagBean : ObjectBeanBase
{
    _Bool _is_default;
    _Bool _checked;
    _Bool _standard;
    NSString *_code;
    double _factor;
    NSString *_name;
}

@property(nonatomic, getter=isStandard) _Bool standard; // @synthesize standard=_standard;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool is_default; // @synthesize is_default=_is_default;
@property(nonatomic) double factor; // @synthesize factor=_factor;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

