//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (HUD)
- (void)hideHud;
- (void)showHint:(id)arg1 yOffset:(float)arg2;
- (void)showHint:(id)arg1;
- (void)showHudInView:(id)arg1 hint:(id)arg2;
- (void)setHUD:(id)arg1;
- (id)HUD;
@end

