//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMANProtocolData : NSObject
{
}

+ (id)md5Value:(id)arg1;
+ (id)timezoneString;
+ (id)languageString;
+ (id)countryString;
+ (id)appPirateString;
+ (_Bool)isAppPirate;
+ (id)appShortVersionString;
+ (id)appBundleVersionString;
+ (id)appDisplayNameString;
+ (id)appPackageNameString;
+ (id)carrierString;
+ (id)accessString;
+ (_Bool)isPad;
+ (id)deviceJailBreakString;
+ (_Bool)isDeviceJailBreak;
+ (id)orientationString;
+ (id)cpuString;
+ (id)osVersionString;
+ (id)osString;
+ (id)resolutionString;
+ (id)deviceModelString;
+ (id)UUIDMD5String;
+ (id)UUIDString;
+ (id)openUDIDString;
+ (id)deviceMacString;
+ (id)deviceIDVendorString;
+ (id)lngString;
+ (id)latString;
+ (id)timeMSString;
+ (id)timeString;
+ (id)dateString;

@end

