//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ObjectBeanBase.h"

@class NSArray, NSString;

@interface UserBean : ObjectBeanBase
{
    NSString *_img2;
    NSString *_birthday;
    NSString *_sex;
    NSString *_school_name;
    long long _isread;
    NSString *_tel;
    NSString *_img;
    NSString *_work_opinion;
    NSString *_type;
    NSString *_city;
    NSString *_id;
    NSString *_area;
    NSString *_height;
    NSString *_email;
    NSString *_age;
    NSString *_path;
    NSString *_province;
    NSString *_resumeid;
    NSString *_pdesc;
    NSString *_work_experience;
    NSString *_qq;
    NSString *_resume_name;
    NSArray *_word_experience_card;
}

@property(retain, nonatomic) NSArray *word_experience_card; // @synthesize word_experience_card=_word_experience_card;
@property(copy, nonatomic) NSString *resume_name; // @synthesize resume_name=_resume_name;
@property(copy, nonatomic) NSString *qq; // @synthesize qq=_qq;
@property(copy, nonatomic) NSString *work_experience; // @synthesize work_experience=_work_experience;
@property(copy, nonatomic) NSString *pdesc; // @synthesize pdesc=_pdesc;
@property(copy, nonatomic) NSString *resumeid; // @synthesize resumeid=_resumeid;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSString *age; // @synthesize age=_age;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *height; // @synthesize height=_height;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *work_opinion; // @synthesize work_opinion=_work_opinion;
@property(copy, nonatomic) NSString *img; // @synthesize img=_img;
@property(copy, nonatomic) NSString *tel; // @synthesize tel=_tel;
@property(nonatomic) long long isread; // @synthesize isread=_isread;
@property(copy, nonatomic) NSString *school_name; // @synthesize school_name=_school_name;
@property(copy, nonatomic) NSString *sex; // @synthesize sex=_sex;
@property(copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSString *img2; // @synthesize img2=_img2;
- (void).cxx_destruct;

@end

