//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Utility : NSObject
{
}

+ (_Bool)isIphone6Plus;
+ (_Bool)isIphone6;
+ (_Bool)isIphone5;
+ (_Bool)isIphone4;
+ (_Bool)isDeviceRetina3X;
+ (_Bool)isDeviceRetina;

@end

