//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseNavViewController.h"

#import "AJAlertViewDelegate.h"
#import "AJPickerButtonDelegate.h"
#import "HJCAjustNumButtonDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "WagePaymentRedBagSelectDelegate.h"

@class NSArray, NSMutableArray, NSString, RedBagBean, ReleaseJobObject, UITableView;

@interface WagePaymentViewController : BaseNavViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, WagePaymentRedBagSelectDelegate, AJPickerButtonDelegate, HJCAjustNumButtonDelegate, AJAlertViewDelegate>
{
    NSString *_jobId;
    UITableView *_wagePayTableView;
    RedBagBean *_redBagBean;
    NSMutableArray *_cellReuseIDArray;
    NSArray *_wageUnitSelectionArray;
    NSArray *_workCountUnitSelectionArray;
    long long _currentUnitSelectedIndex;
    double _wageTotal;
    long long _hireCount;
    double _redBagMoney;
    double _surplusPay;
    NSString *_wageUnitStr;
    NSString *_workCountUnitStr;
    NSString *_wageStr;
    NSString *_workCountStr;
    ReleaseJobObject *_releaseJobObj;
    long long _redBagCount;
}

@property(nonatomic) long long redBagCount; // @synthesize redBagCount=_redBagCount;
@property(retain, nonatomic) ReleaseJobObject *releaseJobObj; // @synthesize releaseJobObj=_releaseJobObj;
@property(copy, nonatomic) NSString *workCountStr; // @synthesize workCountStr=_workCountStr;
@property(copy, nonatomic) NSString *wageStr; // @synthesize wageStr=_wageStr;
@property(copy, nonatomic) NSString *workCountUnitStr; // @synthesize workCountUnitStr=_workCountUnitStr;
@property(copy, nonatomic) NSString *wageUnitStr; // @synthesize wageUnitStr=_wageUnitStr;
@property(nonatomic) double surplusPay; // @synthesize surplusPay=_surplusPay;
@property(nonatomic) double redBagMoney; // @synthesize redBagMoney=_redBagMoney;
@property(nonatomic) long long hireCount; // @synthesize hireCount=_hireCount;
@property(nonatomic) double wageTotal; // @synthesize wageTotal=_wageTotal;
@property(nonatomic) long long currentUnitSelectedIndex; // @synthesize currentUnitSelectedIndex=_currentUnitSelectedIndex;
@property(retain, nonatomic) NSArray *workCountUnitSelectionArray; // @synthesize workCountUnitSelectionArray=_workCountUnitSelectionArray;
@property(retain, nonatomic) NSArray *wageUnitSelectionArray; // @synthesize wageUnitSelectionArray=_wageUnitSelectionArray;
@property(retain, nonatomic) NSMutableArray *cellReuseIDArray; // @synthesize cellReuseIDArray=_cellReuseIDArray;
@property(retain, nonatomic) RedBagBean *redBagBean; // @synthesize redBagBean=_redBagBean;
@property(nonatomic) __weak UITableView *wagePayTableView; // @synthesize wagePayTableView=_wagePayTableView;
@property(copy, nonatomic) NSString *jobId; // @synthesize jobId=_jobId;
- (void).cxx_destruct;
- (void)readOrderInfo;
- (void)createPayOrder;
- (void)readRedBagCount;
- (void)jumpToPayPage:(id)arg1;
- (void)refreshCellWithRow:(long long)arg1;
- (void)refreshSurplusMoney;
- (void)refreshRedBag;
- (void)refreshWageTotal;
- (void)submitBtnClick:(id)arg1;
- (void)alertView:(id)arg1 buttonClick:(long long)arg2;
- (void)redBagDidSelected:(id)arg1;
- (void)numButtonDidChangeWithCurrentNum:(id)arg1 correct:(_Bool)arg2;
- (void)pickerButton:(id)arg1 didSelectRow:(long long)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)showErrorAlert;
- (void)showExitAlert;
- (void)refreshJobs;
- (void)endAllInputEvent;
- (void)submit;
- (void)popViewController;
- (void)initData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

