//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSRegularExpression, NSString, WTReGroup;

@interface WTReParser : NSObject
{
    NSString *_pattern;
    _Bool _ignoreCase;
    WTReGroup *_node;
    _Bool _finished;
    NSRegularExpression *_exactQuantifierRegex;
    NSRegularExpression *_rangeQuantifierRegex;
}

@property(readonly, nonatomic) NSString *pattern; // @synthesize pattern=_pattern;
- (void).cxx_destruct;
- (id)nextState:(id)arg1 finalState:(id)arg2 input:(id)arg3 position:(unsigned long long)arg4;
- (id)processNode:(id)arg1 fromState:(id)arg2 length:(unsigned long long)arg3;
- (id)reformatString:(id)arg1;
- (id)parseSubpattern:(id)arg1 inRange:(struct _NSRange)arg2 enclosed:(_Bool)arg3;
- (id)groupFromNodes:(id)arg1 enclosed:(_Bool)arg2;
- (id)parseCharset:(id)arg1 inRange:(struct _NSRange)arg2 enclosed:(_Bool)arg3;
- (void)raiseParserError:(id)arg1 atPos:(unsigned long long)arg2;
- (_Bool)isValidEscapedChar:(unsigned short)arg1 inCharset:(_Bool)arg2;
- (void)parsePattern;
- (void)dealloc;
- (id)initWithPattern:(id)arg1 ignoreCase:(_Bool)arg2;
- (id)initWithPattern:(id)arg1;

@end

