//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WTReCharacterBase.h"

@interface WTReAnyCharacter : WTReCharacterBase
{
}

- (id)debugDescription;
- (id)displayString:(id)arg1;
- (_Bool)matchesCharacter:(unsigned short)arg1;

@end

