//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPBasicTrackingInfo.h"

@class NSDate;

@interface XMPPTimeQueryInfo : XMPPBasicTrackingInfo
{
    NSDate *timeSent;
}

@property(readonly, nonatomic) NSDate *timeSent; // @synthesize timeSent;
- (void).cxx_destruct;
- (double)rtt;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 timeout:(double)arg3;

@end

