//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XMPPJID;

@interface XMPPRoomOccupantEasemob : NSObject
{
    XMPPJID *jid;
    NSString *affiliation;
    NSString *groupNick;
}

+ (id)roomOccupantMapFromDictionaries:(id)arg1;
+ (id)roomOccupantFromDictionary:(id)arg1;
@property(copy, nonatomic) NSString *groupNick; // @synthesize groupNick;
@property(retain, nonatomic) NSString *affiliation; // @synthesize affiliation;
@property(retain, nonatomic) XMPPJID *jid; // @synthesize jid;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;

@end

