//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSString, XMPPJID;

@interface XMPPMessageArchiving_Contact_CoreDataObject : NSManagedObject
{
}

- (void)didUpdateObject;
- (void)willInsertObject;
@property(retain, nonatomic) NSString *bareJidStr; // @dynamic bareJidStr;
@property(retain, nonatomic) XMPPJID *bareJid; // @dynamic bareJid;

// Remaining properties
@property(retain, nonatomic) NSString *mostRecentMessageBody; // @dynamic mostRecentMessageBody;
@property(retain, nonatomic) NSNumber *mostRecentMessageOutgoing; // @dynamic mostRecentMessageOutgoing;
@property(retain, nonatomic) NSDate *mostRecentMessageTimestamp; // @dynamic mostRecentMessageTimestamp;
@property(retain, nonatomic) XMPPJID *primitiveBareJid; // @dynamic primitiveBareJid;
@property(retain, nonatomic) NSString *primitiveBareJidStr; // @dynamic primitiveBareJidStr;
@property(retain, nonatomic) NSString *streamBareJidStr; // @dynamic streamBareJidStr;

@end

