//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IXMPPCompressor.h"

@class NSString;

@interface XMPPZIPCompressor : NSObject <IXMPPCompressor>
{
    struct z_stream_s _inflation_strm;
    struct z_stream_s _deflation_strm;
    char *_pOutput;
}

- (id)unzip:(id)arg1;
- (id)zip:(id)arg1;
- (id)processOutputData:(id)arg1;
- (id)processInputData:(id)arg1;
- (void)endCompression;
- (void)prepareCompression;
- (id)generateCompressionRequest;
- (_Bool)isSetupCompressionSuccess:(id)arg1;
- (_Bool)isSetupCompressionSuccessNode:(id)arg1;
- (id)setupCompressionFailureReason:(id)arg1;
- (_Bool)isSetupCompressionFailureReasonNode:(id)arg1;
- (_Bool)isSupportCompression:(id)arg1;
- (void)dealloc;
- (id)init;
- (_Bool)isSupportCompressionNode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

