//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "XMPPResource.h"

@class NSDate, NSString, XMPPJID, XMPPPresence;

@interface XMPPResourceMemoryStorageObject : NSObject <XMPPResource, NSCopying, NSCoding>
{
    XMPPJID *jid;
    XMPPPresence *presence;
    NSDate *presenceDate;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (long long)compare:(id)arg1;
- (void)updateWithPresence:(id)arg1;
- (id)presenceDate;
- (id)presence;
- (id)jid;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPresence:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

