//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface XMPPSRVResolver : NSObject
{
    id delegate;
    struct dispatch_queue_s *delegateQueue;
    struct dispatch_queue_s *resolverQueue;
    void *resolverQueueTag;
    NSString *srvName;
    double timeout;
    _Bool resolveInProgress;
    NSMutableArray *results;
    struct _DNSServiceRef_t *sdRef;
    int sdFd;
    struct dispatch_source_s *sdReadSource;
    struct dispatch_source_s *timeoutTimer;
}

+ (id)srvNameFromXMPPDomain:(id)arg1;
- (void).cxx_destruct;
- (void)stop;
- (void)startWithSRVName:(id)arg1 timeout:(double)arg2;
- (id)processRecord:(const void *)arg1 length:(unsigned short)arg2;
- (void)failWithDNSError:(int)arg1;
- (void)failWithError:(id)arg1;
- (void)succeed;
- (void)sortResults;
@property(readonly) double timeout; // @dynamic timeout;
@property(readonly) NSString *srvName; // @dynamic srvName;
- (void)dealloc;
- (id)initWithdDelegate:(id)arg1 delegateQueue:(struct dispatch_queue_s *)arg2 resolverQueue:(struct dispatch_queue_s *)arg3;

@end

