//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DDXMLElement, NSString, XMPPStream;

@protocol XMPPSASLAuthentication <NSObject>
+ (NSString *)mechanismName;
- (long long)handleAuth:(DDXMLElement *)arg1;
- (_Bool)start:(id *)arg1;
- (id)initWithStream:(XMPPStream *)arg1 password:(NSString *)arg2;

@optional
- (_Bool)shouldResendOpeningNegotiationAfterSuccessfulAuthentication;
@end

