//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPReceipt.h"

@interface XMPPReceiptReq : XMPPReceipt
{
}

+ (_Bool)isXMPPReceiptReq:(id)arg1;
+ (id)createFromXMPPMessage:(id)arg1;
- (id)toXMPPMessage;

@end

