//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DDXMLElement, EMGCDAsyncSocket, NSError, NSMutableDictionary, NSString, XMPPIQ, XMPPMessage, XMPPPresence, XMPPStream;

@protocol XMPPStreamDelegate

@optional
- (void)xmppStream:(XMPPStream *)arg1 didReceiveCustomElement:(DDXMLElement *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didSendCustomElement:(DDXMLElement *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 willUnregisterModule:(id)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didRegisterModule:(id)arg2;
- (void)xmppStream:(XMPPStream *)arg1 willSendP2PFeatures:(DDXMLElement *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveP2PFeatures:(DDXMLElement *)arg2;
- (void)xmppStreamDidDisconnect:(XMPPStream *)arg1 withError:(NSError *)arg2;
- (void)xmppStreamConnectDidTimeout:(XMPPStream *)arg1;
- (void)xmppStreamDidSendClosingStreamStanza:(XMPPStream *)arg1;
- (void)xmppStreamWasToldToDisconnect:(XMPPStream *)arg1;
- (void)xmppStreamDidChangeMyJID:(XMPPStream *)arg1;
- (void)xmppStream:(XMPPStream *)arg1 didFailToSendPresence:(XMPPPresence *)arg2 error:(NSError *)arg3;
- (void)xmppStream:(XMPPStream *)arg1 didFailToSendMessage:(XMPPMessage *)arg2 error:(NSError *)arg3;
- (void)xmppStream:(XMPPStream *)arg1 didFailToSendIQ:(XMPPIQ *)arg2 error:(NSError *)arg3;
- (void)xmppStream:(XMPPStream *)arg1 didSendPresence:(XMPPPresence *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didSendMessage:(XMPPMessage *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didSendIQ:(XMPPIQ *)arg2;
- (XMPPPresence *)xmppStream:(XMPPStream *)arg1 willSendPresence:(XMPPPresence *)arg2;
- (XMPPMessage *)xmppStream:(XMPPStream *)arg1 willSendMessage:(XMPPMessage *)arg2;
- (XMPPIQ *)xmppStream:(XMPPStream *)arg1 willSendIQ:(XMPPIQ *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveError:(DDXMLElement *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceivePresence:(XMPPPresence *)arg2;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveMessage:(XMPPMessage *)arg2;
- (_Bool)xmppStream:(XMPPStream *)arg1 didReceiveIQ:(XMPPIQ *)arg2;
- (void)xmppStreamDidFilterStanza:(XMPPStream *)arg1;
- (XMPPPresence *)xmppStream:(XMPPStream *)arg1 willReceivePresence:(XMPPPresence *)arg2;
- (XMPPMessage *)xmppStream:(XMPPStream *)arg1 willReceiveMessage:(XMPPMessage *)arg2;
- (XMPPIQ *)xmppStream:(XMPPStream *)arg1 willReceiveIQ:(XMPPIQ *)arg2;
- (NSString *)xmppStream:(XMPPStream *)arg1 alternativeResourceForConflictingResource:(NSString *)arg2;
- (id <XMPPCustomBinding>)xmppStreamWillBind:(XMPPStream *)arg1;
- (void)xmppStream:(XMPPStream *)arg1 didNotAuthenticate:(DDXMLElement *)arg2;
- (void)xmppStreamDidAuthenticate:(XMPPStream *)arg1;
- (void)xmppStream:(XMPPStream *)arg1 didNotRegister:(DDXMLElement *)arg2;
- (void)xmppStreamDidRegister:(XMPPStream *)arg1;
- (void)xmppStreamDidConnect:(XMPPStream *)arg1;
- (void)xmppStreamDidSecure:(XMPPStream *)arg1;
- (void)xmppStream:(XMPPStream *)arg1 didReceiveTrust:(struct __SecTrust *)arg2 completionHandler:(void (^)(_Bool))arg3;
- (void)xmppStream:(XMPPStream *)arg1 willSecureWithSettings:(NSMutableDictionary *)arg2;
- (void)xmppStreamDidStartNegotiation:(XMPPStream *)arg1;
- (void)xmppStream:(XMPPStream *)arg1 socketDidConnect:(EMGCDAsyncSocket *)arg2;
- (void)xmppStreamWillConnect:(XMPPStream *)arg1;
@end

