//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface XMPPPrivacyQueryInfo : NSObject
{
    int type;
    NSString *privacyListName;
    NSArray *privacyListItems;
    struct dispatch_source_s *timer;
}

+ (id)queryInfoWithType:(int)arg1 name:(id)arg2 items:(id)arg3;
+ (id)queryInfoWithType:(int)arg1 name:(id)arg2;
+ (id)queryInfoWithType:(int)arg1;
@property(nonatomic) struct dispatch_source_s *timer; // @synthesize timer;
@property(readonly, nonatomic) NSArray *privacyListItems; // @synthesize privacyListItems;
@property(readonly, nonatomic) NSString *privacyListName; // @synthesize privacyListName;
@property(readonly, nonatomic) int type; // @synthesize type;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (id)initWithType:(int)arg1 name:(id)arg2 items:(id)arg3;

@end

