//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, XMPPStream;

@interface XMPPIDTracker : NSObject
{
    XMPPStream *xmppStream;
    struct dispatch_queue_s *queue;
    NSMutableDictionary *dict;
    void *queueTag;
    NSObject *lock;
}

- (void).cxx_destruct;
- (id)allIDs;
- (void)removeAllIDs;
- (void)removeID:(id)arg1;
- (unsigned long long)numberOfIDs;
- (_Bool)invokeForElement:(id)arg1 withObject:(id)arg2;
- (_Bool)invokeForID:(id)arg1 withObject:(id)arg2;
- (void)addElement:(id)arg1 trackingInfo:(id)arg2;
- (void)addID:(id)arg1 trackingInfo:(id)arg2;
- (void)addElement:(id)arg1 block:(CDUnknownBlockType)arg2 timeout:(double)arg3;
- (void)addID:(id)arg1 block:(CDUnknownBlockType)arg2 timeout:(double)arg3;
- (void)addElement:(id)arg1 target:(id)arg2 selector:(SEL)arg3 timeout:(double)arg4;
- (void)addID:(id)arg1 target:(id)arg2 selector:(SEL)arg3 timeout:(double)arg4;
- (void)dealloc;
- (id)initWithStream:(id)arg1 dispatchQueue:(struct dispatch_queue_s *)arg2;
- (id)initWithDispatchQueue:(struct dispatch_queue_s *)arg1;
- (id)init;

@end

