//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XMPPJID, XMPPStream, XMPPvCardTemp, XMPPvCardTempModule;

@protocol XMPPvCardTempModuleStorage <NSObject>
- (_Bool)shouldFetchvCardTempForJID:(XMPPJID *)arg1 xmppStream:(XMPPStream *)arg2;
- (XMPPvCardTemp *)myvCardTempForXMPPStream:(XMPPStream *)arg1;
- (void)setvCardTemp:(XMPPvCardTemp *)arg1 forJID:(XMPPJID *)arg2 xmppStream:(XMPPStream *)arg3;
- (XMPPvCardTemp *)vCardTempForJID:(XMPPJID *)arg1 xmppStream:(XMPPStream *)arg2;
- (_Bool)configureWithParent:(XMPPvCardTempModule *)arg1 queue:(struct dispatch_queue_s *)arg2;
@end

