//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPCoreDataStorage.h"

#import "XMPPvCardAvatarStorage.h"
#import "XMPPvCardTempModuleStorage.h"

@class NSString;

@interface XMPPvCardCoreDataStorage : XMPPCoreDataStorage <XMPPvCardAvatarStorage, XMPPvCardTempModuleStorage>
{
}

+ (id)sharedInstance;
- (_Bool)shouldFetchvCardTempForJID:(id)arg1 xmppStream:(id)arg2;
- (id)myvCardTempForXMPPStream:(id)arg1;
- (void)setvCardTemp:(id)arg1 forJID:(id)arg2 xmppStream:(id)arg3;
- (id)vCardTempForJID:(id)arg1 xmppStream:(id)arg2;
- (void)clearvCardTempForJID:(id)arg1 xmppStream:(id)arg2;
- (id)photoHashForJID:(id)arg1 xmppStream:(id)arg2;
- (id)photoDataForJID:(id)arg1 xmppStream:(id)arg2;
- (void)commonInit;
- (_Bool)configureWithParent:(id)arg1 queue:(struct dispatch_queue_s *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

