//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DDXMLElement, NSArray, UIImage, XMPPJID, XMPPPresence, XMPPRoster, XMPPStream;

@protocol XMPPRosterStorage <NSObject>
- (NSArray *)jidsForXMPPStream:(XMPPStream *)arg1;
- (void)clearAllUsersAndResourcesForXMPPStream:(XMPPStream *)arg1;
- (void)clearAllResourcesForXMPPStream:(XMPPStream *)arg1;
- (_Bool)userExistsWithJID:(XMPPJID *)arg1 xmppStream:(XMPPStream *)arg2;
- (void)handlePresence:(XMPPPresence *)arg1 xmppStream:(XMPPStream *)arg2;
- (void)handleRosterItem:(DDXMLElement *)arg1 xmppStream:(XMPPStream *)arg2;
- (void)endRosterPopulationForXMPPStream:(XMPPStream *)arg1;
- (void)beginRosterPopulationForXMPPStream:(XMPPStream *)arg1;
- (_Bool)configureWithParent:(XMPPRoster *)arg1 queue:(struct dispatch_queue_s *)arg2;

@optional
- (void)setPhoto:(UIImage *)arg1 forUserWithJID:(XMPPJID *)arg2 xmppStream:(XMPPStream *)arg3;
@end

