//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class XMPPvCardCoreDataStorageObject, XMPPvCardTemp;

@interface XMPPvCardTempCoreDataStorageObject : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) XMPPvCardCoreDataStorageObject *vCard; // @dynamic vCard;
@property(retain, nonatomic) XMPPvCardTemp *vCardTemp; // @dynamic vCardTemp;
@end

