//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPModule.h"

@class XMPPIDTracker, XMPPvCardTemp;

@interface XMPPvCardTempModule : XMPPModule
{
    id <XMPPvCardTempModuleStorage> _xmppvCardTempModuleStorage;
    XMPPIDTracker *_myvCardTracker;
}

@property(readonly, nonatomic) id <XMPPvCardTempModuleStorage> xmppvCardTempModuleStorage; // @synthesize xmppvCardTempModuleStorage=_xmppvCardTempModuleStorage;
- (void).cxx_destruct;
- (void)xmppStreamDidDisconnect:(id)arg1 withError:(id)arg2;
- (_Bool)xmppStream:(id)arg1 didReceiveIQ:(id)arg2;
- (void)handleMyvcard:(id)arg1 withInfo:(id)arg2;
- (void)_fetchvCardTempForJID:(id)arg1;
- (void)_updatevCardTemp:(id)arg1 forJID:(id)arg2;
- (void)updateMyvCardTemp:(id)arg1;
@property(readonly, nonatomic) XMPPvCardTemp *myvCardTemp;
- (id)vCardTempForJID:(id)arg1 shouldFetch:(_Bool)arg2;
- (void)fetchvCardTempForJID:(id)arg1 ignoreStorage:(_Bool)arg2;
- (void)fetchvCardTempForJID:(id)arg1;
- (void)dealloc;
- (void)deactivate;
- (_Bool)activate:(id)arg1;
- (id)initWithvCardStorage:(id)arg1 dispatchQueue:(struct dispatch_queue_s *)arg2;
- (id)initWithvCardStorage:(id)arg1;
- (id)initWithDispatchQueue:(struct dispatch_queue_s *)arg1;
- (id)init;

@end

