//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMPPModule.h"

@class NSData, NSDate, XMPPJID, XMPPTime;

@interface XMPPAutoTime : XMPPModule
{
    double recalibrationInterval;
    XMPPJID *targetJID;
    double timeDifference;
    unsigned long long lastCalibrationTime;
    struct dispatch_source_s *recalibrationTimer;
    _Bool awaitingQueryResponse;
    XMPPTime *xmppTime;
    NSData *lastServerAddress;
    NSDate *systemUptimeChecked;
    double systemUptime;
}

@property(retain, nonatomic) NSDate *systemUptimeChecked; // @synthesize systemUptimeChecked;
@property(retain, nonatomic) NSData *lastServerAddress; // @synthesize lastServerAddress;
- (void).cxx_destruct;
- (void)xmppStreamDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)xmppStreamDidAuthenticate:(id)arg1;
- (void)xmppStream:(id)arg1 socketDidConnect:(id)arg2;
- (void)xmppTime:(id)arg1 didNotReceiveResponse:(id)arg2 dueToTimeout:(double)arg3;
- (void)xmppTime:(id)arg1 didReceiveResponse:(id)arg2 withRTT:(double)arg3;
- (void)stopRecalibrationTimer;
- (void)startRecalibrationTimer;
- (void)updateRecalibrationTimer;
- (void)handleRecalibrationTimerFire;
- (void)systemClockDidChange:(id)arg1;
@property _Bool respondsToQueries;
@property(readonly) unsigned long long lastCalibrationTime;
@property(readonly) NSDate *date;
@property(readonly) double timeDifference;
@property(retain) XMPPJID *targetJID;
@property double recalibrationInterval;
- (void)dealloc;
- (void)deactivate;
- (_Bool)activate:(id)arg1;
- (id)initWithDispatchQueue:(struct dispatch_queue_s *)arg1;

@end

