//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, NSString;

@interface XMPPGroupCoreDataStorageObject : NSManagedObject
{
}

+ (id)fetchOrInsertGroupName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (id)insertGroupName:(id)arg1 inManagedObjectContext:(id)arg2;
+ (void)clearEmptyGroupsInManagedObjectContext:(id)arg1;
- (void)removeUsers:(id)arg1;
- (void)addUsers:(id)arg1;
- (void)removeUsersObject:(id)arg1;
- (void)addUsersObject:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSSet *users; // @dynamic users;

@end

