//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString, UIColor, UITapGestureRecognizer;

@interface ZTFeatureMaskView : UIView
{
    id <ZTFeatureMaskViewDelegate> _delegate;
    CDUnknownBlockType _featureDidClosed;
    UIColor *_maskColor;
    double _maskAlpha;
    NSString *_oneTimeKey;
    NSMutableArray *_transparencies;
    UIView *_maskedView;
    UITapGestureRecognizer *_closeGuesture;
    struct UIEdgeInsets _edgeInsetsInMaskedView;
}

+ (void)clearAllInMaskedView:(id)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *closeGuesture; // @synthesize closeGuesture=_closeGuesture;
@property(retain, nonatomic) UIView *maskedView; // @synthesize maskedView=_maskedView;
@property(retain, nonatomic) NSMutableArray *transparencies; // @synthesize transparencies=_transparencies;
@property(retain, nonatomic) NSString *oneTimeKey; // @synthesize oneTimeKey=_oneTimeKey;
@property(nonatomic) struct UIEdgeInsets edgeInsetsInMaskedView; // @synthesize edgeInsetsInMaskedView=_edgeInsetsInMaskedView;
@property(nonatomic) double maskAlpha; // @synthesize maskAlpha=_maskAlpha;
@property(retain, nonatomic) UIColor *maskColor; // @synthesize maskColor=_maskColor;
@property(copy, nonatomic) CDUnknownBlockType featureDidClosed; // @synthesize featureDidClosed=_featureDidClosed;
@property(nonatomic) __weak id <ZTFeatureMaskViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addCloseButtonWithImage:(id)arg1 referenceView:(id)arg2 withInnerSpacingLeft:(double)arg3 spacingTop:(double)arg4;
- (void)addCloseButtonWithImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingRight:(double)arg3 spacingBottom:(double)arg4;
- (void)addCloseButtonWithImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingRight:(double)arg3 spacingTop:(double)arg4;
- (void)addCloseButtonWithImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingLeft:(double)arg3 spacingBottom:(double)arg4;
- (void)addCloseButtonWithImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingLeft:(double)arg3 spacingTop:(double)arg4;
- (void)addCloseButtonWithImage:(id)arg1 inReferenceView:(id)arg2;
- (void)addCloseButtonWithImage:(id)arg1 inRect:(struct CGRect)arg2;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withInnerSpacingLeft:(double)arg3 spacingBottom:(double)arg4;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withInnerSpacingLeft:(double)arg3 spacingTop:(double)arg4;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingRight:(double)arg3 spacingBottom:(double)arg4;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingRight:(double)arg3 spacingTop:(double)arg4;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingLeft:(double)arg3 spacingBottom:(double)arg4;
- (void)addImage:(id)arg1 referenceView:(id)arg2 withOuterSpacingLeft:(double)arg3 spacingTop:(double)arg4;
- (void)addImage:(id)arg1 inReferenceView:(id)arg2;
- (void)addImage:(id)arg1 inRect:(struct CGRect)arg2;
- (void)addTransparencyRect:(struct CGRect)arg1 radius:(double)arg2;
- (void)addTransparencyInReferenceView:(id)arg1 radius:(double)arg2 innerRect:(struct CGRect)arg3;
- (void)addTransparencyInReferenceView:(id)arg1 wider:(double)arg2 radius:(double)arg3;
- (void)addTransparencyInReferenceView:(id)arg1 radius:(double)arg2;
- (void)addTransparencyInReferenceView:(id)arg1 innerRect:(struct CGRect)arg2;
- (void)addTransparencyInReferenceView:(id)arg1 wider:(double)arg2;
- (void)addTransparencyInReferenceView:(id)arg1;
- (void)addTransparencyRect:(struct CGRect)arg1;
- (void)removeShowing;
- (_Bool)canShow;
- (void)markShowed;
- (void)show;
- (void)setEdgesInMaskedView:(struct UIEdgeInsets)arg1;
- (void)clickCloseButton:(id)arg1;
- (void)clickMaskView;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithOneTimeKey:(id)arg1;
- (id)init;

@end

